---
title: src/main.tscn
---
:toc:

== src / main.tscn

=== Diagram
[plantuml]
....
class R as "Main" <<(C,lightgreen) Control>> {
}
class N1 as "ColorRect" <<(C,lightgreen) ColorRect>> {
}
class N2 as "World" <<(N,lightskyblue) Node2D>> {
}
class N3 as "StaticBody2D" <<(S,lightskyblue) StaticBody2D>> {
}
class N4 as "ColorRect" <<(C,lightgreen) ColorRect>> {
}
class N5 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N6 as "Player" <<(C,lightskyblue) CharacterBody2D>> {
  ~ dashed
  ~ jumped
  ~ landed
  ~ failed
  ~ reached
---
  - SPEED
  - DASH_SPEED
  - CLIMBING_SPEED
  - JUMP_VELOCITY
  - GRAVITY
  - ALLOWED_TIME_TO_JUMP
  - DASH_TIME
  - DASH_ATTENUATION
  - MAX_DASH_COUNT
  - MAX_CLIMBING_TIME
  - DEFAULT_SCALE
  * GhostEffect
  * LandedEffect
  * fatigue_curve
  * state
  * falling_time
  * dash_rest_time
  * dash_rest_count
  * climb_rest_time
  * sprite_tween
  * last_owner_name
  * playable
  * restart_position
---
  + _ready()
  + _physics_process()
  + compute_state()
  + is_just_input_action()
  + is_input_action()
  + animate()
  + animate_with()
  + compute_dashed()
  + idle()
  + walk_right()
  + walk_left()
  + turn_right()
  + turn_left()
  + dash()
  + lock()
  + unlock()
  + vibrate()
  + get_state_by()
  + tween_sprite()
  + update_sprite_states_shader_parameters()
  + spawn_ghost_effect()
  + current_sprite_state()
  + is_dashed()
  + _on_dashed()
  + _on_jumped()
  + _on_landed()
  + _on_failed()
  + _on_reached()
  + _on_frame_subject_area_entered()
  + _on_frame_subject_area_exited()
  + _on_failure_collision_area_entered()
}
class N7 as "FirstStepsBGMPlayable" <<(N,darkgray) Node>> {
---
  + _ready()
}
R --o N1
R --o N2
R --o N7
N2 --o N3
N2 --o N6
N3 --o N4
N3 --o N5
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _ready
.$World/Player
```gdscript
func _ready() -> void:
	playable = true
	if last_owner_name == owner.name:
		position = restart_position
	else:
		restart_position = position
	last_owner_name = owner.name
```
.$FirstStepsBGMPlayable
```gdscript
func _ready() -> void:
	BGM.first_steps()
```
==== _physics_process
.$World/Player
```gdscript
func _physics_process(delta: float) -> void:
	var dx := Input.get_axis(&'move_left', &'move_right')
	var dy := Input.get_axis(&'move_up', &'move_down')
	var direction := Vector2(dx, dy)
	var last_state := state
	state = compute_state(delta, direction)
	match state:
		State.CLIMBING:
			dx = 0
			velocity.y = dy * CLIMBING_SPEED
		State.DASHED:
			velocity = direction.normalized() * DASH_SPEED
		State.DASHING:
			velocity *= DASH_ATTENUATION * delta
		State.EXHAUSTED:
			dx = 0
		State.FAILED:
			velocity.x = lerp(velocity.x, 0.0, 0.2)
			velocity.y = lerp(velocity.y, 0.0, 0.2)
		State.FALLING:
			if last_state == State.CLIMBING \
			and dy < 0:
				velocity.y = JUMP_VELOCITY * 0.8
			else:
				if velocity.y < JUMP_VELOCITY * 0.85:
					velocity.y += GRAVITY * 1.15 * delta
				else:
					velocity.y += GRAVITY * delta
		State.JUMPED:
			velocity.y = JUMP_VELOCITY
		State.LOCKED:
			dx = 0
			velocity = Vector2(0, 0)
		_: pass
	
	if not playable: dx = 0
	if not (state == State.DASHED or state == State.DASHING):
		if dx: velocity.x = dx * SPEED
		else: velocity.x = move_toward(velocity.x, 0, SPEED)

	animate(playable)
	move_and_slide()
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Main# [.node-type.type-control]#Control#
** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
** [.node-name.type-2d]#World# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#StaticBody2D# [.node-type.type-2d]#StaticBody2D#
**** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
**** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
*** [.node-name.type-2d]#Player# [.node-type.type-2d]#link:/scenes/src/player/player.tscn[res://src/player/player.tscn]#
** [.node-name.type-plain]#FirstStepsBGMPlayable# [.node-type.type-plain]#link:/scenes/src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn[res://src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn]#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`3`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$ColorRect# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$World/StaticBody2D/ColorRect# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*offset_top* a|`1038.0`
|*offset_right* a|`1911.0`
|*offset_bottom* a|`1078.0`
|*color* a|`Color(0.309065, 0.200807, 0.180328, 1)`
|===
[.node-property.node-2d]
.#$World/StaticBody2D/CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(956.25, 1056)`
|*shape* a|`SubResource("RectangleShape2D_1fq2a")`
|===
[.node-property.node-2d]
.#$World/Player# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*position* a|`Vector2(488, 874)`
|===




