---
title: src/main.tscn
---
:toc:

== src / main.tscn

=== Diagram
[plantuml]
....
class R as "Main" <<(C,#90EE90) Control>> {
}
class N1 as "ColorRect" <<(C,#90EE90) ColorRect>> {
}
class N2 as "World" <<(N,#87CEFA) Node2D>> {
}
class N3 as "StaticBody2D" <<(S,#87CEFA) StaticBody2D>> {
}
class N4 as "ColorRect" <<(C,#90EE90) ColorRect>> {
}
class N5 as "CollisionShape2D" <<(C,#87CEFA) CollisionShape2D>> {
}
class N6 as "Player" <<(C,#87CEFA) CharacterBody2D>> {
  ~ dashed
  ~ failed
---
  - SPEED
  - DASH_SPEED
  - JUMP_VELOCITY
  - GRAVITY
  - ALLOWED_TIME_TO_JUMP
  - DASH_TIME
  - DASH_ATTENUATION
  - MAX_DASH_COUNT
  * GhostEffect
  * falling_time
  * dash_rest_time
  * dash_rest_count
  * grounding
  * is_failed
---
  + _physics_process()
  + animate()
  + vibrate()
  + get_state()
  + update_sprite_states_shader_parameters()
  + spawn_ghost_effect()
  + current_sprite_state()
  + is_dashed()
  + _on_dashed()
  + _on_failed()
  + _on_frame_subject_area_entered()
  + _on_frame_subject_area_exited()
  + _on_failure_collision_area_entered()
}
class N7 as "FirstStepsBGMPlayable" <<(N,#A9A9A9) Node>> {
---
  + _ready()
}
R --o N1
R --o N2
R --o N7
N2 --o N3
N2 --o N6
N3 --o N4
N3 --o N5
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _physics_process
.$World/Player
```gdscript
func _physics_process(delta: float) -> void:
	if is_failed:
		return
	if dash_rest_time > 0:
		dash_rest_time -= delta
		velocity *= DASH_ATTENUATION * delta
	else:
		# Add the gravity.
		if not is_on_floor():
			velocity.y += GRAVITY * delta
			falling_time += delta
			grounding = false
		else:
			if not grounding: vibrate('Landed')
			grounding = true
			falling_time = 0
			dash_rest_count = MAX_DASH_COUNT

		# Handle jump.
		if Input.is_action_just_pressed("move_jump") and falling_time < ALLOWED_TIME_TO_JUMP:
			velocity.y = JUMP_VELOCITY

		var direction_x := Input.get_axis("move_left", "move_right")
		if direction_x:
			velocity.x = direction_x * SPEED
		else:
			velocity.x = move_toward(velocity.x, 0, SPEED)

		# Handle dash.
		if Input.is_action_just_pressed("move_dash") && dash_rest_count > 0:
			var direction_y := Input.get_axis("move_up", "move_down")
			var direction = Vector2(direction_x, direction_y).normalized()
			if direction:
				dashed.emit()
				velocity = direction * DASH_SPEED
				dash_rest_time = DASH_TIME
				dash_rest_count -= 1
	animate()
	move_and_slide()
```
==== _ready
.$FirstStepsBGMPlayable
```gdscript
func _ready() -> void:
	BGM.first_steps()
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Main# [.node-type.type-control]#Control#
** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
** [.node-name.type-2d]#World# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#StaticBody2D# [.node-type.type-2d]#StaticBody2D#
**** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
**** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
*** [.node-name.type-2d]#Player# [.node-type.type-2d]#link:/scenes/src/player/player.tscn[res://src/player/player.tscn]#
** [.node-name.type-plain]#FirstStepsBGMPlayable# [.node-type.type-plain]#link:/scenes/src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn[res://src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn]#


=== Signal Connections
NOTE: No signal connections.



=== Properties
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`3`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|===
.#$ColorRect# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`1`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|===
.#$World/StaticBody2D/ColorRect# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*offset_top* |`1038.0`
|*offset_right* |`1911.0`
|*offset_bottom* |`1078.0`
|*color* |`Color(0.309065, 0.200807, 0.180328, 1)`
|===
.#$World/StaticBody2D/CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(956.25, 1056)`
|*shape* |`SubResource("RectangleShape2D_1fq2a")`
|===
.#$World/Player# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*position* |`Vector2(488, 874)`
|===




