---
title: src/main.tscn
---
:toc:

== src / main.tscn

=== Diagram
[plantuml]
....
class ROOT as "Main" <<(C,lightgreen) Control>> {
}
class ColorRect as "ColorRect" <<(C,lightgreen) ColorRect>> {
}
class World as "World" <<(N,lightskyblue) Node2D>> {
}
class World_StaticBody2D as "StaticBody2D" <<(S,lightskyblue) StaticBody2D>> {
}
class World_StaticBody2D_ColorRect as "ColorRect" <<(C,lightgreen) ColorRect>> {
}
class World_StaticBody2D_CollisionShape2D as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class World_Player as "Player" <<(C,lightskyblue) CharacterBody2D>> {
  ~ dashed
  ~ failed
---
  - SPEED
  - DASH_SPEED
  - JUMP_VELOCITY
  - GRAVITY
  - ALLOWED_TIME_TO_JUMP
  - DASH_TIME
  - DASH_ATTENUATION
  - MAX_DASH_COUNT
  * GhostEffect
  * falling_time
  * dash_rest_time
  * dash_rest_count
  * grounding
  * is_failed
---
  + _physics_process()
  + animate()
  + vibrate()
  + get_state()
  + update_sprite_states_shader_parameters()
  + spawn_ghost_effect()
  + current_sprite_state()
  + is_dashed()
  + _on_dashed()
  + _on_failed()
  + _on_frame_subject_area_entered()
  + _on_frame_subject_area_exited()
  + _on_failure_collision_area_entered()
}
class FirstStepsBGMPlayable as "FirstStepsBGMPlayable" <<(N,darkgray) Node>> {
---
  + _ready()
}
ROOT --o ColorRect
ROOT --o World
ROOT --o FirstStepsBGMPlayable
World --o World_StaticBody2D
World --o World_Player
World_StaticBody2D --o World_StaticBody2D_ColorRect
World_StaticBody2D --o World_StaticBody2D_CollisionShape2D
left to right direction

....




=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Main# [.node-type.type-control]#Control#
** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
** [.node-name.type-2d]#World# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#StaticBody2D# [.node-type.type-2d]#StaticBody2D#
**** [.node-name.type-control]#ColorRect# [.node-type.type-control]#ColorRect#
**** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
*** [.node-name.type-2d]#Player# [.node-type.type-2d]#link:/scenes/src/player/player.tscn[res://src/player/player.tscn]#
** [.node-name.type-other]#FirstStepsBGMPlayable# [.node-type.type-other]#link:/scenes/src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn[res://src/mixins/first_steps_bgm_playable/first_steps_bgm_playable.tscn]#




=== Signal Connections
NOTE: No signal connections.

=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*size* |`Vector2(1915.5, 49)`
|_node_ |*layout_mode* |`3`
|_node_ |*anchors_preset* |`15`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`15`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*offset_top* |`1038.0`
|_node_ |*offset_right* |`1911.0`
|_node_ |*offset_bottom* |`1078.0`
|_node_ |*color* |`Color(0.309065, 0.200807, 0.180328, 1)`
|_node_ |*position* |`Vector2(956.25, 1056)`
|_node_ |*shape* |`SubResource("RectangleShape2D_1fq2a")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*position* |`Vector2(488, 874)`
|===




