---
title: debug/hair/node_2d.tscn
---
:toc:

== debug / hair / node_2d.tscn

=== Diagram
[plantuml]
....
class R as "Node2D" <<(N,lightskyblue) Node2D>> {
}
class N1 as "Hair" <<(N,lightskyblue) Node2D>> {
  - SEGMENT_COUNT
  - MAX_DISTANCE
  - LERP_SPEED
  - BASE_RADIUS
  - OUTLINE_WIDTH
  - DECREASE_RATE
  * base_color
  * dash_color
  * color
  * positions
---
  + _ready()
  + _process()
  + _draw()
  + set_dashed()
}
R --o N1
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _ready
.$Hair
```gdscript
func _ready() -> void:
	positions.clear()
	for i in range(SEGMENT_COUNT):
		positions.append(global_position)
```
==== _process
.$Hair
```gdscript
func _process(delta: float) -> void:
	if positions.is_empty(): return
	positions[0] = global_position
	
	for i in range(1, SEGMENT_COUNT):
		var target = positions[i-1]
		var diff = positions[i] - target
		if diff.length() > MAX_DISTANCE:
			positions[i] = target + diff.normalized() * MAX_DISTANCE
		positions[i] = positions[i].lerp(target, LERP_SPEED * delta)
	
	queue_redraw()
```
==== _draw
.$Hair
```gdscript
func _draw() -> void:
	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r + OUTLINE_WIDTH, Color.BLACK)

	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r, color)
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Node2D# [.node-type.type-2d]#Node2D#
** [.node-name.type-2d]#Hair# [.node-type.type-2d]#link:/scenes/src/player/hair/hair.tscn[res://src/player/hair/hair.tscn]#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(-25, 5)`
|*scale* a|`Vector2(6, 6)`
|===
[.node-property.node-2d]
.#$Hair# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(5.3333335, -0.3333335)`
|*lerp_speed* a|`15.0`
|===




