---
title: src/beginning/chapters/chapter/chapter.tscn
---
:toc:

== src / beginning / chapters / chapter / chapter.tscn

=== Diagram
[plantuml]
....
class R as "Chapter" <<(M,lightgreen) MarginContainer>> {
  * play_opening
  * resource
  * focus_animation_skip
---
  + set_play_opening()
  + focus_returned()
  + selected()
  + unselected()
  + _on_focus_entered()
}
class N1 as "Placeholder" <<(T,lightgreen) TextureRect>> {
}
class N2 as "Sprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N3 as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
R --o N1
R --o N2
R --o N3
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_focus_entered, R::focus_entered)
....





=== Instantiators
* link:/scenes/src/beginning/chapters/chapters.tscn[res://src/beginning/chapters/chapters.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Chapter# [.node-type.type-control]#MarginContainer#
** [.node-name.type-control]#Placeholder# [.node-type.type-control]#TextureRect#
** [.node-name.type-2d]#Sprite2D# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$.:[#_focus_entered_#]=>$.
```gdscript
func _on_focus_entered() -> void:
	if focus_animation_skip: focus_animation_skip = false
	else: %AnimationPlayer.play("focused")
```


=== Animations
==== Animation_ue4pb

[plantuml]
....
control "Root" as R
participant "$Sprite2D" as T0



== Time: 0.0 ==
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : rotation\n = 0.0
R  ->  T0 : position\n = Vector2(77, 72)
R  ->o  R : focus_mode\n = 2
R  ->  T0 : skew\n = 0.0


....
---

==== focused

[plantuml]
....
control "Root" as R
participant "$Sprite2D" as T0



== Time: 0.0 ==
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : rotation\n = 0.523599
== Time: 0.2 ==
R  ->  T0 : scale\n = Vector2(1.2, 1.2)
R  ->  T0 : rotation\n = -0.349066
== Time: 0.5 ==
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : rotation\n = 0.0


....
---

==== opening

[plantuml]
....
control "Root" as R
participant "$Sprite2D" as T0



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(77, -50)
R  ->o  R : focus_mode\n = 0
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(77, 72)
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : rotation\n = 0.0
R  ->o  R : focus_mode\n = 2


....
---

==== selected

[plantuml]
....
control "Root" as R
participant "$Sprite2D" as T0



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(77, 72)
R  ->  T0 : rotation\n = 0.0
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : skew\n = 0.0
== Time: 0.233333 ==
R  ->  T0 : scale\n = Vector2(-0.2, 2)
== Time: 0.234984 ==
R  ->  T0 : skew\n = -0.349066
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(1000, 420)
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : skew\n = 0.0


....
---

==== unselected

[plantuml]
....
control "Root" as R
participant "$Sprite2D" as T0



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(1000, 420)
R  ->  T0 : rotation\n = 0.0
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : skew\n = 0.0
== Time: 0.10168 ==
R  ->  T0 : scale\n = Vector2(0, 2)
R  ->  T0 : skew\n = 0.349066
== Time: 0.3 ==
R  ->  T0 : scale\n = Vector2(1, 1)
R  ->  T0 : skew\n = 0.0
== Time: 0.4 ==
R  ->  T0 : position\n = Vector2(77, 72)


....
---



=== Properties
.Root properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_right* |`0.083`
|_node_ |*anchor_bottom* |`0.148`
|_node_ |*offset_right* |`0.639984`
|_node_ |*offset_bottom* |`0.160004`
|_node_ |*focus_mode* |`2`
|_node_ |*theme_override_constants/margin_left* |`20`
|_node_ |*theme_override_constants/margin_top* |`20`
|_node_ |*theme_override_constants/margin_right* |`20`
|_node_ |*theme_override_constants/margin_bottom* |`20`
|_node_ |*script* |`ExtResource("1_v6bqu")`
|===
.$Placeholder properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*custom_minimum_size* |`Vector2(120, 0)`
|_node_ |*layout_mode* |`2`
|===
.$Sprite2D properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_node_ |*z_index* |`4`
|_node_ |*z_as_relative* |`false`
|_node_ |*texture_filter* |`2`
|_node_ |*position* |`Vector2(77, 72)`
|_node_ |*texture* |`ExtResource("1_ix5pl")`
|===
.$AnimationPlayer properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*libraries* |`{
&"": SubResource("AnimationLibrary_rglud")
}`
|===


=== link:/scripts/src/beginning/chapters/chapter/chapter.gd[chapter.gd]

```gdscript
extends MarginContainer

@export var play_opening := false : set = set_play_opening
@export var resource : ChapterResource
var focus_animation_skip := false


func set_play_opening(val: bool) -> void:
	if val: %AnimationPlayer.play("opening")


func focus_returned() -> void:
	focus_animation_skip = true
	grab_focus()
	focus_animation_skip = false


func selected() -> void:
	%AnimationPlayer.play('selected')


func unselected() -> void:
	%AnimationPlayer.play('unselected')


func _on_focus_entered() -> void:
	if focus_animation_skip: focus_animation_skip = false
	else: %AnimationPlayer.play("focused")

```


