---
title: src/stages/0/gimmicks/dash_lecture/dash_lecture.tscn
---
:toc:

== src / stages / 0 / gimmicks / dash_lecture / dash_lecture.tscn

=== Diagram
[plantuml]
....
class R as "DashLecture" <<(N,lightskyblue) Node2D>> {
  ~ finished
---
  * state
  * player
---
  + start()
  + _input()
  + _on_start_area_2d_area_entered()
  + _on_animation_player_animation_finished()
}
class N1 as "Crow" <<(S,lightskyblue) Sprite2D>> {
---
  + idle()
  + caw()
  + peck()
  + take_off()
  + fly()
  + play()
}
class N2 as "StartArea2D" <<(A,lightskyblue) Area2D>> {
}
class N3 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N4 as "Tooltip" <<(N,lightgreen) NinePatchRect>> {
}
class N5 as "RichTextLabel" <<(N,darkgray) Node>> {
}
class N6 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
R --o N2
R --o N4
R --o N6
N2 --o N3
N4 --o N5
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_start_area_2d_area_entered, N2::area_entered)
_(R::_on_animation_player_animation_finished, N6::animation_finished)
....




=== Overridden virtual functions
==== _input
```gdscript
func _input(event: InputEvent) -> void:
	if not state == State.AWAIT_INPUT: return
	if event.is_action_pressed(&'move_dash'):
		player.unlock()
		player.dash(Vector2(1, -1))
		%AnimationPlayer.play(&'finish')
```


=== Instantiators
* link:/scenes/src/chapters/0/stages/0/stage_0.tscn[res://src/chapters/0/stages/0/stage_0.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#DashLecture# [.node-type.type-2d]#Node2D#
** [.node-name.type-2d]#Crow# [.node-type.type-2d]#link:/scenes/src/stages/0/gimmicks/crow/crow.tscn[res://src/stages/0/gimmicks/crow/crow.tscn]#
** [.node-name.type-2d]#StartArea2D# [.node-type.type-2d]#Area2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-control]#Tooltip# [.node-type.type-control]#link:/scenes/src/stages/0/gimmicks/tooltip/tooltip.tscn[res://src/stages/0/gimmicks/tooltip/tooltip.tscn]#
*** [.node-name.type-plain]#RichTextLabel# [.node-type.type-plain]#Node#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$StartArea2D:[#_area_entered_#]=>$.
```gdscript
func _on_start_area_2d_area_entered(area: Area2D) -> void:
	if not state == State.READY: return
	player = area.owner
	start()
```
[.signal-connection]
.$AnimationPlayer:[#_animation_finished_#]=>$.
```gdscript
func _on_animation_player_animation_finished(anim_name: StringName) -> void:
	match anim_name:
		&'finish':
			finished.emit()
			call_deferred(&'queue_free')
```


=== Animations
==== Animation_hidjn

[plantuml]
....
control "Root" as R
participant "$Crow" as T0 #87CEFA
participant "$Tooltip" as T3 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(1893, -76.999985)
R  ->o  R : state\n = 0
R  ->o  T0 : flip_h\n = true
R  ->o  T3 : visible\n = false


....
---

==== finish

[plantuml]
....
control "Root" as R
participant "$Tooltip" as T1 #90EE90
participant "$Crow" as T2 #87CEFA



== Time: 0.0 ==
R  ->o  T1 : visible\n = false
R  ->  T2 : position\n = Vector2(1113, 500)
R  ->o  T2 : flip_h\n = false
== Time: 0.3 ==
R  ->o  T2 : &"fly"()
== Time: 0.96666664 ==
R  ->  T2 : position\n = Vector2(1112, 404.00003)
== Time: 1.0333333 ==
R  ->o  T2 : &"fly"()
== Time: 1.1333333 ==
R  ->  T2 : position\n = Vector2(1132, 408)
== Time: 4.0 ==
R  ->o  R : state\n = 3
R  ->  T2 : position\n = Vector2(2513.0002, -214)


....
---

==== start

[plantuml]
....
control "Root" as R
participant "$Crow" as T0 #87CEFA
participant "$Tooltip" as T4 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(1893, -76.999985)
R  ->o  R : state\n = 1
R  ->o  T0 : &"caw"()
R  ->o  T0 : flip_h\n = true
R  ->o  T4 : visible\n = false
== Time: 2.0 ==
R  ->  T0 : position\n = Vector2(1113, 492)
R  ->o  T0 : &"caw"()
R  ->o  T0 : flip_h\n = false
== Time: 3.0 ==
R  ->o  T0 : &"caw"()
== Time: 5.0 ==
R  ->o  T0 : &"caw"()
== Time: 5.2 ==
R  ->o  T4 : visible\n = true
== Time: 5.5 ==
R  ->o  R : state\n = 2


....
---



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*script* a|link:/scripts/src/stages/0/gimmicks/dash_lecture/dash_lecture.gd[res://src/stages/0/gimmicks/dash_lecture/dash_lecture.gd]
|===
[.node-property.node-2d]
.#$Crow# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(1893, -76.999985)`
|*flip_h* a|`true`
|===
[.node-property.node-2d]
.#$StartArea2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* a|`0`
|*collision_mask* a|`16`
|===
[.node-property.node-2d]
.#$StartArea2D/CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(771.75, 832)`
|*shape* a|`SubResource("RectangleShape2D_32iru")`
|===
[.node-property.node-control]
.#$Tooltip# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* a|`false`
|*offset_left* a|`984.0`
|*offset_top* a|`273.0`
|*offset_right* a|`1223.0`
|*offset_bottom* a|`424.0`
|===
[.node-property.node-plain]
.#$Tooltip/RichTextLabel# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*text* a|`[color=skyblue]ダッシュ[/color]
[b]↗[/b] (X)`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*libraries* a|`{
&"": SubResource("AnimationLibrary_1qo5f")
}`
|===


=== link:/scripts/src/stages/0/gimmicks/dash_lecture/dash_lecture.gd[dash_lecture.gd]

```gdscript
extends Node2D

signal finished

enum State { READY, STARTED, AWAIT_INPUT, FINISHED }

@export var state : State = State.READY
var player : Player = null


func start() -> void:
	if player: player.lock()
	%AnimationPlayer.play(&'start')


func _input(event: InputEvent) -> void:
	if not state == State.AWAIT_INPUT: return
	if event.is_action_pressed(&'move_dash'):
		player.unlock()
		player.dash(Vector2(1, -1))
		%AnimationPlayer.play(&'finish')


func _on_start_area_2d_area_entered(area: Area2D) -> void:
	if not state == State.READY: return
	player = area.owner
	start()


func _on_animation_player_animation_finished(anim_name: StringName) -> void:
	match anim_name:
		&'finish':
			finished.emit()
			call_deferred(&'queue_free')

```


