---
title: Home
application_name: PlatformerCeleste
---

[.welcome-code]
```gdscript
▖  ▖  ▜            ▗        ▌   ▌      
▌▞▖▌█▌▐ ▛▘▛▌▛▛▌█▌  ▜▘▛▌  ▛▌▛▌▄▖▛▌▛▌▛▘  
▛ ▝▌▙▖▐▖▙▖▙▌▌▌▌▙▖  ▐▖▙▌  ▙▌▙▌  ▙▌▙▌▙▖▗ 
                         ▄▌            

Usage

$ rake  # Analyze your Godot project, generate AsciiDoc files, and start the server.
```


=== Stats
[options="header"]
|===
| | | Min | Mean | Max | All

.1+| *Scenes* +
35 _files_

| *Child Nodes*
| link:/scenes/autoloads/current/current.tscn[0 _nodes_]
| 8.8 _nodes_
| link:/scenes/src/account/account.tscn[73 _nodes_]
| 308 _nodes_



.2+| *Scripts* +
37 _files_

| *Functions*
| link:/scripts/resources/account_stage_resource.gd[0 _funcs_]
| 5.7 _funcs_
| link:/scripts/src/beginning/chapters/menu/menu.gd[20 _funcs_]
| 209 _funcs_
| *Lines / Func*
| link:/scripts/autoloads/preference/preference.gd[1 _lines_]
| 23.7 _lines_
| link:/scripts/src/player/player.gd[39 _lines_]
| 874 _lines_



.1+| *Resources* +
13 _files_

| *Properties*
| link:/resources/data/test/account/empty_account.tres[6 _props_]
| 31.0 _props_
| link:/resources/data/test/account/full_account.tres[165 _props_]
| 402 _props_



.1+| *Asset Images* +
75 _files_

| *Content Length*
| link:/assets/assets/images/particles/circle_blur.png[296.0 B ]
| 22.55 KB 
| link:/assets/assets/world/Panorama.png[711.88 KB ]
| 1.65 MB 


|===


=== Main Scene
* link:/scenes/src/beginning/screen/screen.tscn[res://src/beginning/screen/screen.tscn]


=== Autoloads
[cols="1,3" options="header"]
|===
|Name |Path
|_Preference_ |link:/scripts/autoloads/preference/preference.gd[res://autoloads/preference/preference.gd]
|_BGM_ |link:/scenes/autoloads/bgm/bgm.tscn[res://autoloads/bgm/bgm.tscn]
|_KeyboardHandler_ |link:/scenes/autoloads/keyboard_handler/keyboard_handler.tscn[res://autoloads/keyboard_handler/keyboard_handler.tscn]
|_Current_ |link:/scenes/autoloads/current/current.tscn[res://autoloads/current/current.tscn]
|_Panku_ |link:/scenes/addons/panku_console/console.tscn[res://addons/panku_console/console.tscn]
|===


=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_application_ |*config/name* |`PlatformerCeleste`
|_application_ |*run/main_scene* |`res://src/beginning/screen/screen.tscn`
|_application_ |*config/features* |`PackedStringArray("4.5", "Forward Plus")`
|_application_ |*config/icon* |`res://icon.svg`
|_autoload_ |*Preference* |`*res://autoloads/preference/preference.gd`
|_autoload_ |*BGM* |`*res://autoloads/bgm/bgm.tscn`
|_autoload_ |*KeyboardHandler* |`*res://autoloads/keyboard_handler/keyboard_handler.tscn`
|_autoload_ |*Current* |`*res://autoloads/current/current.tscn`
|_autoload_ |*Panku* |`*res://addons/panku_console/console.tscn`
|_debug_ |*gdscript/warnings/integer_division* |`0`
|_display_ |*window/size/viewport_width* |`1920`
|_display_ |*window/size/viewport_height* |`1080`
|_display_ |*window/stretch/mode* |`viewport`
|_editor_plugins_ |*enabled* |`PackedStringArray("res://addons/gdscript_input_field/plugin.cfg", "res://addons/gut/plugin.cfg", "res://addons/panku_console/plugin.cfg")`
|_input_ |*ui_accept* |`{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194309,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":4194310,"physical_keycode":0,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":32,"physical_keycode":0,"key_label":0,"unicode":32,"location":0,"echo":false,"script":null)
, Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":0,"pressure":0.0,"pressed":true,"script":null)
]
}`
|_input_ |*toggle_console* |`{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194343,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}`
|_input_ |*move_jump* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":0,"pressure":0.0,"pressed":true,"script":null)
]
}`
|_input_ |*move_dash* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":2,"pressure":0.0,"pressed":true,"script":null)
]
}`
|_input_ |*move_left* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadMotion,"resource_local_to_scene":false,"resource_name":"","device":-1,"axis":0,"axis_value":-1.0,"script":null)
]
}`
|_input_ |*move_right* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadMotion,"resource_local_to_scene":false,"resource_name":"","device":-1,"axis":0,"axis_value":1.0,"script":null)
]
}`
|_input_ |*move_up* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadMotion,"resource_local_to_scene":false,"resource_name":"","device":-1,"axis":1,"axis_value":-1.0,"script":null)
]
}`
|_input_ |*move_down* |`{
"deadzone": 0.5,
"events": [Object(InputEventJoypadMotion,"resource_local_to_scene":false,"resource_name":"","device":-1,"axis":1,"axis_value":1.0,"script":null)
]
}`
|_input_ |*ui_back* |`{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194305,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
, Object(InputEventJoypadButton,"resource_local_to_scene":false,"resource_name":"","device":-1,"button_index":1,"pressure":0.0,"pressed":true,"script":null)
]
}`
|_input_ |*toggle_fullscreen* |`{
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194342,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
, Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":true,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":4194309,"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)
]
}`
|_layer_names_ |*2d_physics/layer_1* |`Basic`
|_layer_names_ |*2d_physics/layer_2* |`Player`
|_layer_names_ |*2d_physics/layer_3* |`Camera`
|_layer_names_ |*2d_physics/layer_4* |`Failure`
|_rendering_ |*textures/canvas_textures/default_texture_filter* |`0`
|===


