---
title: src/stages/gimmicks/falling_ice_block/falling_ice_block.tscn
---
:toc:

== src / stages / gimmicks / falling_ice_block / falling_ice_block.tscn

=== Diagram
[plantuml]
....
class ROOT as "FallingIceBlock" <<(R,lightskyblue) RigidBody2D>> {
---
  + _ready()
  + fall()
  + _on_detection_area_2d_body_entered()
}
class Sprite2D as "Sprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class CollisionShape2D as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class FailureCollision as "FailureCollision" <<(A,lightskyblue) Area2D>> {
}
class FailureCollision_CollisionShape2D as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class DetectionArea2D as "DetectionArea2D" <<(A,lightskyblue) Area2D>> {
}
class DetectionArea2D_CollisionShape2D as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class AnimationPlayer as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
ROOT --o Sprite2D
ROOT --o CollisionShape2D
ROOT --o FailureCollision
ROOT --o DetectionArea2D
ROOT --o AnimationPlayer
FailureCollision --o FailureCollision_CollisionShape2D
DetectionArea2D --o DetectionArea2D_CollisionShape2D
left to right direction
ROOT::_on_detection_area_2d_body_entered <-[#blue,thickness=2]- DetectionArea2D::body_entered
....


=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	freeze = true
```


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#FallingIceBlock# [.node-type.type-2d]#RigidBody2D#
** [.node-name.type-2d]#Sprite2D# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#FailureCollision# [.node-type.type-2d]#Area2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#DetectionArea2D# [.node-type.type-2d]#Area2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#




=== Signal Connections
[cols="1,1,1,2" options="header"]
|===
|From |Name |To |Method
|_DetectionArea2D_ |*body_entered* |_._ |`_on_detection_area_2d_body_entered`
|===


=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*size* |`Vector2(363, 68)`
|_sub_resource_ |*size* |`Vector2(350, 801)`
|_node_ |*script* |`ExtResource("2_snubb")`
|_node_ |*scale* |`Vector2(8, 8)`
|_node_ |*texture* |`ExtResource("1_snubb")`
|_node_ |*position* |`Vector2(-1.5, 2)`
|_node_ |*shape* |`SubResource("RectangleShape2D_snubb")`
|_node_ |*collision_layer* |`8`
|_node_ |*collision_mask* |`8`
|_node_ |*position* |`Vector2(4, 78)`
|_node_ |*shape* |`SubResource("RectangleShape2D_snubb")`
|_node_ |*collision_mask* |`2`
|_node_ |*position* |`Vector2(0, 316.5)`
|_node_ |*shape* |`SubResource("RectangleShape2D_51pa1")`
|_node_ |*debug_color* |`Color(0.89528626, 0.7040168, 0.559312, 0.41960785)`
|===


=== link:/scripts/src/stages/gimmicks/falling_ice_block/falling_ice_block.gd[falling_ice_block.gd]

```gdscript
extends RigidBody2D


func _ready() -> void:
	freeze = true


func fall() -> void:
	freeze = false


func _on_detection_area_2d_body_entered(body: Node2D) -> void:
	fall.call_deferred()

```


