---
title: src/stages/frame/camera_frame.tscn
---
:toc:

== src / stages / frame / camera_frame.tscn

=== Diagram
[plantuml]
....
class R as "CameraFrame" <<(A,lightskyblue) Area2D>> {
  - HALF_SIZE
---
  + corner()
}
class N1 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
R --o N1
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....





=== Instantiators
* link:/scenes/src/chapters/0/stages/0/stage_0.tscn[res://src/chapters/0/stages/0/stage_0.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#CameraFrame# [.node-type.type-2d]#Area2D#
** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*size* |`Vector2(1920, 1080)`
|_node_ |*collision_layer* |`4`
|_node_ |*collision_mask* |`4`
|_node_ |*script* |`ExtResource("1_1tugu")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*shape* |`SubResource("RectangleShape2D_jyj6x")`
|_node_ |*debug_color* |`Color(1, 0.23921569, 0.5372549, 0.03529412)`
|===


=== link:/scripts/src/stages/frame/camera_frame.gd[camera_frame.gd]

```gdscript
extends Area2D

const HALF_SIZE = Vector2(1920, 1080) / 2


func corner() -> Dictionary:
	return {
		"left":   global_position.x - HALF_SIZE.x,
		"right":  global_position.x + HALF_SIZE.x,
		"top":    global_position.y - HALF_SIZE.y,
		"bottom": global_position.y + HALF_SIZE.y,
	}

```


