---
title: src/stages/frame/camera_frame.tscn
---
:toc:

== src / stages / frame / camera_frame.tscn

=== Diagram
[plantuml]
....
class R as "CameraFrame" <<(A,lightskyblue) Area2D>> {
  - HALF_SIZE
---
  + corner_of()
  + corner()
}
class N1 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
R --o N1
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....






=== Instantiators
* link:/scenes/debug/stages/basic/basic.tscn[res://debug/stages/basic/basic.tscn]
* link:/scenes/src/chapters/0/stages/0/stage_0.tscn[res://src/chapters/0/stages/0/stage_0.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#CameraFrame# [.node-type.type-2d]#Area2D#
** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* a|`4`
|*collision_mask* a|`4`
|*script* a|link:/scripts/src/stages/frame/camera_frame.gd[res://src/stages/frame/camera_frame.gd]
|===
[.node-property.node-2d]
.#$CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*shape* a|`SubResource("RectangleShape2D_jyj6x")`
|*debug_color* a|`Color(1, 0.23921569, 0.5372549, 0.03529412)`
|===


=== link:/scripts/src/stages/frame/camera_frame.gd[camera_frame.gd]

```gdscript
extends Area2D

const HALF_SIZE = Vector2(1920, 1080) / 2


static func corner_of(area: Area2D) -> Dictionary:
	return {
		"left":   area.global_position.x - HALF_SIZE.x,
		"right":  area.global_position.x + HALF_SIZE.x,
		"top":    area.global_position.y - HALF_SIZE.y,
		"bottom": area.global_position.y + HALF_SIZE.y,
	}


func corner() -> Dictionary:
	return corner_of(self)

```


