---
title: src/beginning/menu/menu.tscn
---
:toc:

== src / beginning / menu / menu.tscn

=== Diagram
[plantuml]
....
class R as "Menu" <<(C,#90EE90) Control>> {
  * current_plate
  * grab_focus_root
---
  + _ready()
  + set_grab_focus_root()
  + change_plate()
  + _on_climb_button_focus_entered()
  + _on_climb_button_focus_exited()
  + _on_climb_button_pressed()
  + _on_quit_button_pressed()
  + _on_accounts_ui_backed()
  + _on_accounts_get_started()
  + _on_chapters_ui_backed()
  + _on_chapters_focused()
  + _on_chapters_selected()
}
class N1 as "SubViewportContainer" <<(S,#90EE90) SubViewportContainer>> {
}
class N2 as "Snow" <<(N,#87CEFA) Node2D>> {
}
class N3 as "SubViewport" <<(S,#FFFF00) SubViewport>> {
}
class N4 as "World" <<(N,#FF69B4) Node3D>> {
  * CameraNode
---
  + back_to_circular_move()
  + focus_chapter()
  + zoom_chapter()
  + initialize_animation_camera_key()
  + smooth_rotation()
  + acute_angle()
  + _on_animation_player_animation_finished()
}
class N5 as "RootContainer" <<(M,#90EE90) MarginContainer>> {
}
class N6 as "MenuContainer" <<(V,#90EE90) VBoxContainer>> {
}
class N7 as "ClimbContainer" <<(N,#87CEFA) Node2D>> {
}
class N8 as "LogoContainer" <<(C,#90EE90) CenterContainer>> {
}
class N9 as "Sprite2D" <<(S,#87CEFA) Sprite2D>> {
}
class N10 as "ButtonContainer" <<(B,#90EE90) BoxContainer>> {
}
class N11 as "ClimbButton" <<(B,#90EE90) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N12 as "OthersContainer" <<(N,#87CEFA) Node2D>> {
}
class N13 as "VBoxContainer" <<(V,#90EE90) VBoxContainer>> {
}
class N14 as "OptionsContainer" <<(B,#90EE90) BoxContainer>> {
}
class N15 as "OptionsButton" <<(B,#90EE90) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N16 as "CreditsContainer" <<(B,#90EE90) BoxContainer>> {
}
class N17 as "CreditsButton" <<(B,#90EE90) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N18 as "QuitContainer" <<(B,#90EE90) BoxContainer>> {
}
class N19 as "QuitButton" <<(B,#90EE90) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N20 as "Accounts" <<(M,#90EE90) MarginContainer>> {
  ~ ui_backed
  ~ get_started
---
  * grab_focus_first
  * focus_returned
  * current_idx
---
  + _ready()
  + load_accounts()
  + set_grab_focus_first()
  + set_focus_returned()
  + _on_account_1_selected()
  + _on_account_1_unselected()
  + _on_account_2_selected()
  + _on_account_2_unselected()
  + _on_account_3_selected()
  + _on_account_3_unselected()
  + _on_account_ui_backed()
  + _on_account_get_started()
  + _on_account_focus_entered()
}
class N21 as "Chapters" <<(C,#90EE90) Control>> {
  ~ focused
  ~ selected
  ~ ui_backed
---
  - ICON_OFFSET
  - INITIAL_CHAPTERS_X
  * grab_focus_first
  * play_opening
  * current_plate
  * shown
  * focused_chapter_idx
  * selected_chapter_idx
---
  + _ready()
  + setup_from_account_resource()
  + _input()
  + go_back()
  + go_foward()
  + set_grab_focus_first()
  + set_play_opening()
  + focus_pin_to()
  + zoom_pin_to()
  + force_focus_return()
  + load_focused_chapter_to_menu()
  + get_chapter()
  + set_chapters_animation_offset()
  + _on_chapater_focused()
  + _on_animation_player_animation_finished()
  + _on_selected()
  + _on_menu_ui_backed()
}
class N22 as "AnimationPlayer" <<(A,#FFFF00) AnimationPlayer>> {
}
R --o N1
R --o N5
R --o N20
R --o N21
R --o N22
N1 --o N2
N1 --o N3
N3 --o N4
N5 --o N6
N6 --o N7
N6 --o N12
N7 --o N8
N7 --o N10
N8 --o N9
N10 --o N11
N12 --o N13
N13 --o N14
N13 --o N16
N13 --o N18
N14 --o N15
N16 --o N17
N18 --o N19
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_climb_button_focus_entered, N11::focus_entered)
_(R::_on_climb_button_focus_exited, N11::focus_exited)
_(R::_on_climb_button_pressed, N11::pressed)
_(R::_on_quit_button_pressed, N19::pressed)
_(R::_on_accounts_get_started, N20::get_started)
_(R::_on_accounts_ui_backed, N20::ui_backed)
_(R::_on_chapters_focused, N21::focused)
_(R::_on_chapters_selected, N21::selected)
_(R::_on_chapters_ui_backed, N21::ui_backed)
....


=== Assets
[.scene-assets]
.res://assets/images/ui/Credits.svg
[link=/assets/assets/images/ui/Credits.svg] 
image::/assets/raw/assets/images/ui/Credits.svg[200, 100] 

[.scene-assets]
.res://assets/images/ui/Quit.svg
[link=/assets/assets/images/ui/Quit.svg] 
image::/assets/raw/assets/images/ui/Quit.svg[200, 100] 



=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	%ClimbButton.grab_focus()
	FocusHelper.set_neighbors_v([
		%ClimbButton, %OptionsButton, %CreditsButton, %QuitButton])
```
.$Accounts
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		grab_focus_first = true
	else:
		load_accounts()
```
.$Chapters
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('opening')
	FocusHelper.set_neighbors_h(%ChaptersContainer.get_children())
	for chapter in %ChaptersContainer.get_children():
		chapter.focus_entered.connect(_on_chapater_focused.bind(chapter))
	load_focused_chapter_to_menu()
```
==== _process
.$RootContainer/MenuContainer/ClimbContainer/ButtonContainer/ClimbButton, $RootContainer/MenuContainer/OthersContainer/VBoxContainer/OptionsContainer/OptionsButton, $RootContainer/MenuContainer/OthersContainer/VBoxContainer/CreditsContainer/CreditsButton, $RootContainer/MenuContainer/OthersContainer/VBoxContainer/QuitContainer/QuitButton
```gdscript
func _process(delta: float) -> void:
	if not focused: return
	blink_time += delta
	add_theme_color_override("font_focus_color", get_focus_color())
	if blink_time > BLINK_INTERVAL: blink_time = 0
```
==== _input
.$Chapters
```gdscript
func _input(event: InputEvent) -> void:
	if not (shown && current_plate == Plate.ROOT): return
	if event.is_action_pressed("ui_back"):
		go_back()
	elif event.is_action_pressed("ui_accept"):
		go_foward()
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Menu# [.node-type.type-control]#Control#
** [.node-name.type-control]#SubViewportContainer# [.node-type.type-control]#SubViewportContainer#
*** [.node-name.type-2d]#Snow# [.node-type.type-2d]#link:/scenes/src/world/snow/snow.tscn[res://src/world/snow/snow.tscn]#
*** [.node-name.type-other]#SubViewport# [.node-type.type-other]#SubViewport#
**** [.node-name.type-3d]#World# [.node-type.type-3d]#link:/scenes/src/world/world.tscn[res://src/world/world.tscn]#
** [.node-name.type-control]#RootContainer# [.node-type.type-control]#MarginContainer#
*** [.node-name.type-control]#MenuContainer# [.node-type.type-control]#VBoxContainer#
**** [.node-name.type-2d]#ClimbContainer# [.node-type.type-2d]#Node2D#
***** [.node-name.type-control]#LogoContainer# [.node-type.type-control]#CenterContainer#
****** [.node-name.type-2d]#Sprite2D# [.node-type.type-2d]#Sprite2D#
***** [.node-name.type-control]#ButtonContainer# [.node-type.type-control]#BoxContainer#
****** [.node-name.type-control]#ClimbButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
**** [.node-name.type-2d]#OthersContainer# [.node-type.type-2d]#Node2D#
***** [.node-name.type-control]#VBoxContainer# [.node-type.type-control]#VBoxContainer#
****** [.node-name.type-control]#OptionsContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#OptionsButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
****** [.node-name.type-control]#CreditsContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#CreditsButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
****** [.node-name.type-control]#QuitContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#QuitButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
** [.node-name.type-control]#Accounts# [.node-type.type-control]#link:/scenes/src/beginning/accounts/accounts.tscn[res://src/beginning/accounts/accounts.tscn]#
** [.node-name.type-control]#Chapters# [.node-type.type-control]#link:/scenes/src/beginning/chapters/chapters.tscn[res://src/beginning/chapters/chapters.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$RootContainer/MenuContainer/ClimbContainer/ButtonContainer/ClimbButton:[#_focus_entered_#]=>$.
```gdscript
func _on_climb_button_focus_entered() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_focused')
```
[.signal-connection]
.$RootContainer/MenuContainer/ClimbContainer/ButtonContainer/ClimbButton:[#_focus_exited_#]=>$.
```gdscript
func _on_climb_button_focus_exited() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_unfocused')
```
[.signal-connection]
.$RootContainer/MenuContainer/ClimbContainer/ButtonContainer/ClimbButton:[#_pressed_#]=>$.
```gdscript
func _on_climb_button_pressed() -> void:
	if current_plate == Plate.ROOT:
		Input.start_joy_vibration(0, 0.4, 0.6, 0.2)
		%AnimationPlayer.play('climb_selected')
```
[.signal-connection]
.$RootContainer/MenuContainer/OthersContainer/VBoxContainer/QuitContainer/QuitButton:[#_pressed_#]=>$.
```gdscript
func _on_quit_button_pressed() -> void:
	get_tree().quit()
```
[.signal-connection]
.$Accounts:[#_get_started_#]=>$.
```gdscript
func _on_accounts_get_started(account: Account) -> void:
	%Chapters.setup_from_account_resource()
	%AnimationPlayer.play("chapters_show")
```
[.signal-connection]
.$Accounts:[#_ui_backed_#]=>$.
```gdscript
func _on_accounts_ui_backed() -> void:
	if current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('climb_unselected')
```
[.signal-connection]
.$Chapters:[#_focused_#]=>$.
```gdscript
func _on_chapters_focused(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.focus_chapter(idx)
```
[.signal-connection]
.$Chapters:[#_selected_#]=>$.
```gdscript
func _on_chapters_selected(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.zoom_chapter(idx)
```
[.signal-connection]
.$Chapters:[#_ui_backed_#]=>$.
```gdscript
func _on_chapters_ui_backed() -> void:
	if current_plate == Plate.CHAPTERS || current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('chapters_hide')
		%World.back_to_circular_move()
```


=== Animations
==== Animation_f84do

[plantuml]
....
control "Root" as R
participant "$RootContainer" as T0 #90EE90
participant "$RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T1 #87CEFA
participant "$Accounts" as T2 #90EE90
participant "$RootContainer\n/MenuContainer\n/OthersContainer" as T3 #87CEFA
participant "$RootContainer\n/MenuContainer\n/ClimbContainer" as T4 #87CEFA
participant "$Chapters" as T10 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(0, 0)
R  ->  T2 : position\n = Vector2(1920, 0)
R  ->  T3 : position\n = Vector2(10, 400)
R  ->  T4 : position\n = Vector2(0, 0)
R  ->o  T2 : grab_focus_first\n = false
R  ->o  R : current_plate\n = 0
R  ->o  R : grab_focus_root\n = false
R  ->  T1 : rotation\n = 0.0
R  ->  T1 : offset\n = Vector2(10, 140)
R  ->  T10 : position\n = Vector2(1920, 0)
R  ->o  T10 : play_opening\n = false
R  ->o  T10 : grab_focus_first\n = false
R  ->o  T2 : focus_returned\n = false


....
---

==== chapters_hide

[plantuml]
....
control "Root" as R
participant "$Accounts" as T0 #90EE90
participant "$Chapters" as T1 #90EE90
participant "$RootContainer\n/MenuContainer\n/ClimbContainer" as T2 #87CEFA
participant "$RootContainer\n/MenuContainer\n/OthersContainer" as T3 #87CEFA



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(-1920, 1080)
R  ->  T1 : position\n = Vector2(0, 0)
R  ->  T2 : position\n = Vector2(-1000, 0)
R  ->  T3 : position\n = Vector2(-1000, 400)
== Time: 0.166667 ==
R  ->o  T0 : focus_returned\n = true
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(1920, 0)
== Time: 1.0 ==
R  ->  T1 : position\n = Vector2(1920, 0)
R  ->o  R : current_plate\n = 2


....
---

==== chapters_show

[plantuml]
....
control "Root" as R
participant "$Accounts" as T0 #90EE90
participant "$Chapters" as T1 #90EE90
participant "$RootContainer\n/MenuContainer\n/ClimbContainer" as T5 #87CEFA
participant "$RootContainer\n/MenuContainer\n/OthersContainer" as T6 #87CEFA



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(0, 0)
R  ->o  T1 : play_opening\n = true
R  ->o  T0 : grab_focus_first\n = false
R  ->  T5 : position\n = Vector2(-1000, 0)
R  ->  T6 : position\n = Vector2(-1000, 400)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(-1920, 1080)
R  ->o  R : current_plate\n = 3
== Time: 0.7 ==
R  ->o  T1 : grab_focus_first\n = true


....
---

==== climb_focused

[plantuml]
....
control "Root" as R
participant "$RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T0 #87CEFA
participant "$Chapters" as T1 #90EE90
participant "$Accounts" as T2 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(1920, 0)
R  ->  T2 : position\n = Vector2(1920, 0)
== Time: 0.1 ==
R  ->  T0 : position\n = Vector2(0, 5)
== Time: 0.2 ==
R  ->  T0 : position\n = Vector2(0, -10)
== Time: 1.0 ==
R  ->  T0 : position\n = Vector2(0, -5)


....
---

==== climb_selected

[plantuml]
....
control "Root" as R
participant "$Accounts" as T0 #90EE90
participant "$RootContainer\n/MenuContainer\n/OthersContainer" as T1 #87CEFA
participant "$RootContainer\n/MenuContainer\n/ClimbContainer" as T2 #87CEFA
participant "$RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T5 #87CEFA
participant "$Chapters" as T7 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(1920, 0)
R  ->  T1 : position\n = Vector2(10, 400)
R  ->  T2 : position\n = Vector2(0, 0)
R  ->o  T0 : grab_focus_first\n = false
R  ->o  R : current_plate\n = 1
R  ->  T5 : rotation\n = 0.0
R  ->  T5 : offset\n = Vector2(10, 140)
R  ->  T7 : position\n = Vector2(1920, 0)
== Time: 0.05 ==
R  ->  T5 : rotation\n = -0.349066
R  ->  T5 : offset\n = Vector2(-80, 60)
== Time: 0.15 ==
R  ->  T5 : rotation\n = 0.0349066
R  ->  T5 : offset\n = Vector2(40, 110)
== Time: 0.25 ==
R  ->  T5 : rotation\n = 0.20944
R  ->  T5 : offset\n = Vector2(70, 110)
== Time: 0.35 ==
R  ->  T5 : rotation\n = -0.174533
R  ->  T5 : offset\n = Vector2(-40, 120)
== Time: 0.7 ==
R  ->  T0 : position\n = Vector2(1920, 0)
R  ->  T1 : position\n = Vector2(-1000, 400)
R  ->  T2 : position\n = Vector2(0, 0)
R  ->o  R : current_plate\n = 2
R  ->  T5 : rotation\n = 0.0
R  ->  T5 : offset\n = Vector2(10, 140)
== Time: 1.5 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T2 : position\n = Vector2(-1000, 0)
R  ->o  T0 : grab_focus_first\n = true


....
---

==== climb_unfocused

[plantuml]
....
control "Root" as R
participant "$RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T0 #87CEFA



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, -5)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 0)


....
---

==== climb_unselected

[plantuml]
....
control "Root" as R
participant "$Accounts" as T0 #90EE90
participant "$RootContainer\n/MenuContainer\n/OthersContainer" as T1 #87CEFA
participant "$RootContainer\n/MenuContainer\n/ClimbContainer" as T2 #87CEFA
participant "$Chapters" as T6 #90EE90



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(-1000, 400)
R  ->  T2 : position\n = Vector2(-1000, 0)
R  ->o  T0 : grab_focus_first\n = true
R  ->o  R : current_plate\n = 2
R  ->o  R : grab_focus_root\n = false
R  ->  T6 : position\n = Vector2(1920, 0)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(1920, 0)
R  ->  T2 : position\n = Vector2(0, 0)
R  ->o  R : current_plate\n = 1
== Time: 0.55 ==
R  ->o  T0 : grab_focus_first\n = false
R  ->o  R : grab_focus_root\n = true
== Time: 1.0 ==
R  ->  T0 : position\n = Vector2(1920, 0)
R  ->  T1 : position\n = Vector2(10, 400)
R  ->  T2 : position\n = Vector2(0, 0)


....
---

==== opening (autoplay)

[plantuml]
....
control "Root" as R
participant "$RootContainer" as T0 #90EE90
participant "$RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T1 #87CEFA
participant "$Accounts" as T2 #90EE90
participant "$Chapters" as T5 #90EE90



== Time: 0.0 ==
R  ->  T1 : position\n = Vector2(0, -5)
R  ->  T2 : position\n = Vector2(1920, 0)
R  ->o  R : current_plate\n = 0
R  ->o  T5 : play_opening\n = false
R  ->o  T2 : grab_focus_first\n = false
R  ->o  T5 : grab_focus_first\n = false
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(-800, 0)
== Time: 0.966667 ==
R  ->  T0 : position\n = Vector2(0, 0)
== Time: 1.0 ==
R  ->o  R : current_plate\n = 1
R  ->o  R : grab_focus_root\n = true


....
---



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`3`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme* |`ExtResource("1_w62bb")`
|*script* |`ExtResource("2_7v8tq")`
|===
[.node-property.node-control]
.#$SubViewportContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`1`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*focus_mode* |`0`
|===
[.node-property.node-other]
.#$SubViewportContainer/SubViewport# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*handle_input_locally* |`false`
|*gui_disable_input* |`true`
|*size* |`Vector2i(1920, 1080)`
|*render_target_update_mode* |`4`
|===
[.node-property.node-3d]
.#$SubViewportContainer/SubViewport/World# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|===
[.node-property.node-control]
.#$RootContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`1`
|*anchors_preset* |`9`
|*anchor_bottom* |`1.0`
|*offset_right* |`663.0`
|*offset_bottom* |`30.0`
|*grow_vertical* |`2`
|*theme_override_constants/margin_left* |`180`
|*theme_override_constants/margin_top* |`120`
|*theme_override_constants/margin_bottom* |`100`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/ClimbContainer/LogoContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*custom_minimum_size* |`Vector2(0, 240)`
|*offset_left* |`170.0`
|*offset_right* |`170.0`
|*offset_bottom* |`240.0`
|*size_flags_horizontal* |`4`
|===
[.node-property.node-2d]
.#$RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture_filter* |`2`
|*texture* |`ExtResource("5_wprcb")`
|*offset* |`Vector2(10, 140)`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/ClimbContainer/ButtonContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*offset_top* |`244.0`
|*offset_right* |`340.0`
|*offset_bottom* |`389.0`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/ClimbContainer/ButtonContainer/ClimbButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*focus_neighbor_left* |`NodePath(".")`
|*focus_neighbor_top* |`NodePath(".")`
|*focus_neighbor_right* |`NodePath(".")`
|*focus_neighbor_bottom* |`NodePath("../../../OthersContainer/VBoxContainer/OptionsContainer/OptionsButton")`
|*theme_override_font_sizes/font_size* |`100`
|*text* |` CLIMB`
|*icon* |`null`
|*focus_move_direction* |`1`
|===
[.node-property.node-2d]
.#$RootContainer/MenuContainer/OthersContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(10, 400)`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*offset_right* |`483.0`
|*offset_bottom* |`281.0`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/OptionsContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/OptionsContainer/OptionsButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*focus_neighbor_top* |`NodePath("../../../../ClimbContainer/ButtonContainer/ClimbButton")`
|*focus_neighbor_bottom* |`NodePath("../../CreditsContainer/CreditsButton")`
|*text* |` Options`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/CreditsContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/CreditsContainer/CreditsButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*focus_neighbor_top* |`NodePath("../../OptionsContainer/OptionsButton")`
|*focus_neighbor_bottom* |`NodePath("../../QuitContainer/QuitButton")`
|*text* |` Credits`
|*icon* |`ExtResource("7_tps4m")`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/QuitContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
[.node-property.node-control]
.#$RootContainer/MenuContainer/OthersContainer/VBoxContainer/QuitContainer/QuitButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*focus_neighbor_top* |`NodePath("../../CreditsContainer/CreditsButton")`
|*text* |` Quit`
|*icon* |`ExtResource("8_lywrx")`
|===
[.node-property.node-control]
.#$Accounts# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*offset_left* |`1920.0`
|*offset_right* |`1920.0`
|===
[.node-property.node-control]
.#$Chapters# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*offset_left* |`1920.0`
|*offset_right* |`1920.0`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*libraries* |`{
&"": SubResource("AnimationLibrary_dft0i")
}`
|*autoplay* |`opening`
|===


=== link:/scripts/src/beginning/menu/menu.gd[menu.gd]

```gdscript
extends Control

enum Plate { OPENING, ROOT, ACCOUNTS, CHAPTERS }
@export var current_plate : Plate = Plate.OPENING : set = change_plate
@export var grab_focus_root : bool = false : set = set_grab_focus_root


func _ready() -> void:
	%ClimbButton.grab_focus()
	FocusHelper.set_neighbors_v([
		%ClimbButton, %OptionsButton, %CreditsButton, %QuitButton])


func set_grab_focus_root(val: bool) -> void:
	if val: %ClimbButton.grab_focus()


func change_plate(val: Plate) -> void:
	current_plate = val


func _on_climb_button_focus_entered() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_focused')


func _on_climb_button_focus_exited() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_unfocused')


func _on_climb_button_pressed() -> void:
	if current_plate == Plate.ROOT:
		Input.start_joy_vibration(0, 0.4, 0.6, 0.2)
		%AnimationPlayer.play('climb_selected')


func _on_quit_button_pressed() -> void:
	get_tree().quit()


func _on_accounts_ui_backed() -> void:
	if current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('climb_unselected')


func _on_accounts_get_started(account: Account) -> void:
	%Chapters.setup_from_account_resource()
	%AnimationPlayer.play("chapters_show")


func _on_chapters_ui_backed() -> void:
	if current_plate == Plate.CHAPTERS || current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('chapters_hide')
		%World.back_to_circular_move()


func _on_chapters_focused(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.focus_chapter(idx)


func _on_chapters_selected(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.zoom_chapter(idx)

```


