---
title: src/beginning/menu/menu.tscn
---
:toc:

== src / beginning / menu / menu.tscn

=== Diagram
[plantuml]
....
class ROOT as "Menu" <<(C,lightgreen) Control>> {
  * current_plate
  * grab_focus_root
---
  + _ready()
  + set_grab_focus_root()
  + change_plate()
  + _on_climb_button_focus_entered()
  + _on_climb_button_focus_exited()
  + _on_climb_button_pressed()
  + _on_quit_button_pressed()
  + _on_accounts_ui_backed()
  + _on_accounts_get_started()
  + _on_chapters_ui_backed()
  + _on_chapters_focused()
  + _on_chapters_selected()
}
class SubViewportContainer as "SubViewportContainer" <<(S,lightgreen) SubViewportContainer>> {
}
class SubViewportContainer_Snow as "Snow" <<(N,lightskyblue) Node2D>> {
}
class SubViewportContainer_SubViewport as "SubViewport" <<(S,darkgray) SubViewport>> {
}
class SubViewportContainer_SubViewport_World as "World" <<(N,hotpink) Node3D>> {
  * CameraNode
---
  + back_to_circular_move()
  + focus_chapter()
  + zoom_chapter()
  + initialize_animation_camera_key()
  + smooth_rotation()
  + acute_angle()
  + _on_animation_player_animation_finished()
}
class RootContainer as "RootContainer" <<(M,lightgreen) MarginContainer>> {
}
class RootContainer_MenuContainer as "MenuContainer" <<(V,lightgreen) VBoxContainer>> {
}
class RootContainer_MenuContainer_ClimbContainer as "ClimbContainer" <<(N,lightskyblue) Node2D>> {
}
class RootContainer_MenuContainer_ClimbContainer_LogoContainer as "LogoContainer" <<(C,lightgreen) CenterContainer>> {
}
class RootContainer_MenuContainer_ClimbContainer_LogoContainer_Sprite2D as "Sprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class RootContainer_MenuContainer_ClimbContainer_ButtonContainer as "ButtonContainer" <<(B,lightgreen) BoxContainer>> {
}
class RootContainer_MenuContainer_ClimbContainer_ButtonContainer_ClimbButton as "ClimbButton" <<(B,lightgreen) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class RootContainer_MenuContainer_OthersContainer as "OthersContainer" <<(N,lightskyblue) Node2D>> {
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer as "VBoxContainer" <<(V,lightgreen) VBoxContainer>> {
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_OptionsContainer as "OptionsContainer" <<(B,lightgreen) BoxContainer>> {
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_OptionsContainer_OptionsButton as "OptionsButton" <<(B,lightgreen) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_CreditsContainer as "CreditsContainer" <<(B,lightgreen) BoxContainer>> {
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_CreditsContainer_CreditsButton as "CreditsButton" <<(B,lightgreen) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer as "QuitContainer" <<(B,lightgreen) BoxContainer>> {
}
class RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer_QuitButton as "QuitButton" <<(B,lightgreen) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class Accounts as "Accounts" <<(M,lightgreen) MarginContainer>> {
  ~ ui_backed
  ~ get_started
---
  * grab_focus_first
  * focus_returned
  * current_idx
---
  + _ready()
  + load_accounts()
  + set_grab_focus_first()
  + set_focus_returned()
  + _on_account_1_selected()
  + _on_account_1_unselected()
  + _on_account_2_selected()
  + _on_account_2_unselected()
  + _on_account_3_selected()
  + _on_account_3_unselected()
  + _on_account_ui_backed()
  + _on_account_get_started()
  + _on_account_focus_entered()
}
class Chapters as "Chapters" <<(C,lightgreen) Control>> {
  ~ focused
  ~ selected
  ~ ui_backed
---
  - ICON_OFFSET
  - INITIAL_CHAPTERS_X
  * grab_focus_first
  * play_opening
  * current_plate
  * shown
  * focused_chapter_idx
  * selected_chapter_idx
---
  + _ready()
  + setup_from_account_resource()
  + _input()
  + go_back()
  + go_foward()
  + set_grab_focus_first()
  + set_play_opening()
  + focus_pin_to()
  + zoom_pin_to()
  + force_focus_return()
  + load_focused_chapter_to_menu()
  + get_chapter()
  + set_chapters_animation_offset()
  + _on_chapater_focused()
  + _on_animation_player_animation_finished()
  + _on_selected()
  + _on_menu_ui_backed()
}
class AnimationPlayer as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
ROOT --o SubViewportContainer
ROOT --o RootContainer
ROOT --o Accounts
ROOT --o Chapters
ROOT --o AnimationPlayer
SubViewportContainer --o SubViewportContainer_Snow
SubViewportContainer --o SubViewportContainer_SubViewport
SubViewportContainer_SubViewport --o SubViewportContainer_SubViewport_World
RootContainer --o RootContainer_MenuContainer
RootContainer_MenuContainer --o RootContainer_MenuContainer_ClimbContainer
RootContainer_MenuContainer --o RootContainer_MenuContainer_OthersContainer
RootContainer_MenuContainer_ClimbContainer --o RootContainer_MenuContainer_ClimbContainer_LogoContainer
RootContainer_MenuContainer_ClimbContainer --o RootContainer_MenuContainer_ClimbContainer_ButtonContainer
RootContainer_MenuContainer_ClimbContainer_LogoContainer --o RootContainer_MenuContainer_ClimbContainer_LogoContainer_Sprite2D
RootContainer_MenuContainer_ClimbContainer_ButtonContainer --o RootContainer_MenuContainer_ClimbContainer_ButtonContainer_ClimbButton
RootContainer_MenuContainer_OthersContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer
RootContainer_MenuContainer_OthersContainer_VBoxContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_OptionsContainer
RootContainer_MenuContainer_OthersContainer_VBoxContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_CreditsContainer
RootContainer_MenuContainer_OthersContainer_VBoxContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer
RootContainer_MenuContainer_OthersContainer_VBoxContainer_OptionsContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_OptionsContainer_OptionsButton
RootContainer_MenuContainer_OthersContainer_VBoxContainer_CreditsContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_CreditsContainer_CreditsButton
RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer --o RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer_QuitButton
left to right direction
ROOT::_on_climb_button_focus_entered <-[#blue,thickness=2]- RootContainer_MenuContainer_ClimbContainer_ButtonContainer_ClimbButton::focus_entered
ROOT::_on_climb_button_focus_exited <-[#blue,thickness=2]- RootContainer_MenuContainer_ClimbContainer_ButtonContainer_ClimbButton::focus_exited
ROOT::_on_climb_button_pressed <-[#blue,thickness=2]- RootContainer_MenuContainer_ClimbContainer_ButtonContainer_ClimbButton::pressed
ROOT::_on_quit_button_pressed <-[#blue,thickness=2]- RootContainer_MenuContainer_OthersContainer_VBoxContainer_QuitContainer_QuitButton::pressed
ROOT::_on_accounts_get_started <-[#blue,thickness=2]- Accounts::get_started
ROOT::_on_accounts_ui_backed <-[#blue,thickness=2]- Accounts::ui_backed
ROOT::_on_chapters_focused <-[#blue,thickness=2]- Chapters::focused
ROOT::_on_chapters_selected <-[#blue,thickness=2]- Chapters::selected
ROOT::_on_chapters_ui_backed <-[#blue,thickness=2]- Chapters::ui_backed
....


=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	%ClimbButton.grab_focus()
	FocusHelper.set_neighbors_v([
		%ClimbButton, %OptionsButton, %CreditsButton, %QuitButton])
```


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Menu# [.node-type.type-control]#Control#
** [.node-name.type-control]#SubViewportContainer# [.node-type.type-control]#SubViewportContainer#
*** [.node-name.type-2d]#Snow# [.node-type.type-2d]#link:/scenes/src/world/snow/snow.tscn[res://src/world/snow/snow.tscn]#
*** [.node-name.type-other]#SubViewport# [.node-type.type-other]#SubViewport#
**** [.node-name.type-3d]#World# [.node-type.type-3d]#link:/scenes/src/world/world.tscn[res://src/world/world.tscn]#
** [.node-name.type-control]#RootContainer# [.node-type.type-control]#MarginContainer#
*** [.node-name.type-control]#MenuContainer# [.node-type.type-control]#VBoxContainer#
**** [.node-name.type-2d]#ClimbContainer# [.node-type.type-2d]#Node2D#
***** [.node-name.type-control]#LogoContainer# [.node-type.type-control]#CenterContainer#
****** [.node-name.type-2d]#Sprite2D# [.node-type.type-2d]#Sprite2D#
***** [.node-name.type-control]#ButtonContainer# [.node-type.type-control]#BoxContainer#
****** [.node-name.type-control]#ClimbButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
**** [.node-name.type-2d]#OthersContainer# [.node-type.type-2d]#Node2D#
***** [.node-name.type-control]#VBoxContainer# [.node-type.type-control]#VBoxContainer#
****** [.node-name.type-control]#OptionsContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#OptionsButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
****** [.node-name.type-control]#CreditsContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#CreditsButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
****** [.node-name.type-control]#QuitContainer# [.node-type.type-control]#BoxContainer#
******* [.node-name.type-control]#QuitButton# [.node-type.type-control]#link:/scenes/src/ui/button/button.tscn[res://src/ui/button/button.tscn]#
** [.node-name.type-control]#Accounts# [.node-type.type-control]#link:/scenes/src/beginning/accounts/accounts.tscn[res://src/beginning/accounts/accounts.tscn]#
** [.node-name.type-control]#Chapters# [.node-type.type-control]#link:/scenes/src/beginning/chapters/chapters.tscn[res://src/beginning/chapters/chapters.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Animations
==== Animation_f84do

[plantuml]
....
control "Root" as Root
participant "RootContainer" as T0
participant "RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T1
participant "Accounts" as T2
participant "RootContainer\n/MenuContainer\n/OthersContainer" as T3
participant "RootContainer\n/MenuContainer\n/ClimbContainer" as T4
participant "Chapters" as T10



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(0, 0)
Root  ->  T2 : position\n = Vector2(1920, 0)
Root  ->  T3 : position\n = Vector2(10, 400)
Root  ->  T4 : position\n = Vector2(0, 0)
Root  ->o  T2 : grab_focus_first\n = false
Root  ->o  Root : current_plate\n = 0
Root  ->o  Root : grab_focus_root\n = false
Root  ->  T1 : rotation\n = 0.0
Root  ->  T1 : offset\n = Vector2(10, 140)
Root  ->  T10 : position\n = Vector2(1920, 0)
Root  ->o  T10 : play_opening\n = false
Root  ->o  T10 : grab_focus_first\n = false
Root  ->o  T2 : focus_returned\n = false


....
---

==== chapters_hide

[plantuml]
....
control "Root" as Root
participant "Accounts" as T0
participant "Chapters" as T1
participant "RootContainer\n/MenuContainer\n/ClimbContainer" as T2
participant "RootContainer\n/MenuContainer\n/OthersContainer" as T3



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(-1920, 1080)
Root  ->  T1 : position\n = Vector2(0, 0)
Root  ->  T2 : position\n = Vector2(-1000, 0)
Root  ->  T3 : position\n = Vector2(-1000, 400)
== Time: 0.166667 ==
Root  ->o  T0 : focus_returned\n = true
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(1920, 0)
== Time: 1.0 ==
Root  ->  T1 : position\n = Vector2(1920, 0)
Root  ->o  Root : current_plate\n = 2


....
---

==== chapters_show

[plantuml]
....
control "Root" as Root
participant "Accounts" as T0
participant "Chapters" as T1
participant "RootContainer\n/MenuContainer\n/ClimbContainer" as T5
participant "RootContainer\n/MenuContainer\n/OthersContainer" as T6



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(0, 0)
Root  ->o  T1 : play_opening\n = true
Root  ->o  T0 : grab_focus_first\n = false
Root  ->  T5 : position\n = Vector2(-1000, 0)
Root  ->  T6 : position\n = Vector2(-1000, 400)
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(-1920, 1080)
Root  ->o  Root : current_plate\n = 3
== Time: 0.7 ==
Root  ->o  T1 : grab_focus_first\n = true


....
---

==== climb_focused

[plantuml]
....
control "Root" as Root
participant "RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T0
participant "Chapters" as T1
participant "Accounts" as T2



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(1920, 0)
Root  ->  T2 : position\n = Vector2(1920, 0)
== Time: 0.1 ==
Root  ->  T0 : position\n = Vector2(0, 5)
== Time: 0.2 ==
Root  ->  T0 : position\n = Vector2(0, -10)
== Time: 1.0 ==
Root  ->  T0 : position\n = Vector2(0, -5)


....
---

==== climb_selected

[plantuml]
....
control "Root" as Root
participant "Accounts" as T0
participant "RootContainer\n/MenuContainer\n/OthersContainer" as T1
participant "RootContainer\n/MenuContainer\n/ClimbContainer" as T2
participant "RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T5
participant "Chapters" as T7



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(1920, 0)
Root  ->  T1 : position\n = Vector2(10, 400)
Root  ->  T2 : position\n = Vector2(0, 0)
Root  ->o  T0 : grab_focus_first\n = false
Root  ->o  Root : current_plate\n = 1
Root  ->  T5 : rotation\n = 0.0
Root  ->  T5 : offset\n = Vector2(10, 140)
Root  ->  T7 : position\n = Vector2(1920, 0)
== Time: 0.05 ==
Root  ->  T5 : rotation\n = -0.349066
Root  ->  T5 : offset\n = Vector2(-80, 60)
== Time: 0.15 ==
Root  ->  T5 : rotation\n = 0.0349066
Root  ->  T5 : offset\n = Vector2(40, 110)
== Time: 0.25 ==
Root  ->  T5 : rotation\n = 0.20944
Root  ->  T5 : offset\n = Vector2(70, 110)
== Time: 0.35 ==
Root  ->  T5 : rotation\n = -0.174533
Root  ->  T5 : offset\n = Vector2(-40, 120)
== Time: 0.7 ==
Root  ->  T0 : position\n = Vector2(1920, 0)
Root  ->  T1 : position\n = Vector2(-1000, 400)
Root  ->  T2 : position\n = Vector2(0, 0)
Root  ->o  Root : current_plate\n = 2
Root  ->  T5 : rotation\n = 0.0
Root  ->  T5 : offset\n = Vector2(10, 140)
== Time: 1.5 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T2 : position\n = Vector2(-1000, 0)
Root  ->o  T0 : grab_focus_first\n = true


....
---

==== climb_unfocused

[plantuml]
....
control "Root" as Root
participant "RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T0



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, -5)
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(0, 0)


....
---

==== climb_unselected

[plantuml]
....
control "Root" as Root
participant "Accounts" as T0
participant "RootContainer\n/MenuContainer\n/OthersContainer" as T1
participant "RootContainer\n/MenuContainer\n/ClimbContainer" as T2
participant "Chapters" as T6



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(-1000, 400)
Root  ->  T2 : position\n = Vector2(-1000, 0)
Root  ->o  T0 : grab_focus_first\n = true
Root  ->o  Root : current_plate\n = 2
Root  ->o  Root : grab_focus_root\n = false
Root  ->  T6 : position\n = Vector2(1920, 0)
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(1920, 0)
Root  ->  T2 : position\n = Vector2(0, 0)
Root  ->o  Root : current_plate\n = 1
== Time: 0.55 ==
Root  ->o  T0 : grab_focus_first\n = false
Root  ->o  Root : grab_focus_root\n = true
== Time: 1.0 ==
Root  ->  T0 : position\n = Vector2(1920, 0)
Root  ->  T1 : position\n = Vector2(10, 400)
Root  ->  T2 : position\n = Vector2(0, 0)


....
---

==== opening

[plantuml]
....
control "Root" as Root
participant "RootContainer" as T0
participant "RootContainer\n/MenuContainer\n/ClimbContainer\n/LogoContainer\n/Sprite2D" as T1
participant "Accounts" as T2
participant "Chapters" as T5



== Time: 0.0 ==
Root  ->  T1 : position\n = Vector2(0, -5)
Root  ->  T2 : position\n = Vector2(1920, 0)
Root  ->o  Root : current_plate\n = 0
Root  ->o  T5 : play_opening\n = false
Root  ->o  T2 : grab_focus_first\n = false
Root  ->o  T5 : grab_focus_first\n = false
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(-800, 0)
== Time: 0.966667 ==
Root  ->  T0 : position\n = Vector2(0, 0)
== Time: 1.0 ==
Root  ->o  Root : current_plate\n = 1
Root  ->o  Root : grab_focus_root\n = true


....
---



=== Signal Connections
[cols="1,1,1,2" options="header"]
|===
|From |Name |To |Method
|_RootContainer / MenuContainer / ClimbContainer / ButtonContainer / ClimbButton_ |*focus_entered* |_._ |`_on_climb_button_focus_entered`
|_RootContainer / MenuContainer / ClimbContainer / ButtonContainer / ClimbButton_ |*focus_exited* |_._ |`_on_climb_button_focus_exited`
|_RootContainer / MenuContainer / ClimbContainer / ButtonContainer / ClimbButton_ |*pressed* |_._ |`_on_climb_button_pressed`
|_RootContainer / MenuContainer / OthersContainer / VBoxContainer / QuitContainer / QuitButton_ |*pressed* |_._ |`_on_quit_button_pressed`
|_Accounts_ |*get_started* |_._ |`_on_accounts_get_started`
|_Accounts_ |*ui_backed* |_._ |`_on_accounts_ui_backed`
|_Chapters_ |*focused* |_._ |`_on_chapters_focused`
|_Chapters_ |*selected* |_._ |`_on_chapters_selected`
|_Chapters_ |*ui_backed* |_._ |`_on_chapters_ui_backed`
|===


=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*length* |`0.001`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("RootContainer:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("RootContainer/MenuContainer/OthersContainer:position")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(10, 400)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer:position")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("Accounts:grab_focus_first")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [0]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath(".:grab_focus_root")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/8/type* |`value`
|_sub_resource_ |*tracks/8/imported* |`false`
|_sub_resource_ |*tracks/8/enabled* |`true`
|_sub_resource_ |*tracks/8/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:rotation")`
|_sub_resource_ |*tracks/8/interp* |`1`
|_sub_resource_ |*tracks/8/loop_wrap* |`true`
|_sub_resource_ |*tracks/8/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [0.0]
}`
|_sub_resource_ |*tracks/9/type* |`value`
|_sub_resource_ |*tracks/9/imported* |`false`
|_sub_resource_ |*tracks/9/enabled* |`true`
|_sub_resource_ |*tracks/9/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:offset")`
|_sub_resource_ |*tracks/9/interp* |`1`
|_sub_resource_ |*tracks/9/loop_wrap* |`true`
|_sub_resource_ |*tracks/9/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(10, 140)]
}`
|_sub_resource_ |*tracks/10/type* |`value`
|_sub_resource_ |*tracks/10/imported* |`false`
|_sub_resource_ |*tracks/10/enabled* |`true`
|_sub_resource_ |*tracks/10/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/10/interp* |`1`
|_sub_resource_ |*tracks/10/loop_wrap* |`true`
|_sub_resource_ |*tracks/10/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/11/type* |`value`
|_sub_resource_ |*tracks/11/imported* |`false`
|_sub_resource_ |*tracks/11/enabled* |`true`
|_sub_resource_ |*tracks/11/path* |`NodePath("Chapters:play_opening")`
|_sub_resource_ |*tracks/11/interp* |`1`
|_sub_resource_ |*tracks/11/loop_wrap* |`true`
|_sub_resource_ |*tracks/11/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/12/type* |`value`
|_sub_resource_ |*tracks/12/imported* |`false`
|_sub_resource_ |*tracks/12/enabled* |`true`
|_sub_resource_ |*tracks/12/path* |`NodePath("Chapters:grab_focus_first")`
|_sub_resource_ |*tracks/12/interp* |`1`
|_sub_resource_ |*tracks/12/loop_wrap* |`true`
|_sub_resource_ |*tracks/12/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/13/type* |`value`
|_sub_resource_ |*tracks/13/imported* |`false`
|_sub_resource_ |*tracks/13/enabled* |`true`
|_sub_resource_ |*tracks/13/path* |`NodePath("Accounts:focus_returned")`
|_sub_resource_ |*tracks/13/interp* |`1`
|_sub_resource_ |*tracks/13/loop_wrap* |`true`
|_sub_resource_ |*tracks/13/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*resource_name* |`chapters_hide`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(-1920, 1080), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0, 0.5, 1),
"transitions": PackedFloat32Array(0.5, 1, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(1920, 0), Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(-1000, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("RootContainer/MenuContainer/OthersContainer:position")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(-1000, 400)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(1),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [2]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("Accounts:focus_returned")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0.166667),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*resource_name* |`chapters_show`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(-1920, 1080)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("Chapters:play_opening")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Chapters:grab_focus_first")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0.7),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath("Accounts:grab_focus_first")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer:position")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(-1000, 0)]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("RootContainer/MenuContainer/OthersContainer:position")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(-1000, 400)]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0.5),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [3]
}`
|_sub_resource_ |*resource_name* |`climb_focused`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.1, 0.2, 1),
"transitions": PackedFloat32Array(3, 3, 1, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(0, 5), Vector2(0, -10), Vector2(0, -5)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*resource_name* |`climb_selected`
|_sub_resource_ |*length* |`1.5`
|_sub_resource_ |*step* |`0.05`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.7, 1.5),
"transitions": PackedFloat32Array(1, 0.25, 1),
"update": 0,
"values": [Vector2(1920, 0), Vector2(1920, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("RootContainer/MenuContainer/OthersContainer:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0, 0.7),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(10, 400), Vector2(-1000, 400)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0, 0.7, 1.5),
"transitions": PackedFloat32Array(1, 0.5, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(0, 0), Vector2(-1000, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Accounts:grab_focus_first")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0, 1.5),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [false, true]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0, 0.7),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [1, 2]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:rotation")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0, 0.05, 0.15, 0.25, 0.35, 0.7),
"transitions": PackedFloat32Array(0.25, 0.25, 0.5, 0.5, 0.75, 1),
"update": 0,
"values": [0.0, -0.349066, 0.0349066, 0.20944, -0.174533, 0.0]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:offset")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0, 0.05, 0.15, 0.25, 0.35, 0.7),
"transitions": PackedFloat32Array(0.25, 0.25, 0.5, 0.5, 0.75, 1),
"update": 0,
"values": [Vector2(10, 140), Vector2(-80, 60), Vector2(40, 110), Vector2(70, 110), Vector2(-40, 120), Vector2(10, 140)]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*resource_name* |`climb_unfocused`
|_sub_resource_ |*length* |`0.5`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(1, 3),
"update": 0,
"values": [Vector2(0, -5), Vector2(0, 0)]
}`
|_sub_resource_ |*resource_name* |`climb_unselected`
|_sub_resource_ |*step* |`0.05`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5, 1),
"transitions": PackedFloat32Array(0.25, 1, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(1920, 0), Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("RootContainer/MenuContainer/OthersContainer:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0, 1),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(-1000, 400), Vector2(10, 400)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0, 0.5, 1),
"transitions": PackedFloat32Array(0.25, 1, 1),
"update": 0,
"values": [Vector2(-1000, 0), Vector2(0, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Accounts:grab_focus_first")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0, 0.55),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [true, false]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [2, 1]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath(".:grab_focus_root")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0, 0.55),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [false, true]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("Chapters:position")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*resource_name* |`opening`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("RootContainer:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0.5, 0.966667),
"transitions": PackedFloat32Array(4.75682, 1),
"update": 0,
"values": [Vector2(-800, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("RootContainer/MenuContainer/ClimbContainer/LogoContainer/Sprite2D:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, -5)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("Accounts:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath(".:current_plate")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0, 1),
"transitions": PackedFloat32Array(1, 1),
"update": 1,
"values": [0, 1]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:grab_focus_root")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(1),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("Chapters:play_opening")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("Accounts:grab_focus_first")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath("Chapters:grab_focus_first")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*_data* |`{
&"RESET": SubResource("Animation_f84do"),
&"chapters_hide": SubResource("Animation_na2l5"),
&"chapters_show": SubResource("Animation_ttv6y"),
&"climb_focused": SubResource("Animation_enmrk"),
&"climb_selected": SubResource("Animation_8dqyp"),
&"climb_unfocused": SubResource("Animation_hjluo"),
&"climb_unselected": SubResource("Animation_swgws"),
&"opening": SubResource("Animation_65t62")
}`
|_node_ |*layout_mode* |`3`
|_node_ |*anchors_preset* |`15`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*theme* |`ExtResource("1_w62bb")`
|_node_ |*script* |`ExtResource("2_7v8tq")`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`15`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*focus_mode* |`0`
|_node_ |*handle_input_locally* |`false`
|_node_ |*gui_disable_input* |`true`
|_node_ |*size* |`Vector2i(1920, 1080)`
|_node_ |*render_target_update_mode* |`4`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`9`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*offset_right* |`663.0`
|_node_ |*offset_bottom* |`30.0`
|_node_ |*grow_vertical* |`2`
|_node_ |*theme_override_constants/margin_left* |`180`
|_node_ |*theme_override_constants/margin_top* |`120`
|_node_ |*theme_override_constants/margin_bottom* |`100`
|_node_ |*layout_mode* |`2`
|_node_ |*custom_minimum_size* |`Vector2(0, 240)`
|_node_ |*offset_left* |`170.0`
|_node_ |*offset_right* |`170.0`
|_node_ |*offset_bottom* |`240.0`
|_node_ |*size_flags_horizontal* |`4`
|_node_ |*texture_filter* |`2`
|_node_ |*texture* |`ExtResource("5_wprcb")`
|_node_ |*offset* |`Vector2(10, 140)`
|_node_ |*offset_top* |`244.0`
|_node_ |*offset_right* |`340.0`
|_node_ |*offset_bottom* |`389.0`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*focus_neighbor_left* |`NodePath(".")`
|_node_ |*focus_neighbor_top* |`NodePath(".")`
|_node_ |*focus_neighbor_right* |`NodePath(".")`
|_node_ |*focus_neighbor_bottom* |`NodePath("../../../OthersContainer/VBoxContainer/OptionsContainer/OptionsButton")`
|_node_ |*theme_override_font_sizes/font_size* |`100`
|_node_ |*text* |` CLIMB`
|_node_ |*icon* |`null`
|_node_ |*focus_move_direction* |`1`
|_node_ |*position* |`Vector2(10, 400)`
|_node_ |*offset_right* |`483.0`
|_node_ |*offset_bottom* |`281.0`
|_node_ |*layout_mode* |`2`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*focus_neighbor_top* |`NodePath("../../../../ClimbContainer/ButtonContainer/ClimbButton")`
|_node_ |*focus_neighbor_bottom* |`NodePath("../../CreditsContainer/CreditsButton")`
|_node_ |*text* |` Options`
|_node_ |*layout_mode* |`2`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*focus_neighbor_top* |`NodePath("../../OptionsContainer/OptionsButton")`
|_node_ |*focus_neighbor_bottom* |`NodePath("../../QuitContainer/QuitButton")`
|_node_ |*text* |` Credits`
|_node_ |*icon* |`ExtResource("7_tps4m")`
|_node_ |*layout_mode* |`2`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*focus_neighbor_top* |`NodePath("../../CreditsContainer/CreditsButton")`
|_node_ |*text* |` Quit`
|_node_ |*icon* |`ExtResource("8_lywrx")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*offset_left* |`1920.0`
|_node_ |*offset_right* |`1920.0`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*offset_left* |`1920.0`
|_node_ |*offset_right* |`1920.0`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*libraries* |`{
&"": SubResource("AnimationLibrary_dft0i")
}`
|_node_ |*autoplay* |`opening`
|===


=== link:/scripts/src/beginning/menu/menu.gd[menu.gd]

```gdscript
extends Control

enum Plate { OPENING, ROOT, ACCOUNTS, CHAPTERS }
@export var current_plate : Plate = Plate.OPENING : set = change_plate
@export var grab_focus_root : bool = false : set = set_grab_focus_root


func _ready() -> void:
	%ClimbButton.grab_focus()
	FocusHelper.set_neighbors_v([
		%ClimbButton, %OptionsButton, %CreditsButton, %QuitButton])


func set_grab_focus_root(val: bool) -> void:
	if val: %ClimbButton.grab_focus()


func change_plate(val: Plate) -> void:
	current_plate = val


func _on_climb_button_focus_entered() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_focused')


func _on_climb_button_focus_exited() -> void:
	if current_plate == Plate.ROOT:
		%AnimationPlayer.play('climb_unfocused')


func _on_climb_button_pressed() -> void:
	if current_plate == Plate.ROOT:
		Input.start_joy_vibration(0, 0.4, 0.6, 0.2)
		%AnimationPlayer.play('climb_selected')


func _on_quit_button_pressed() -> void:
	get_tree().quit()


func _on_accounts_ui_backed() -> void:
	if current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('climb_unselected')


func _on_accounts_get_started(account: Account) -> void:
	%Chapters.setup_from_account_resource()
	%AnimationPlayer.play("chapters_show")


func _on_chapters_ui_backed() -> void:
	if current_plate == Plate.CHAPTERS || current_plate == Plate.ACCOUNTS:
		%AnimationPlayer.play('chapters_hide')
		%World.back_to_circular_move()


func _on_chapters_focused(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.focus_chapter(idx)


func _on_chapters_selected(idx: int) -> void:
	if current_plate == Plate.CHAPTERS:
		%World.zoom_chapter(idx)

```


