---
title: src/beginning/accounts/accounts.tscn
---
:toc:

== src / beginning / accounts / accounts.tscn

=== Diagram
[plantuml]
....
class R as "Accounts" <<(M,lightgreen) MarginContainer>> {
  ~ ui_backed
  ~ get_started
---
  * grab_focus_first
  * focus_returned
  * current_idx
---
  + _ready()
  + load_accounts()
  + set_grab_focus_first()
  + set_focus_returned()
  + _on_account_1_selected()
  + _on_account_1_unselected()
  + _on_account_2_selected()
  + _on_account_2_unselected()
  + _on_account_3_selected()
  + _on_account_3_unselected()
  + _on_account_ui_backed()
  + _on_account_get_started()
  + _on_account_focus_entered()
}
class N1 as "AccountsContainer" <<(N,lightskyblue) Node2D>> {
}
class N2 as "Account1" <<(B,lightgreen) BoxContainer>> {
  ~ ui_backed
  ~ selected
  ~ unselected
  ~ get_started
---
  - LABELS_IN_RESOURCE
  * resource
  * state
  * focus_top
  * focus_menu
---
  + _ready()
  + reset_summary_visiblity()
  + _input()
  + set_resource()
  + load_resource()
  + set_icon_visibility_on()
  + set_focus_top()
  + set_focus_menu()
  + is_focused()
  + is_unfocused()
  + is_selected()
  + _on_focus_entered()
  + _on_focus_exited()
  + _on_selected()
  + _on_unselected()
  + _on_get_started_button_pressed()
}
class N3 as "Account2" <<(B,lightgreen) BoxContainer>> {
  ~ ui_backed
  ~ selected
  ~ unselected
  ~ get_started
---
  - LABELS_IN_RESOURCE
  * resource
  * state
  * focus_top
  * focus_menu
---
  + _ready()
  + reset_summary_visiblity()
  + _input()
  + set_resource()
  + load_resource()
  + set_icon_visibility_on()
  + set_focus_top()
  + set_focus_menu()
  + is_focused()
  + is_unfocused()
  + is_selected()
  + _on_focus_entered()
  + _on_focus_exited()
  + _on_selected()
  + _on_unselected()
  + _on_get_started_button_pressed()
}
class N4 as "Account3" <<(B,lightgreen) BoxContainer>> {
  ~ ui_backed
  ~ selected
  ~ unselected
  ~ get_started
---
  - LABELS_IN_RESOURCE
  * resource
  * state
  * focus_top
  * focus_menu
---
  + _ready()
  + reset_summary_visiblity()
  + _input()
  + set_resource()
  + load_resource()
  + set_icon_visibility_on()
  + set_focus_top()
  + set_focus_menu()
  + is_focused()
  + is_unfocused()
  + is_selected()
  + _on_focus_entered()
  + _on_focus_exited()
  + _on_selected()
  + _on_unselected()
  + _on_get_started_button_pressed()
}
class N5 as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
R --o N1
R --o N5
N1 --o N2
N1 --o N3
N1 --o N4
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_account_get_started, N2::get_started)
_(R::_on_account_1_selected, N2::selected)
_(R::_on_account_ui_backed, N2::ui_backed)
_(R::_on_account_1_unselected, N2::unselected)
_(R::_on_account_focus_entered, N3::focus_entered)
_(R::_on_account_get_started, N3::get_started)
_(R::_on_account_2_selected, N3::selected)
_(R::_on_account_ui_backed, N3::ui_backed)
_(R::_on_account_2_unselected, N3::unselected)
_(R::_on_account_focus_entered, N4::focus_entered)
_(R::_on_account_get_started, N4::get_started)
_(R::_on_account_3_selected, N4::selected)
_(R::_on_account_ui_backed, N4::ui_backed)
_(R::_on_account_3_unselected, N4::unselected)
....


=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		grab_focus_first = true
	else:
		load_accounts()
```
.$AccountsContainer/Account1, $AccountsContainer/Account2, $AccountsContainer/Account3
```gdscript
func _ready() -> void:
	FocusHelper.set_neighbors_v(
		[%GetStartedButton, %ChangeNameButton, %AssistModeButton])
	reset_summary_visiblity()
	if resource: load_resource()
```
==== _input
.$AccountsContainer/Account1, $AccountsContainer/Account2, $AccountsContainer/Account3
```gdscript
func _input(event: InputEvent) -> void:
	if is_focused() && event.is_action_pressed("ui_accept"):
		selected.emit()
	elif event.is_action_pressed("ui_back"):
		if is_selected():  unselected.emit()
		elif is_focused(): ui_backed.emit()
```



=== Instantiators
* link:/scenes/src/beginning/menu/menu.tscn[res://src/beginning/menu/menu.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Accounts# [.node-type.type-control]#MarginContainer#
** [.node-name.type-2d]#AccountsContainer# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#Account1# [.node-type.type-control]#link:/scenes/src/account/account.tscn[res://src/account/account.tscn]#
*** [.node-name.type-control]#Account2# [.node-type.type-control]#link:/scenes/src/account/account.tscn[res://src/account/account.tscn]#
*** [.node-name.type-control]#Account3# [.node-type.type-control]#link:/scenes/src/account/account.tscn[res://src/account/account.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$AccountsContainer/Account1:[#_get_started_#]=>$., $AccountsContainer/Account2:[#_get_started_#]=>$., $AccountsContainer/Account3:[#_get_started_#]=>$.
```gdscript
func _on_account_get_started(number: int) -> void:
	var account = get_node('%Account' + str(number))
	Current.load_account(number)
	get_started.emit(account)
```
[.signal-connection]
.$AccountsContainer/Account1:[#_selected_#]=>$.
```gdscript
func _on_account_1_selected() -> void:
	%AnimationPlayer.play("1st_selected")
```
[.signal-connection]
.$AccountsContainer/Account1:[#_ui_backed_#]=>$., $AccountsContainer/Account2:[#_ui_backed_#]=>$., $AccountsContainer/Account3:[#_ui_backed_#]=>$.
```gdscript
func _on_account_ui_backed() -> void:
	%AnimationPlayer.play("RESET")
	ui_backed.emit()
```
[.signal-connection]
.$AccountsContainer/Account1:[#_unselected_#]=>$.
```gdscript
func _on_account_1_unselected() -> void:
	%AnimationPlayer.play("1st_unselected")
```
[.signal-connection]
.$AccountsContainer/Account2:[#_focus_entered_#]=>$., $AccountsContainer/Account3:[#_focus_entered_#]=>$.
```gdscript
func _on_account_focus_entered(idx: int) -> void:
	current_idx = idx
```
[.signal-connection]
.$AccountsContainer/Account2:[#_selected_#]=>$.
```gdscript
func _on_account_2_selected() -> void:
	%AnimationPlayer.play("2nd_selected")
```
[.signal-connection]
.$AccountsContainer/Account2:[#_unselected_#]=>$.
```gdscript
func _on_account_2_unselected() -> void:
	%AnimationPlayer.play("2nd_unselected")
```
[.signal-connection]
.$AccountsContainer/Account3:[#_selected_#]=>$.
```gdscript
func _on_account_3_selected() -> void:
	%AnimationPlayer.play("3rd_selected")
```
[.signal-connection]
.$AccountsContainer/Account3:[#_unselected_#]=>$.
```gdscript
func _on_account_3_unselected() -> void:
	%AnimationPlayer.play("3rd_unselected")
```


=== Animations
==== 1st_selected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 300)
R  ->  T1 : position\n = Vector2(0, 1200)
R  ->  T2 : position\n = Vector2(0, 1200)


....
---

==== 1st_unselected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 300)
R  ->  T1 : position\n = Vector2(0, 1200)
R  ->  T2 : position\n = Vector2(0, 1200)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)


....
---

==== 2nd_selected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, -800)
R  ->  T1 : position\n = Vector2(0, 300)
R  ->  T2 : position\n = Vector2(0, 1200)


....
---

==== 2nd_unselected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, -800)
R  ->  T1 : position\n = Vector2(0, 300)
R  ->  T2 : position\n = Vector2(0, 1200)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)


....
---

==== 3rd_selected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, -800)
R  ->  T1 : position\n = Vector2(0, -800)
R  ->  T2 : position\n = Vector2(0, 300)


....
---

==== 3rd_unselected

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, -800)
R  ->  T1 : position\n = Vector2(0, -800)
R  ->  T2 : position\n = Vector2(0, 300)
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)


....
---

==== Animation_l10c4

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)


....
---

==== opening

[plantuml]
....
control "Root" as R
participant "$AccountsContainer\n/Account1" as T0
participant "$AccountsContainer\n/Account2" as T1
participant "$AccountsContainer\n/Account3" as T2



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 50)
R  ->  T1 : position\n = Vector2(0, 356)
R  ->  T2 : position\n = Vector2(0, 656)


....
---



=== Properties
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme_override_constants/margin_top* |`90`
|*theme_override_constants/margin_bottom* |`90`
|*script* |`ExtResource("1_t5yqj")`
|===
.#$AccountsContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|===
.#$AccountsContainer/Account1# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*anchors_preset* |`0`
|*anchor_right* |`0.0`
|*offset_top* |`50.0`
|*offset_right* |`1920.0`
|*offset_bottom* |`342.0`
|*grow_horizontal* |`1`
|*size_flags_horizontal* |`3`
|*focus_neighbor_left* |`NodePath(".")`
|*focus_neighbor_top* |`NodePath(".")`
|*focus_neighbor_right* |`NodePath(".")`
|*focus_neighbor_bottom* |`NodePath("../Account2")`
|===
.#$AccountsContainer/Account2# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*anchors_preset* |`0`
|*anchor_right* |`0.0`
|*offset_top* |`356.0`
|*offset_right* |`1920.0`
|*offset_bottom* |`656.0`
|*grow_horizontal* |`1`
|*focus_neighbor_left* |`NodePath(".")`
|*focus_neighbor_top* |`NodePath("../Account1")`
|*focus_neighbor_right* |`NodePath(".")`
|*focus_neighbor_bottom* |`NodePath("../Account3")`
|*resource* |`null`
|===
.#$AccountsContainer/Account3# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*anchors_preset* |`0`
|*anchor_right* |`0.0`
|*offset_top* |`656.0`
|*offset_right* |`1920.0`
|*offset_bottom* |`964.0`
|*grow_horizontal* |`1`
|*focus_neighbor_left* |`NodePath(".")`
|*focus_neighbor_top* |`NodePath("../Account2")`
|*focus_neighbor_right* |`NodePath(".")`
|*focus_neighbor_bottom* |`NodePath(".")`
|*resource* |`null`
|===
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*libraries* |`{
&"": SubResource("AnimationLibrary_uv55d")
}`
|*autoplay* |`opening`
|===


=== link:/scripts/src/beginning/accounts/accounts.gd[accounts.gd]

```gdscript
extends MarginContainer

signal ui_backed
signal get_started(account: Account)

@export var grab_focus_first : bool : set = set_grab_focus_first
@export var focus_returned : bool : set = set_focus_returned
var current_idx : int = 0


func _ready() -> void:
	if get_parent() == get_tree().root:
		grab_focus_first = true
	else:
		load_accounts()


func load_accounts() -> void:
	for number in [1, 2, 3]:
		var account = AccountResource.find(number)
		var node = get_node('%Account'+str(number))
		node.resource = account
		node.load_resource()


func set_grab_focus_first(val: bool) -> void:
	FocusHelper.grab_first(%AccountsContainer, val)


func set_focus_returned(val: bool) -> void:
	if val:
		%AnimationPlayer.play("RESET")
		%AccountsContainer.get_child(current_idx).grab_focus()


func _on_account_1_selected() -> void:
	%AnimationPlayer.play("1st_selected")


func _on_account_1_unselected() -> void:
	%AnimationPlayer.play("1st_unselected")


func _on_account_2_selected() -> void:
	%AnimationPlayer.play("2nd_selected")


func _on_account_2_unselected() -> void:
	%AnimationPlayer.play("2nd_unselected")


func _on_account_3_selected() -> void:
	%AnimationPlayer.play("3rd_selected")


func _on_account_3_unselected() -> void:
	%AnimationPlayer.play("3rd_unselected")


func _on_account_ui_backed() -> void:
	%AnimationPlayer.play("RESET")
	ui_backed.emit()


func _on_account_get_started(number: int) -> void:
	var account = get_node('%Account' + str(number))
	Current.load_account(number)
	get_started.emit(account)


func _on_account_focus_entered(idx: int) -> void:
	current_idx = idx

```


