---
title: debug/chapters/chapters.tscn
---
:toc:

== debug / chapters / chapters.tscn

=== Diagram
[plantuml]
....
class R as "Chapters" <<(C,lightgreen) Control>> {
  * full_resource
---
  + _ready()
  + reload()
  + dump_json()
  + _on_reload_button_pressed()
  + _on_chapters_ui_backed()
}
class N1 as "Chapters" <<(C,lightgreen) Control>> {
  ~ focused
  ~ selected
  ~ ui_backed
---
  - ICON_OFFSET
  - INITIAL_CHAPTERS_X
  * grab_focus_first
  * play_opening
  * current_plate
  * shown
  * focused_chapter_idx
  * selected_chapter_idx
---
  + _ready()
  + setup_from_account_resource()
  + _input()
  + go_back()
  + go_foward()
  + set_grab_focus_first()
  + set_play_opening()
  + focus_pin_to()
  + zoom_pin_to()
  + force_focus_return()
  + load_focused_chapter_to_menu()
  + get_chapter()
  + set_chapters_animation_offset()
  + _on_chapater_focused()
  + _on_animation_player_animation_finished()
  + _on_selected()
  + _on_menu_ui_backed()
}
class N2 as "ReloadButton" <<(B,lightgreen) Button>> {
}
R --o N1
R --o N2
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_chapters_ui_backed, N1::ui_backed)
_(R::_on_reload_button_pressed, N2::pressed)
....




=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	Current.account = full_resource
	reload()
	dump_json()
```
.$Chapters
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('opening')
	FocusHelper.set_neighbors_h(%ChaptersContainer.get_children())
	for chapter in %ChaptersContainer.get_children():
		chapter.focus_entered.connect(_on_chapater_focused.bind(chapter))
	load_focused_chapter_to_menu()
```
==== _input
.$Chapters
```gdscript
func _input(event: InputEvent) -> void:
	if not (shown && current_plate == Plate.ROOT): return
	if event.is_action_pressed("ui_back"):
		go_back()
	elif event.is_action_pressed("ui_accept"):
		go_foward()
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Chapters# [.node-type.type-control]#Control#
** [.node-name.type-control]#Chapters# [.node-type.type-control]#link:/scenes/src/beginning/chapters/chapters.tscn[res://src/beginning/chapters/chapters.tscn]#
** [.node-name.type-control]#ReloadButton# [.node-type.type-control]#Button#


=== Signal Connections
[.signal-connection]
.$Chapters:[#_ui_backed_#]=>$.
```gdscript
func _on_chapters_ui_backed() -> void:
	reload()
```
[.signal-connection]
.$ReloadButton:[#_pressed_#]=>$.
```gdscript
func _on_reload_button_pressed() -> void:
	reload()
```




=== Properties
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`3`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme* |`ExtResource("1_4kat4")`
|*script* |`ExtResource("1_x5h8o")`
|*full_resource* |`ExtResource("3_n6u80")`
|===
.#$Chapters# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|===
.#$ReloadButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`0`
|*offset_left* |`128.0`
|*offset_top* |`796.0`
|*offset_right* |`335.0`
|*offset_bottom* |`887.0`
|*text* |`Reload`
|===


=== link:/scripts/debug/chapters/chapters.gd[chapters.gd]

```gdscript
extends Control

@export var full_resource : AccountResource


func _ready() -> void:
	Current.account = full_resource
	reload()
	dump_json()


func reload() -> void:
	%Chapters.setup_from_account_resource()
	%Chapters.play_opening = true


func dump_json() -> void:
	var json = ResourceHelper.json(Current.account)
	var res  = JSON.parse_string(json)
	true


func _on_reload_button_pressed() -> void:
	reload()


func _on_chapters_ui_backed() -> void:
	reload()

```


