---
title: src/player/player.tscn
---
:toc:

== src / player / player.tscn

=== Diagram
[plantuml]
....
class R as "Player" <<(C,lightskyblue) CharacterBody2D>> {
  ~ dashed
  ~ failed
---
  - SPEED
  - DASH_SPEED
  - JUMP_VELOCITY
  - GRAVITY
  - ALLOWED_TIME_TO_JUMP
  - DASH_TIME
  - DASH_ATTENUATION
  - MAX_DASH_COUNT
  * GhostEffect
  * falling_time
  * dash_rest_time
  * dash_rest_count
  * grounding
  * is_failed
---
  + _physics_process()
  + animate()
  + vibrate()
  + get_state()
  + update_sprite_states_shader_parameters()
  + spawn_ghost_effect()
  + current_sprite_state()
  + is_dashed()
  + _on_dashed()
  + _on_failed()
  + _on_frame_subject_area_entered()
  + _on_frame_subject_area_exited()
  + _on_failure_collision_area_entered()
}
class N1 as "Sprites" <<(N,lightskyblue) Node2D>> {
}
class N2 as "SpriteStates" <<(N,lightskyblue) Node2D>> {
}
class N3 as "IdleSprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N4 as "RunSprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N5 as "JumpSprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N6 as "FallSprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N7 as "SpriteEffects" <<(N,lightskyblue) Node2D>> {
}
class N8 as "BurstSprite2D" <<(S,lightskyblue) Sprite2D>> {
}
class N9 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N10 as "FailureCollision" <<(A,lightskyblue) Area2D>> {
}
class N11 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N12 as "FrameSubject" <<(A,lightskyblue) Area2D>> {
}
class N13 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N14 as "Camera" <<(C,lightskyblue) Camera2D>> {
  - DASH_SHAKING_TIME
  * shaking_time
  * fixed_position
  * current_frames
---
  + _process()
  + add_frame()
  + remove_frame()
  + apply_limitation()
  + shake()
  + shaking()
}
class N15 as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
class N16 as "AnimationTree" <<(A,darkgray) AnimationTree>> {
}
R --o N1
R --o N9
R --o N10
R --o N12
R --o N14
R --o N15
R --o N16
N1 --o N2
N1 --o N7
N2 --o N3
N2 --o N4
N2 --o N5
N2 --o N6
N7 --o N8
N10 --o N11
N12 --o N13
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_dashed, R::dashed)
_(R::_on_failed, R::failed)
_(R::_on_failure_collision_area_entered, N10::area_entered)
_(R::_on_frame_subject_area_entered, N12::area_entered)
_(R::_on_frame_subject_area_exited, N12::area_exited)
....


=== Overridden virtual functions
==== _physics_process
```gdscript
func _physics_process(delta: float) -> void:
	if is_failed:
		return
	if dash_rest_time > 0:
		dash_rest_time -= delta
		velocity *= DASH_ATTENUATION * delta
	else:
		# Add the gravity.
		if not is_on_floor():
			velocity.y += GRAVITY * delta
			falling_time += delta
			grounding = false
		else:
			if not grounding: vibrate('Landed')
			grounding = true
			falling_time = 0
			dash_rest_count = MAX_DASH_COUNT

		# Handle jump.
		if Input.is_action_just_pressed("move_jump") and falling_time < ALLOWED_TIME_TO_JUMP:
			velocity.y = JUMP_VELOCITY

		var direction_x := Input.get_axis("move_left", "move_right")
		if direction_x:
			velocity.x = direction_x * SPEED
		else:
			velocity.x = move_toward(velocity.x, 0, SPEED)

		# Handle dash.
		if Input.is_action_just_pressed("move_dash") && dash_rest_count > 0:
			var direction_y := Input.get_axis("move_up", "move_down")
			var direction = Vector2(direction_x, direction_y).normalized()
			if direction:
				dashed.emit()
				velocity = direction * DASH_SPEED
				dash_rest_time = DASH_TIME
				dash_rest_count -= 1
	animate()
	move_and_slide()
```
==== _process
.$Camera
```gdscript
func _process(delta: float) -> void:
	if shaking_time:
		shaking_time = maxf(0.0, shaking_time - delta)
		shaking()
```



=== Instantiators
* link:/scenes/src/chapters/0/stages/0/stage_0.tscn[res://src/chapters/0/stages/0/stage_0.tscn]
* link:/scenes/src/main.tscn[res://src/main.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Player# [.node-type.type-2d]#CharacterBody2D#
** [.node-name.type-2d]#Sprites# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#SpriteStates# [.node-type.type-2d]#Node2D#
**** [.node-name.type-2d]#IdleSprite2D# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#RunSprite2D# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#JumpSprite2D# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#FallSprite2D# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-2d]#SpriteEffects# [.node-type.type-2d]#Node2D#
**** [.node-name.type-2d]#BurstSprite2D# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#FailureCollision# [.node-type.type-2d]#Area2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#FrameSubject# [.node-type.type-2d]#Area2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#Camera# [.node-type.type-2d]#link:/scenes/src/player/camera/camera.tscn[res://src/player/camera/camera.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#
** [.node-name.type-other]#AnimationTree# [.node-type.type-other]#AnimationTree#


=== Signal Connections
[.signal-connection]
.$.:[#_dashed_#]=>$.
```gdscript
func _on_dashed() -> void:
	vibrate('Dashed')
	%Camera.shake(&'dash')
```
[.signal-connection]
.$.:[#_failed_#]=>$.
```gdscript
func _on_failed() -> void:
	is_failed = true
	%AnimationTree.active = false
	%AnimationPlayer.play("burst")
```
[.signal-connection]
.$FailureCollision:[#_area_entered_#]=>$.
```gdscript
func _on_failure_collision_area_entered(area: Area2D) -> void:
	failed.emit()
```
[.signal-connection]
.$FrameSubject:[#_area_entered_#]=>$.
```gdscript
func _on_frame_subject_area_entered(area: Area2D) -> void:
	%Camera.add_frame(area)
```
[.signal-connection]
.$FrameSubject:[#_area_exited_#]=>$.
```gdscript
func _on_frame_subject_area_exited(area: Area2D) -> void:
	%Camera.remove_frame(area)
```


=== Animations
==== fall_left

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T2
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T3
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T4


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = false
R  ->  T2 : position\n = Vector2(-12, -72)
R  ->o  T3 : visible\n = false
R  ->o  T4 : visible\n = true
R  ->o  T4 : flip_h\n = false
R  ->o  T4 : frame\n = 0
== Time: 0.125 ==
R  ->o  T4 : frame\n = 1

end
....
---

==== fall_right

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T2
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T3
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T4


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = false
R  ->  T2 : position\n = Vector2(12, -72)
R  ->o  T3 : visible\n = false
R  ->o  T4 : visible\n = true
R  ->o  T4 : flip_h\n = true
R  ->o  T4 : frame\n = 0
== Time: 0.125 ==
R  ->o  T4 : frame\n = 1

end
....
---

==== idle_left

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T1
participant "$Sprites" as T4
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T5
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T6


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->o  T1 : flip_h\n = false
R  ->o  T1 : frame\n = 0
R  ->  T4 : position\n = Vector2(-12, -72)
R  ->o  T5 : visible\n = false
R  ->o  T6 : visible\n = false
== Time: 0.2222 ==
R  ->o  T1 : frame\n = 1
== Time: 0.4444 ==
R  ->o  T1 : frame\n = 2
== Time: 0.6666 ==
R  ->o  T1 : frame\n = 3
== Time: 0.8888 ==
R  ->o  T1 : frame\n = 4
== Time: 1.111 ==
R  ->o  T1 : frame\n = 5
== Time: 1.3332 ==
R  ->o  T1 : frame\n = 6
== Time: 1.5554 ==
R  ->o  T1 : frame\n = 7
== Time: 1.7776 ==
R  ->o  T1 : frame\n = 8
== Time: 1.9998 ==
R  ->o  T1 : frame\n = 9
== Time: 2.222 ==
R  ->o  T1 : frame\n = 10
== Time: 2.4442 ==
R  ->o  T1 : frame\n = 11
== Time: 2.6664 ==
R  ->o  T1 : frame\n = 12
== Time: 2.8886 ==
R  ->o  T1 : frame\n = 13
== Time: 3.1108 ==
R  ->o  T1 : frame\n = 14
== Time: 3.333 ==
R  ->o  T1 : frame\n = 15
== Time: 3.5552 ==
R  ->o  T1 : frame\n = 16
== Time: 3.7774 ==
R  ->o  T1 : frame\n = 17
== Time: 3.9996 ==
R  ->o  T1 : frame\n = 18
== Time: 4.2218 ==
R  ->o  T1 : frame\n = 19
== Time: 4.444 ==
R  ->o  T1 : frame\n = 20
== Time: 4.6662 ==
R  ->o  T1 : frame\n = 21
== Time: 4.8884 ==
R  ->o  T1 : frame\n = 22
== Time: 5.1106 ==
R  ->o  T1 : frame\n = 23
== Time: 5.3328 ==
R  ->o  T1 : frame\n = 24
== Time: 5.555 ==
R  ->o  T1 : frame\n = 25

end
....
---

==== idle_right

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T1
participant "$Sprites" as T4
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T5


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->o  T1 : flip_h\n = true
R  ->o  T1 : frame\n = 0
R  ->  T4 : position\n = Vector2(12, -72)
R  ->o  T5 : visible\n = false
== Time: 0.2222 ==
R  ->o  T1 : frame\n = 1
== Time: 0.4444 ==
R  ->o  T1 : frame\n = 2
== Time: 0.6666 ==
R  ->o  T1 : frame\n = 3
== Time: 0.8888 ==
R  ->o  T1 : frame\n = 4
== Time: 1.111 ==
R  ->o  T1 : frame\n = 5
== Time: 1.3332 ==
R  ->o  T1 : frame\n = 6
== Time: 1.5554 ==
R  ->o  T1 : frame\n = 7
== Time: 1.7776 ==
R  ->o  T1 : frame\n = 8
== Time: 1.9998 ==
R  ->o  T1 : frame\n = 9
== Time: 2.222 ==
R  ->o  T1 : frame\n = 10
== Time: 2.4442 ==
R  ->o  T1 : frame\n = 11
== Time: 2.6664 ==
R  ->o  T1 : frame\n = 12
== Time: 2.8886 ==
R  ->o  T1 : frame\n = 13
== Time: 3.1108 ==
R  ->o  T1 : frame\n = 14
== Time: 3.333 ==
R  ->o  T1 : frame\n = 15
== Time: 3.5552 ==
R  ->o  T1 : frame\n = 16
== Time: 3.7774 ==
R  ->o  T1 : frame\n = 17
== Time: 3.9996 ==
R  ->o  T1 : frame\n = 18
== Time: 4.2218 ==
R  ->o  T1 : frame\n = 19
== Time: 4.444 ==
R  ->o  T1 : frame\n = 20
== Time: 4.6662 ==
R  ->o  T1 : frame\n = 21
== Time: 4.8884 ==
R  ->o  T1 : frame\n = 22
== Time: 5.1106 ==
R  ->o  T1 : frame\n = 23
== Time: 5.3328 ==
R  ->o  T1 : frame\n = 24
== Time: 5.555 ==
R  ->o  T1 : frame\n = 25

end
....
---

==== jump_left

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T2
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T3
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T4


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = false
R  ->  T2 : position\n = Vector2(-12, -72)
R  ->o  T3 : visible\n = true
R  ->o  T4 : visible\n = false
R  ->o  T3 : flip_h\n = false
R  ->o  T3 : frame\n = 0
== Time: 0.125 ==
R  ->o  T3 : frame\n = 1

end
....
---

==== jump_right

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T2
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T3
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T4


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = false
R  ->  T2 : position\n = Vector2(12, -72)
R  ->o  T3 : visible\n = true
R  ->o  T4 : visible\n = false
R  ->o  T3 : frame\n = 0
R  ->o  T3 : flip_h\n = true
== Time: 0.125 ==
R  ->o  T3 : frame\n = 1

end
....
---

==== run_left

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T4
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T5
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T6


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->o  T1 : flip_h\n = false
R  ->o  T1 : frame\n = 0
R  ->  T4 : position\n = Vector2(-12, -72)
R  ->o  T5 : visible\n = false
R  ->o  T6 : visible\n = false
== Time: 0.125 ==
R  ->o  T1 : frame\n = 1
== Time: 0.25 ==
R  ->o  T1 : frame\n = 2
== Time: 0.375 ==
R  ->o  T1 : frame\n = 3
== Time: 0.5 ==
R  ->o  T1 : frame\n = 4
== Time: 0.625 ==
R  ->o  T1 : frame\n = 5
== Time: 0.75 ==
R  ->o  T1 : frame\n = 6

end
....
---

==== run_right

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteStates\n/IdleSprite2D" as T0
participant "$Sprites\n/SpriteStates\n/RunSprite2D" as T1
participant "$Sprites" as T4
participant "$Sprites\n/SpriteStates\n/FallSprite2D" as T5
participant "$Sprites\n/SpriteStates\n/JumpSprite2D" as T6


loop
== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->o  T1 : flip_h\n = true
R  ->o  T1 : frame\n = 0
R  ->  T4 : position\n = Vector2(12, -72)
R  ->o  T5 : visible\n = false
R  ->o  T6 : visible\n = false
== Time: 0.125 ==
R  ->o  T1 : frame\n = 1
== Time: 0.25 ==
R  ->o  T1 : frame\n = 2
== Time: 0.375 ==
R  ->o  T1 : frame\n = 3
== Time: 0.5 ==
R  ->o  T1 : frame\n = 4
== Time: 0.625 ==
R  ->o  T1 : frame\n = 5
== Time: 0.75 ==
R  ->o  T1 : frame\n = 6

end
....
---

==== burst

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteEffects\n/BurstSprite2D" as T0
participant "$Sprites\n/SpriteStates" as T2



== Time: 0.0 ==
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)
== Time: 0.25 ==
R  ->  T2 : modulate\n = Color(14.814934, 14.814934, 14.814934, 1)
== Time: 0.4000001 ==
R  ->o  T0 : frame\n = 0
== Time: 0.45 ==
R  ->o  T0 : visible\n = true
== Time: 0.4500001 ==
R  ->o  T0 : frame\n = 1
== Time: 0.49 ==
R  ->o  T0 : frame\n = 2
== Time: 0.5000001 ==
R  ->o  T0 : frame\n = 2
== Time: 0.55 ==
R  ->o  T0 : frame\n = 3
== Time: 0.6 ==
R  ->o  T0 : frame\n = 4
R  ->  T2 : modulate\n = Color(14.814934, 14.814934, 14.814934, 0)
== Time: 0.65000004 ==
R  ->o  T0 : frame\n = 5
== Time: 0.7 ==
R  ->o  T0 : frame\n = 6
== Time: 0.75 ==
R  ->o  T0 : frame\n = 7
== Time: 0.8 ==
R  ->o  T0 : frame\n = 8
== Time: 0.85 ==
R  ->o  T0 : frame\n = 9
== Time: 0.90000004 ==
R  ->o  T0 : frame\n = 10
== Time: 0.95 ==
R  ->o  T0 : frame\n = 11
== Time: 1.0 ==
R  ->o  T0 : frame\n = 12
== Time: 1.0500001 ==
R  ->o  T0 : frame\n = 13
== Time: 1.1 ==
R  ->o  T0 : frame\n = 14
== Time: 1.15 ==
R  ->o  T0 : frame\n = 15
== Time: 1.2 ==
R  ->o  T0 : frame\n = 16
== Time: 1.25 ==
R  ->o  T0 : frame\n = 17
== Time: 1.3000001 ==
R  ->o  T0 : frame\n = 18
== Time: 1.35 ==
R  ->o  T0 : frame\n = 19
== Time: 1.4 ==
R  ->o  T0 : frame\n = 20
== Time: 1.45 ==
R  ->o  T0 : frame\n = 21
== Time: 1.5 ==
R  ->o  T0 : frame\n = 22
== Time: 1.5500001 ==
R  ->o  T0 : frame\n = 23
== Time: 1.6 ==
R  ->o  T0 : frame\n = 24
== Time: 1.65 ==
R  ->o  T0 : frame\n = 25
== Time: 1.7 ==
R  ->o  T0 : frame\n = 26
== Time: 1.75 ==
R  ->o  T0 : frame\n = 27
== Time: 1.8000001 ==
R  ->o  T0 : frame\n = 28
== Time: 1.85 ==
R  ->o  T0 : frame\n = 29
== Time: 1.9 ==
R  ->o  T0 : frame\n = 30
== Time: 1.95 ==
R  ->o  T0 : frame\n = 31
== Time: 2.0 ==
R  ->o  T0 : frame\n = 32
== Time: 2.05 ==
R  ->o  T0 : frame\n = 33
== Time: 2.1000001 ==
R  ->o  T0 : frame\n = 34
== Time: 2.15 ==
R  ->o  T0 : frame\n = 35
== Time: 2.2 ==
R  ->o  T0 : frame\n = 36
== Time: 2.25 ==
R  ->o  T0 : frame\n = 37
== Time: 2.3 ==
R  ->o  T0 : frame\n = 38
== Time: 2.3500001 ==
R  ->o  T0 : frame\n = 39
== Time: 2.4 ==
R  ->o  T0 : frame\n = 40
== Time: 2.45 ==
R  ->o  T0 : frame\n = 41
== Time: 2.5 ==
R  ->o  T0 : frame\n = 42
== Time: 2.55 ==
R  ->o  T0 : frame\n = 43
== Time: 2.6000001 ==
R  ->o  T0 : frame\n = 44
== Time: 2.65 ==
R  ->o  T0 : frame\n = 45
== Time: 2.7 ==
R  ->o  T0 : frame\n = 46
== Time: 2.75 ==
R  ->o  T0 : frame\n = 47
== Time: 2.8 ==
R  ->o  T0 : frame\n = 48
== Time: 2.8500001 ==
R  ->o  T0 : frame\n = 49
== Time: 2.9 ==
R  ->o  T0 : frame\n = 50
== Time: 2.95 ==
R  ->o  T0 : frame\n = 51
== Time: 3.0 ==
R  ->o  T0 : frame\n = 28
== Time: 3.05 ==
R  ->o  T0 : frame\n = 29
== Time: 3.1000001 ==
R  ->o  T0 : frame\n = 30
== Time: 3.15 ==
R  ->o  T0 : frame\n = 31
== Time: 3.2 ==
R  ->o  T0 : frame\n = 32
== Time: 3.25 ==
R  ->o  T0 : frame\n = 33
== Time: 3.3 ==
R  ->o  T0 : frame\n = 34
== Time: 3.3500001 ==
R  ->o  T0 : frame\n = 35
== Time: 3.4 ==
R  ->o  T0 : frame\n = 36
== Time: 3.45 ==
R  ->o  T0 : frame\n = 37
== Time: 3.5 ==
R  ->o  T0 : frame\n = 38
== Time: 3.55 ==
R  ->o  T0 : frame\n = 39
== Time: 3.6000001 ==
R  ->o  T0 : frame\n = 40
== Time: 3.65 ==
R  ->o  T0 : frame\n = 41
== Time: 3.7 ==
R  ->o  T0 : frame\n = 42
== Time: 3.75 ==
R  ->o  T0 : frame\n = 43
== Time: 3.8 ==
R  ->o  T0 : frame\n = 44
== Time: 3.8500001 ==
R  ->o  T0 : frame\n = 45
== Time: 3.9 ==
R  ->o  T0 : frame\n = 46
== Time: 3.95 ==
R  ->o  T0 : frame\n = 47
== Time: 4.0 ==
R  ->o  T0 : frame\n = 48
== Time: 4.05 ==
R  ->o  T0 : frame\n = 49
== Time: 4.1 ==
R  ->o  T0 : frame\n = 50
== Time: 4.15 ==
R  ->o  T0 : frame\n = 51
== Time: 4.2000003 ==
R  ->o  T0 : frame\n = 52
== Time: 4.25 ==
R  ->o  T0 : frame\n = 28
== Time: 4.3 ==
R  ->o  T0 : frame\n = 29
== Time: 4.35 ==
R  ->o  T0 : frame\n = 30
== Time: 4.4 ==
R  ->o  T0 : frame\n = 31
== Time: 4.4500003 ==
R  ->o  T0 : frame\n = 32
== Time: 4.5 ==
R  ->o  T0 : frame\n = 33
== Time: 4.55 ==
R  ->o  T0 : frame\n = 34
== Time: 4.6 ==
R  ->o  T0 : frame\n = 35
== Time: 4.65 ==
R  ->o  T0 : frame\n = 36
== Time: 4.7000003 ==
R  ->o  T0 : frame\n = 37
== Time: 4.75 ==
R  ->o  T0 : frame\n = 38
== Time: 4.8 ==
R  ->o  T0 : frame\n = 39
== Time: 4.85 ==
R  ->o  T0 : frame\n = 40
== Time: 4.9 ==
R  ->o  T0 : frame\n = 41
== Time: 4.9500003 ==
R  ->o  T0 : frame\n = 42
== Time: 5.0 ==
R  ->o  T0 : frame\n = 43


....
---

==== Animation_l271a

[plantuml]
....
control "Root" as R
participant "$Sprites\n/SpriteEffects\n/BurstSprite2D" as T0
participant "$Sprites\n/SpriteStates" as T2



== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T0 : frame\n = 11
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)


....
---



=== Properties
.Root properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* |`3`
|*script* |`ExtResource("1_5irfl")`
|*GhostEffect* |`ExtResource("2_xv5vk")`
|===
.$Sprites properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*position* |`Vector2(-12, -72)`
|*scale* |`Vector2(6, 6)`
|===
.$Sprites/SpriteStates properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|===
.$Sprites/SpriteStates/IdleSprite2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*material* |`SubResource("ShaderMaterial_jm5te")`
|*texture* |`ExtResource("2_byvol")`
|*hframes* |`27`
|*frame* |`21`
|===
.$Sprites/SpriteStates/RunSprite2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*material* |`SubResource("ShaderMaterial_c3wmo")`
|*texture* |`ExtResource("3_htsrw")`
|*hframes* |`8`
|===
.$Sprites/SpriteStates/JumpSprite2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*material* |`SubResource("ShaderMaterial_osywq")`
|*texture* |`ExtResource("4_gf1li")`
|*hframes* |`2`
|===
.$Sprites/SpriteStates/FallSprite2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*material* |`SubResource("ShaderMaterial_jpi3j")`
|*texture* |`ExtResource("5_vvr2x")`
|*hframes* |`2`
|===
.$Sprites/SpriteEffects properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*position* |`Vector2(2.1666667, 4)`
|===
.$Sprites/SpriteEffects/BurstSprite2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*position* |`Vector2(-1.6666666, -2.8333335)`
|*texture* |`ExtResource("8_l271a")`
|*hframes* |`53`
|*frame* |`11`
|===
.$CollisionShape2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(2, -51)`
|*shape* |`SubResource("CapsuleShape2D_opnj4")`
|===
.$FailureCollision properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* |`8`
|*collision_mask* |`8`
|===
.$FailureCollision/CollisionShape2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*position* |`Vector2(0, -56)`
|*shape* |`SubResource("CapsuleShape2D_l271a")`
|===
.$FrameSubject properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* |`4`
|*collision_mask* |`4`
|===
.$FrameSubject/CollisionShape2D properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*position* |`Vector2(3.5, -51.5)`
|*shape* |`SubResource("RectangleShape2D_x42xx")`
|===
.$Camera properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|===
.$AnimationPlayer properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*libraries* |`{
&"": SubResource("AnimationLibrary_u5nx7")
}`
|===
.$AnimationTree properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*root_node* |`NodePath("%AnimationTree/..")`
|*tree_root* |`SubResource("AnimationNodeStateMachine_mwkb6")`
|*anim_player* |`NodePath("../AnimationPlayer")`
|*parameters/Fall/blend_position* |`0.195104`
|*parameters/Idle/blend_position* |`-0.27003`
|*parameters/Jump/blend_position* |`0.414688`
|*parameters/Run/blend_position* |`-0.997033`
|===


=== link:/scripts/src/player/player.gd[player.gd]

```gdscript
extends CharacterBody2D
class_name Player

@export var GhostEffect : PackedScene

signal dashed
signal failed

const SPEED = 1000.0
const DASH_SPEED = SPEED * 4
const JUMP_VELOCITY = -1100.0
const GRAVITY = 4000
const ALLOWED_TIME_TO_JUMP = 0.15
const DASH_TIME = 0.1
const DASH_ATTENUATION = Vector2(55, 50)
const MAX_DASH_COUNT = 1
var falling_time := 0.0
var dash_rest_time := 0.0
var dash_rest_count := MAX_DASH_COUNT
var grounding : bool = true
var is_failed : bool = false


func _physics_process(delta: float) -> void:
	if is_failed:
		return
	if dash_rest_time > 0:
		dash_rest_time -= delta
		velocity *= DASH_ATTENUATION * delta
	else:
		# Add the gravity.
		if not is_on_floor():
			velocity.y += GRAVITY * delta
			falling_time += delta
			grounding = false
		else:
			if not grounding: vibrate('Landed')
			grounding = true
			falling_time = 0
			dash_rest_count = MAX_DASH_COUNT

		# Handle jump.
		if Input.is_action_just_pressed("move_jump") and falling_time < ALLOWED_TIME_TO_JUMP:
			velocity.y = JUMP_VELOCITY

		var direction_x := Input.get_axis("move_left", "move_right")
		if direction_x:
			velocity.x = direction_x * SPEED
		else:
			velocity.x = move_toward(velocity.x, 0, SPEED)

		# Handle dash.
		if Input.is_action_just_pressed("move_dash") && dash_rest_count > 0:
			var direction_y := Input.get_axis("move_up", "move_down")
			var direction = Vector2(direction_x, direction_y).normalized()
			if direction:
				dashed.emit()
				velocity = direction * DASH_SPEED
				dash_rest_time = DASH_TIME
				dash_rest_count -= 1
	animate()
	move_and_slide()


func animate():
	if is_failed: return
	if velocity.x:
		for state in ['Idle', 'Run', 'Jump', 'Fall']:
			%AnimationTree.set('parameters/%s/blend_position' % [state], velocity.x)
	%AnimationTree.get('parameters/playback').travel(get_state())
	update_sprite_states_shader_parameters()
	if dash_rest_time > 0 && int(dash_rest_time*100)%3 > 0:
		spawn_ghost_effect()


func vibrate(key: String):
	var values = [0, 0, 0]
	match key:
		'Dashed': values = [0.4, 0.6, 0.2]
		'Landed': values = [0.1, 0.3, 0.1]
	Input.start_joy_vibration(0, values[0], values[1], values[2])


func get_state() -> String:
	if velocity:
		if velocity.y < 0: return 'Jump'
		if velocity.y > 0: return 'Fall'
		else: return 'Run'
	else: return 'Idle'


func update_sprite_states_shader_parameters():
	for state in %SpriteStates.get_children():
		state.material.set_shader_parameter("dashed", is_dashed())


func spawn_ghost_effect():
	var ghost = GhostEffect.instantiate()
	ghost.spawn(self)


func current_sprite_state() -> Sprite2D:
	return %SpriteStates.get_children().filter(
		func(c): return c.visible)[0]


func is_dashed() -> bool:
	return true if dash_rest_count < MAX_DASH_COUNT else false


func _on_dashed() -> void:
	vibrate('Dashed')
	%Camera.shake(&'dash')


func _on_failed() -> void:
	is_failed = true
	%AnimationTree.active = false
	%AnimationPlayer.play("burst")


func _on_frame_subject_area_entered(area: Area2D) -> void:
	%Camera.add_frame(area)


func _on_frame_subject_area_exited(area: Area2D) -> void:
	%Camera.remove_frame(area)


func _on_failure_collision_area_entered(area: Area2D) -> void:
	failed.emit()

```


