---
title: src/beginning/chapters/menu/menu.tscn
---
:toc:

== src / beginning / chapters / menu / menu.tscn

=== Diagram
[plantuml]
....
class ROOT as "Menu" <<(C,lightgreen) Control>> {
  ~ ui_backed
  ~ get_started
---
  * grab_focus_first
  * grab_focus_side
  * grab_focus_stage
  * shown
  * chapter_resource
  * state
  * chapter_number
  * stage_resources
---
  + _ready()
  + load_chapter()
  + load_chapter_stages()
  + setup_from_account_resource()
  + set_grab_focus_first()
  + set_grab_focus_side()
  + set_grab_focus_stage()
  + clear_photos()
  + add_photo()
  + clear_stage_buttons()
  + add_stage_button()
  + get_stage_button()
  + hide_stage_button_and_photo()
  + stages_count()
  + _input()
  + _on_climb_button_pressed()
  + _on_stage_button_focus_entered()
  + _on_stage_button_pressed()
  + _on_ui_backed()
  + _on_get_started()
}
class BannerBox as "BannerBox" <<(C,lightgreen) Control>> {
}
class BannerBox_ChapterNumber as "ChapterNumber" <<(L,lightgreen) Label>> {
}
class BannerBox_ChapterName as "ChapterName" <<(L,lightgreen) Label>> {
}
class Box as "Box" <<(N,lightgreen) NinePatchRect>> {
}
class Banner as "Banner" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection as "SideSelection" <<(N,lightskyblue) Node2D>> {
}
class SideSelection_CenterBox as "CenterBox" <<(C,lightgreen) Control>> {
}
class SideSelection_CenterBox_BlueHeartIcon as "BlueHeartIcon" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection_CenterBox_StrawberryIcon as "StrawberryIcon" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection_CenterBox_MultiplicationStrawberry as "MultiplicationStrawberry" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection_CenterBox_StrawberryCountContainer as "StrawberryCountContainer" <<(H,lightgreen) HBoxContainer>> {
}
class SideSelection_CenterBox_StrawberryCountContainer_ObtainedStrawberryCount as "ObtainedStrawberryCount" <<(L,lightgreen) Label>> {
}
class SideSelection_CenterBox_StrawberryCountContainer_Slash as "Slash" <<(L,lightgreen) Label>> {
}
class SideSelection_CenterBox_StrawberryCountContainer_MaxStrawberryCount as "MaxStrawberryCount" <<(L,lightgreen) Label>> {
}
class SideSelection_CenterBox_FailureIcon as "FailureIcon" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection_CenterBox_MultiplicationStrawberry2 as "MultiplicationStrawberry2" <<(S,lightskyblue) Sprite2D>> {
}
class SideSelection_CenterBox_FailureCount as "FailureCount" <<(L,lightgreen) Label>> {
}
class SideSelection_BottomBox as "BottomBox" <<(C,lightgreen) Control>> {
}
class SideSelection_BottomBox_Label as "Label" <<(L,lightgreen) Label>> {
}
class SideSelection_SideButtonContainer as "SideButtonContainer" <<(B,lightgreen) BoxContainer>> {
}
class SideSelection_SideButtonContainer_ClimbBookmark as "ClimbBookmark" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class SideSelection_SideButtonContainer_CassetteBookmark as "CassetteBookmark" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class SideSelection_SideButtonContainer_CassetteBookmark_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class StageSelection as "StageSelection" <<(N,lightskyblue) Node2D>> {
}
class StageSelection_BottomBox as "BottomBox" <<(C,lightgreen) Control>> {
}
class StageSelection_BottomBox_StageLabel as "StageLabel" <<(L,lightgreen) Label>> {
}
class StageSelection_Photos as "Photos" <<(N,lightskyblue) Node2D>> {
}
class StageSelection_Photos_Template as "Template" <<(N,lightskyblue) Node2D>> {
}
class StageSelection_Photos_Template_Photo as "Photo" <<(S,lightskyblue) Sprite2D>> {
  * flicked
  * image
---
  + set_image()
  + flick()
  + pull()
}
class StageSelection_Photos_PhotoInstances as "PhotoInstances" <<(N,lightskyblue) Node2D>> {
}
class StageSelection_StageButtonContainer as "StageButtonContainer" <<(H,lightgreen) HBoxContainer>> {
}
class StageSelection_StageButtonContainer_Stage1Button as "Stage1Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class StageSelection_StageButtonContainer_Stage1Button_Bookmark as "Bookmark" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage1Button_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage2Button as "Stage2Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class StageSelection_StageButtonContainer_Stage2Button_Bookmark as "Bookmark" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage2Button_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage3Button as "Stage3Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class StageSelection_StageButtonContainer_Stage3Button_Bookmark as "Bookmark" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage3Button_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage4Button as "Stage4Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class StageSelection_StageButtonContainer_Stage4Button_Bookmark as "Bookmark" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage4Button_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage5Button as "Stage5Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class StageSelection_StageButtonContainer_Stage5Button_Bookmark as "Bookmark" <<(N,darkgray) Node>> {
}
class StageSelection_StageButtonContainer_Stage5Button_Bookmark_Sprite2D as "Sprite2D" <<(N,darkgray) Node>> {
}
class ClosingCurtain as "ClosingCurtain" <<(C,lightgreen) Control>> {
  * pattern
  * next_scene
---
  + play()
  + _on_animation_player_animation_finished()
}
class AnimationPlayer as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
ROOT --o BannerBox
ROOT --o Box
ROOT --o Banner
ROOT --o SideSelection
ROOT --o StageSelection
ROOT --o ClosingCurtain
ROOT --o AnimationPlayer
BannerBox --o BannerBox_ChapterNumber
BannerBox --o BannerBox_ChapterName
SideSelection --o SideSelection_CenterBox
SideSelection --o SideSelection_BottomBox
SideSelection --o SideSelection_SideButtonContainer
SideSelection_CenterBox --o SideSelection_CenterBox_BlueHeartIcon
SideSelection_CenterBox --o SideSelection_CenterBox_StrawberryIcon
SideSelection_CenterBox --o SideSelection_CenterBox_MultiplicationStrawberry
SideSelection_CenterBox --o SideSelection_CenterBox_StrawberryCountContainer
SideSelection_CenterBox --o SideSelection_CenterBox_FailureIcon
SideSelection_CenterBox --o SideSelection_CenterBox_MultiplicationStrawberry2
SideSelection_CenterBox --o SideSelection_CenterBox_FailureCount
SideSelection_CenterBox_StrawberryCountContainer --o SideSelection_CenterBox_StrawberryCountContainer_ObtainedStrawberryCount
SideSelection_CenterBox_StrawberryCountContainer --o SideSelection_CenterBox_StrawberryCountContainer_Slash
SideSelection_CenterBox_StrawberryCountContainer --o SideSelection_CenterBox_StrawberryCountContainer_MaxStrawberryCount
SideSelection_BottomBox --o SideSelection_BottomBox_Label
SideSelection_SideButtonContainer --o SideSelection_SideButtonContainer_ClimbBookmark
SideSelection_SideButtonContainer --o SideSelection_SideButtonContainer_CassetteBookmark
StageSelection --o StageSelection_BottomBox
StageSelection --o StageSelection_Photos
StageSelection --o StageSelection_StageButtonContainer
StageSelection_BottomBox --o StageSelection_BottomBox_StageLabel
StageSelection_Photos --o StageSelection_Photos_Template
StageSelection_Photos --o StageSelection_Photos_PhotoInstances
StageSelection_Photos_Template --o StageSelection_Photos_Template_Photo
StageSelection_StageButtonContainer --o StageSelection_StageButtonContainer_Stage1Button
StageSelection_StageButtonContainer --o StageSelection_StageButtonContainer_Stage2Button
StageSelection_StageButtonContainer --o StageSelection_StageButtonContainer_Stage3Button
StageSelection_StageButtonContainer --o StageSelection_StageButtonContainer_Stage4Button
StageSelection_StageButtonContainer --o StageSelection_StageButtonContainer_Stage5Button
StageSelection_StageButtonContainer_Stage1Button --o StageSelection_StageButtonContainer_Stage1Button_Bookmark
StageSelection_StageButtonContainer_Stage1Button_Bookmark --o StageSelection_StageButtonContainer_Stage1Button_Bookmark_Sprite2D
StageSelection_StageButtonContainer_Stage2Button --o StageSelection_StageButtonContainer_Stage2Button_Bookmark
StageSelection_StageButtonContainer_Stage2Button_Bookmark --o StageSelection_StageButtonContainer_Stage2Button_Bookmark_Sprite2D
StageSelection_StageButtonContainer_Stage3Button --o StageSelection_StageButtonContainer_Stage3Button_Bookmark
StageSelection_StageButtonContainer_Stage3Button_Bookmark --o StageSelection_StageButtonContainer_Stage3Button_Bookmark_Sprite2D
StageSelection_StageButtonContainer_Stage4Button --o StageSelection_StageButtonContainer_Stage4Button_Bookmark
StageSelection_StageButtonContainer_Stage4Button_Bookmark --o StageSelection_StageButtonContainer_Stage4Button_Bookmark_Sprite2D
StageSelection_StageButtonContainer_Stage5Button --o StageSelection_StageButtonContainer_Stage5Button_Bookmark
StageSelection_StageButtonContainer_Stage5Button_Bookmark --o StageSelection_StageButtonContainer_Stage5Button_Bookmark_Sprite2D
left to right direction
ROOT::_on_get_started <-[#blue,thickness=2]- ROOT::get_started
ROOT::_on_ui_backed <-[#blue,thickness=2]- ROOT::ui_backed
ROOT::_on_climb_button_pressed <-[#blue,thickness=2]- SideSelection_SideButtonContainer_ClimbBookmark::pressed
ROOT::_on_stage_button_focus_entered <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage1Button::focus_entered
ROOT::_on_stage_button_pressed <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage1Button::pressed
ROOT::_on_stage_button_focus_entered <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage2Button::focus_entered
ROOT::_on_stage_button_pressed <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage2Button::pressed
ROOT::_on_stage_button_focus_entered <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage3Button::focus_entered
ROOT::_on_stage_button_pressed <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage3Button::pressed
ROOT::_on_stage_button_focus_entered <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage4Button::focus_entered
ROOT::_on_stage_button_pressed <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage4Button::pressed
ROOT::_on_stage_button_focus_entered <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage5Button::focus_entered
ROOT::_on_stage_button_pressed <-[#blue,thickness=2]- StageSelection_StageButtonContainer_Stage5Button::pressed
....


=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('show')
	FocusHelper.set_neighbors_h(%SideButtonContainer.get_children())
	FocusHelper.set_neighbors_h(%StageButtonContainer.get_children())
```
==== _input
```gdscript
func _input(event: InputEvent) -> void:
	if not shown: return
	if event.is_action_pressed("ui_back"):
		match state:
			State.UNSELECTED: ui_backed.emit()
			State.SELECTED:
				state = State.UNSELECTED
				%AnimationPlayer.play("climb_unselected")
```


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Menu# [.node-type.type-control]#Control#
** [.node-name.type-control]#BannerBox# [.node-type.type-control]#Control#
*** [.node-name.type-control]#ChapterNumber# [.node-type.type-control]#Label#
*** [.node-name.type-control]#ChapterName# [.node-type.type-control]#Label#
** [.node-name.type-control]#Box# [.node-type.type-control]#NinePatchRect#
** [.node-name.type-2d]#Banner# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#SideSelection# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#CenterBox# [.node-type.type-control]#Control#
**** [.node-name.type-2d]#BlueHeartIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#StrawberryIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#MultiplicationStrawberry# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-control]#StrawberryCountContainer# [.node-type.type-control]#HBoxContainer#
***** [.node-name.type-control]#ObtainedStrawberryCount# [.node-type.type-control]#Label#
***** [.node-name.type-control]#Slash# [.node-type.type-control]#Label#
***** [.node-name.type-control]#MaxStrawberryCount# [.node-type.type-control]#Label#
**** [.node-name.type-2d]#FailureIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#MultiplicationStrawberry2# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-control]#FailureCount# [.node-type.type-control]#Label#
*** [.node-name.type-control]#BottomBox# [.node-type.type-control]#Control#
**** [.node-name.type-control]#Label# [.node-type.type-control]#Label#
*** [.node-name.type-control]#SideButtonContainer# [.node-type.type-control]#BoxContainer#
**** [.node-name.type-control]#ClimbBookmark# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
**** [.node-name.type-control]#CassetteBookmark# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
** [.node-name.type-2d]#StageSelection# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#BottomBox# [.node-type.type-control]#Control#
**** [.node-name.type-control]#StageLabel# [.node-type.type-control]#Label#
*** [.node-name.type-2d]#Photos# [.node-type.type-2d]#Node2D#
**** [.node-name.type-2d]#Template# [.node-type.type-2d]#Node2D#
***** [.node-name.type-2d]#Photo# [.node-type.type-2d]#link:/scenes/src/beginning/chapters/menu/photo/photo.tscn[res://src/beginning/chapters/menu/photo/photo.tscn]#
**** [.node-name.type-2d]#PhotoInstances# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#StageButtonContainer# [.node-type.type-control]#HBoxContainer#
**** [.node-name.type-control]#Stage1Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage2Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage3Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage4Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage5Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
** [.node-name.type-control]#ClosingCurtain# [.node-type.type-control]#link:/scenes/src/curtain/closing/closing.tscn[res://src/curtain/closing/closing.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Animations
==== Animation_m3sah

[plantuml]
....
control "Root" as Root
participant "SideSelection\n/CenterBox\n/StrawberryIcon" as T1
participant "SideSelection\n/CenterBox\n/FailureIcon" as T2
participant "SideSelection" as T3
participant "StageSelection" as T4
participant "Box" as T5
participant "SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T6
participant "SideSelection\n/CenterBox\n/BlueHeartIcon" as T10



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(960, 0)
Root  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
Root  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
Root  ->  T3 : position\n = Vector2(0, 0)
Root  ->  T4 : position\n = Vector2(0, 0)
Root  ->  T5 : size\n = Vector2(725, 678)
Root  ->o  T6 : focused\n = false
Root  ->o  Root : grab_focus_side\n = false
Root  ->o  Root : grab_focus_stage\n = false
Root  ->o  Root : shown\n = false
Root  ->  T10 : rotation\n = 0.0
Root  ->  T10 : scale\n = Vector2(1.38281, 1.38281)


....
---

==== climb_selected

[plantuml]
....
control "Root" as Root
participant "SideSelection" as T0
participant "StageSelection" as T1
participant "Box" as T3



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(0, 0)
Root  ->  T1 : position\n = Vector2(1000, 0)
Root  ->  Root : position\n = Vector2(0, 0)
Root  ->  T3 : size\n = Vector2(725, 678)
Root  ->o  Root : grab_focus_stage\n = true
Root  ->o  Root : grab_focus_side\n = false
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(1000, 0)
Root  ->  T3 : size\n = Vector2(725, 760)
== Time: 0.7 ==
Root  ->  T1 : position\n = Vector2(0, 0)


....
---

==== climb_unselected

[plantuml]
....
control "Root" as Root
participant "SideSelection" as T0
participant "StageSelection" as T1
participant "Box" as T3



== Time: 0.0 ==
Root  ->  T0 : position\n = Vector2(1000, 0)
Root  ->  T1 : position\n = Vector2(0, 0)
Root  ->  Root : position\n = Vector2(0, 0)
Root  ->  T3 : size\n = Vector2(725, 760)
Root  ->o  Root : grab_focus_stage\n = false
== Time: 0.1 ==
Root  ->o  Root : grab_focus_side\n = true
== Time: 0.5 ==
Root  ->  T0 : position\n = Vector2(0, 0)
== Time: 0.7 ==
Root  ->  T1 : position\n = Vector2(1000, 0)
Root  ->  T3 : size\n = Vector2(725, 678)


....
---

==== hide

[plantuml]
....
control "Root" as Root
participant "Box" as T1
participant "SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T2
participant "SideSelection" as T4
participant "StageSelection" as T5



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(0, 0)
Root  ->  T1 : size\n = Vector2(725, 678)
Root  ->  T4 : position\n = Vector2(0, 0)
Root  ->  T5 : position\n = Vector2(1000, 0)
Root  ->o  Root : shown\n = false
== Time: 0.1 ==
Root  ->o  T2 : focused\n = false
== Time: 0.2 ==
Root  ->o  Root : grab_focus_side\n = false
== Time: 0.5 ==
Root  ->  Root : position\n = Vector2(960, 0)


....
---

==== show

[plantuml]
....
control "Root" as Root
participant "SideSelection\n/CenterBox\n/StrawberryIcon" as T1
participant "SideSelection\n/CenterBox\n/FailureIcon" as T2
participant "Box" as T3
participant "SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T4
participant "SideSelection" as T6
participant "StageSelection" as T7
participant "SideSelection\n/CenterBox\n/BlueHeartIcon" as T9



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(960, 0)
Root  ->  T3 : size\n = Vector2(725, 678)
Root  ->o  T4 : focused\n = true
Root  ->  T6 : position\n = Vector2(0, 0)
Root  ->  T7 : position\n = Vector2(1000, 0)
Root  ->o  Root : shown\n = true
== Time: 0.12 ==
Root  ->o  Root : grab_focus_side\n = true
== Time: 0.23 ==
Root  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
Root  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
Root  ->  T9 : rotation\n = 0.0
== Time: 0.230703 ==
Root  ->  T9 : scale\n = Vector2(1.38281, 1.38281)
== Time: 0.38 ==
Root  ->  T1 : scale\n = Vector2(0.32, 0.32)
Root  ->  T2 : scale\n = Vector2(0.443, 0.443)
Root  ->  T9 : rotation\n = 0.0890118
Root  ->  T9 : scale\n = Vector2(1.583, 1.583)
== Time: 0.5 ==
Root  ->  Root : position\n = Vector2(0, 0)
Root  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
Root  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
Root  ->  T9 : rotation\n = 0.0
Root  ->  T9 : scale\n = Vector2(1.38281, 1.38281)


....
---



=== Signal Connections
[cols="1,1,1,2" options="header"]
|===
|From |Name |To |Method
|_._ |*get_started* |_._ |`_on_get_started`
|_._ |*ui_backed* |_._ |`_on_ui_backed`
|_SideSelection / SideButtonContainer / ClimbBookmark_ |*pressed* |_._ |`_on_climb_button_pressed`
|_StageSelection / StageButtonContainer / Stage1Button_ |*focus_entered* |_._ |`_on_stage_button_focus_entered`
|_StageSelection / StageButtonContainer / Stage1Button_ |*pressed* |_._ |`_on_stage_button_pressed`
|_StageSelection / StageButtonContainer / Stage2Button_ |*focus_entered* |_._ |`_on_stage_button_focus_entered`
|_StageSelection / StageButtonContainer / Stage2Button_ |*pressed* |_._ |`_on_stage_button_pressed`
|_StageSelection / StageButtonContainer / Stage3Button_ |*focus_entered* |_._ |`_on_stage_button_focus_entered`
|_StageSelection / StageButtonContainer / Stage3Button_ |*pressed* |_._ |`_on_stage_button_pressed`
|_StageSelection / StageButtonContainer / Stage4Button_ |*focus_entered* |_._ |`_on_stage_button_focus_entered`
|_StageSelection / StageButtonContainer / Stage4Button_ |*pressed* |_._ |`_on_stage_button_pressed`
|_StageSelection / StageButtonContainer / Stage5Button_ |*focus_entered* |_._ |`_on_stage_button_focus_entered`
|_StageSelection / StageButtonContainer / Stage5Button_ |*pressed* |_._ |`_on_stage_button_pressed`
|===


=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*length* |`0.001`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(960, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("SideSelection/CenterBox/StrawberryIcon:scale")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0.269531, 0.269531)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("SideSelection/CenterBox/FailureIcon:scale")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0.392578, 0.392578)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("SideSelection:position")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath("StageSelection:position")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("Box:size")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(725, 678)]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("SideSelection/SideButtonContainer/ClimbBookmark:focused")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath(".:grab_focus_side")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/8/type* |`value`
|_sub_resource_ |*tracks/8/imported* |`false`
|_sub_resource_ |*tracks/8/enabled* |`true`
|_sub_resource_ |*tracks/8/path* |`NodePath(".:grab_focus_stage")`
|_sub_resource_ |*tracks/8/interp* |`1`
|_sub_resource_ |*tracks/8/loop_wrap* |`true`
|_sub_resource_ |*tracks/8/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/9/type* |`value`
|_sub_resource_ |*tracks/9/imported* |`false`
|_sub_resource_ |*tracks/9/enabled* |`true`
|_sub_resource_ |*tracks/9/path* |`NodePath(".:shown")`
|_sub_resource_ |*tracks/9/interp* |`1`
|_sub_resource_ |*tracks/9/loop_wrap* |`true`
|_sub_resource_ |*tracks/9/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/10/type* |`value`
|_sub_resource_ |*tracks/10/imported* |`false`
|_sub_resource_ |*tracks/10/enabled* |`true`
|_sub_resource_ |*tracks/10/path* |`NodePath("SideSelection/CenterBox/BlueHeartIcon:rotation")`
|_sub_resource_ |*tracks/10/interp* |`1`
|_sub_resource_ |*tracks/10/loop_wrap* |`true`
|_sub_resource_ |*tracks/10/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [0.0]
}`
|_sub_resource_ |*tracks/11/type* |`value`
|_sub_resource_ |*tracks/11/imported* |`false`
|_sub_resource_ |*tracks/11/enabled* |`true`
|_sub_resource_ |*tracks/11/path* |`NodePath("SideSelection/CenterBox/BlueHeartIcon:scale")`
|_sub_resource_ |*tracks/11/interp* |`1`
|_sub_resource_ |*tracks/11/loop_wrap* |`true`
|_sub_resource_ |*tracks/11/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1.38281, 1.38281)]
}`
|_sub_resource_ |*resource_name* |`climb_selected`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("SideSelection:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(1000, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("StageSelection:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0, 0.7),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(1000, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Box:size")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(725, 678), Vector2(725, 760)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:grab_focus_stage")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath(".:grab_focus_side")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*resource_name* |`climb_unselected`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath("SideSelection:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 0.5),
"update": 0,
"values": [Vector2(1000, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("StageSelection:position")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0, 0.7),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(1000, 0)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Box:size")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0, 0.7),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(725, 760), Vector2(725, 678)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath(".:grab_focus_side")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0.1),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath(".:grab_focus_stage")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*resource_name* |`hide`
|_sub_resource_ |*length* |`0.5`
|_sub_resource_ |*step* |`0.01`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(960, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("Box:size")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(725, 678)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("SideSelection/SideButtonContainer/ClimbBookmark:focused")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0.1),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath(".:grab_focus_side")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0.2),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath("SideSelection:position")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath("StageSelection:position")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1000, 0)]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath(".:shown")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*resource_name* |`show`
|_sub_resource_ |*length* |`0.5`
|_sub_resource_ |*step* |`0.01`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(960, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath("SideSelection/CenterBox/StrawberryIcon:scale")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0.23, 0.38, 0.5),
"transitions": PackedFloat32Array(1, 1, 1),
"update": 0,
"values": [Vector2(0.269531, 0.269531), Vector2(0.32, 0.32), Vector2(0.269531, 0.269531)]
}`
|_sub_resource_ |*tracks/2/type* |`value`
|_sub_resource_ |*tracks/2/imported* |`false`
|_sub_resource_ |*tracks/2/enabled* |`true`
|_sub_resource_ |*tracks/2/path* |`NodePath("SideSelection/CenterBox/FailureIcon:scale")`
|_sub_resource_ |*tracks/2/interp* |`1`
|_sub_resource_ |*tracks/2/loop_wrap* |`true`
|_sub_resource_ |*tracks/2/keys* |`{
"times": PackedFloat32Array(0.23, 0.38, 0.5),
"transitions": PackedFloat32Array(1, 1, 1),
"update": 0,
"values": [Vector2(0.392578, 0.392578), Vector2(0.443, 0.443), Vector2(0.392578, 0.392578)]
}`
|_sub_resource_ |*tracks/3/type* |`value`
|_sub_resource_ |*tracks/3/imported* |`false`
|_sub_resource_ |*tracks/3/enabled* |`true`
|_sub_resource_ |*tracks/3/path* |`NodePath("Box:size")`
|_sub_resource_ |*tracks/3/interp* |`1`
|_sub_resource_ |*tracks/3/loop_wrap* |`true`
|_sub_resource_ |*tracks/3/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(725, 678)]
}`
|_sub_resource_ |*tracks/4/type* |`value`
|_sub_resource_ |*tracks/4/imported* |`false`
|_sub_resource_ |*tracks/4/enabled* |`true`
|_sub_resource_ |*tracks/4/path* |`NodePath("SideSelection/SideButtonContainer/ClimbBookmark:focused")`
|_sub_resource_ |*tracks/4/interp* |`1`
|_sub_resource_ |*tracks/4/loop_wrap* |`true`
|_sub_resource_ |*tracks/4/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/5/type* |`value`
|_sub_resource_ |*tracks/5/imported* |`false`
|_sub_resource_ |*tracks/5/enabled* |`true`
|_sub_resource_ |*tracks/5/path* |`NodePath(".:grab_focus_side")`
|_sub_resource_ |*tracks/5/interp* |`1`
|_sub_resource_ |*tracks/5/loop_wrap* |`true`
|_sub_resource_ |*tracks/5/keys* |`{
"times": PackedFloat32Array(0.12),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/6/type* |`value`
|_sub_resource_ |*tracks/6/imported* |`false`
|_sub_resource_ |*tracks/6/enabled* |`true`
|_sub_resource_ |*tracks/6/path* |`NodePath("SideSelection:position")`
|_sub_resource_ |*tracks/6/interp* |`1`
|_sub_resource_ |*tracks/6/loop_wrap* |`true`
|_sub_resource_ |*tracks/6/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/7/type* |`value`
|_sub_resource_ |*tracks/7/imported* |`false`
|_sub_resource_ |*tracks/7/enabled* |`true`
|_sub_resource_ |*tracks/7/path* |`NodePath("StageSelection:position")`
|_sub_resource_ |*tracks/7/interp* |`1`
|_sub_resource_ |*tracks/7/loop_wrap* |`true`
|_sub_resource_ |*tracks/7/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(1000, 0)]
}`
|_sub_resource_ |*tracks/8/type* |`value`
|_sub_resource_ |*tracks/8/imported* |`false`
|_sub_resource_ |*tracks/8/enabled* |`true`
|_sub_resource_ |*tracks/8/path* |`NodePath(".:shown")`
|_sub_resource_ |*tracks/8/interp* |`1`
|_sub_resource_ |*tracks/8/loop_wrap* |`true`
|_sub_resource_ |*tracks/8/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*tracks/9/type* |`value`
|_sub_resource_ |*tracks/9/imported* |`false`
|_sub_resource_ |*tracks/9/enabled* |`true`
|_sub_resource_ |*tracks/9/path* |`NodePath("SideSelection/CenterBox/BlueHeartIcon:rotation")`
|_sub_resource_ |*tracks/9/interp* |`1`
|_sub_resource_ |*tracks/9/loop_wrap* |`true`
|_sub_resource_ |*tracks/9/keys* |`{
"times": PackedFloat32Array(0.23, 0.38, 0.5),
"transitions": PackedFloat32Array(1, 1, 1),
"update": 0,
"values": [0.0, 0.0890118, 0.0]
}`
|_sub_resource_ |*tracks/10/type* |`value`
|_sub_resource_ |*tracks/10/imported* |`false`
|_sub_resource_ |*tracks/10/enabled* |`true`
|_sub_resource_ |*tracks/10/path* |`NodePath("SideSelection/CenterBox/BlueHeartIcon:scale")`
|_sub_resource_ |*tracks/10/interp* |`1`
|_sub_resource_ |*tracks/10/loop_wrap* |`true`
|_sub_resource_ |*tracks/10/keys* |`{
"times": PackedFloat32Array(0.230703, 0.38, 0.5),
"transitions": PackedFloat32Array(1, 1, 1),
"update": 0,
"values": [Vector2(1.38281, 1.38281), Vector2(1.583, 1.583), Vector2(1.38281, 1.38281)]
}`
|_sub_resource_ |*_data* |`{
&"RESET": SubResource("Animation_m3sah"),
&"climb_selected": SubResource("Animation_y3fl8"),
&"climb_unselected": SubResource("Animation_7mnsa"),
&"hide": SubResource("Animation_vm8b4"),
&"show": SubResource("Animation_txdb4")
}`
|_node_ |*layout_mode* |`3`
|_node_ |*anchors_preset* |`15`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`1.0`
|_node_ |*offset_left* |`960.0`
|_node_ |*offset_right* |`960.0`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*theme* |`ExtResource("1_hp5xr")`
|_node_ |*script* |`ExtResource("2_prk84")`
|_node_ |*chapter_resource* |`ExtResource("3_54dmq")`
|_node_ |*z_index* |`4`
|_node_ |*layout_mode* |`1`
|_node_ |*anchor_left* |`1.0`
|_node_ |*anchor_top* |`0.162`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.162`
|_node_ |*offset_left* |`-721.0`
|_node_ |*offset_top* |`-70.96`
|_node_ |*offset_right* |`4.0`
|_node_ |*offset_bottom* |`72.04`
|_node_ |*grow_horizontal* |`0`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_left* |`0.709`
|_node_ |*anchor_top* |`0.276`
|_node_ |*anchor_right* |`0.709`
|_node_ |*anchor_bottom* |`0.276`
|_node_ |*offset_left* |`-590.189`
|_node_ |*offset_top* |`-27.468`
|_node_ |*offset_right* |`-0.189026`
|_node_ |*offset_bottom* |`27.532`
|_node_ |*theme_override_colors/font_color* |`Color(0.242966, 0.242966, 0.242966, 1)`
|_node_ |*theme_override_colors/font_outline_color* |`Color(0.239, 0.239, 0.239, 0)`
|_node_ |*theme_override_font_sizes/font_size* |`36`
|_node_ |*text* |`Chapter 1`
|_node_ |*horizontal_alignment* |`2`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_left* |`0.709`
|_node_ |*anchor_top* |`0.64`
|_node_ |*anchor_right* |`0.709`
|_node_ |*anchor_bottom* |`0.64`
|_node_ |*offset_left* |`-590.189`
|_node_ |*offset_top* |`-33.52`
|_node_ |*offset_right* |`-0.189026`
|_node_ |*offset_bottom* |`33.48`
|_node_ |*text* |`Ghost town`
|_node_ |*horizontal_alignment* |`2`
|_node_ |*z_index* |`2`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_left* |`1.0`
|_node_ |*anchor_top* |`0.069`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.069`
|_node_ |*offset_left* |`-721.0`
|_node_ |*offset_top* |`0.479996`
|_node_ |*offset_right* |`4.0`
|_node_ |*offset_bottom* |`678.48`
|_node_ |*texture* |`ExtResource("1_avfsq")`
|_node_ |*region_rect* |`Rect2(235, 116, 725, 760)`
|_node_ |*patch_margin_bottom* |`300`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*z_index* |`3`
|_node_ |*texture_filter* |`2`
|_node_ |*position* |`Vector2(1639, 175)`
|_node_ |*texture* |`ExtResource("4_30gw0")`
|_node_ |*texture_filter* |`2`
|_node_ |*z_index* |`2`
|_node_ |*layout_mode* |`3`
|_node_ |*anchors_preset* |`0`
|_node_ |*offset_left* |`1256.0`
|_node_ |*offset_top* |`247.0`
|_node_ |*offset_right* |`1884.0`
|_node_ |*offset_bottom* |`517.0`
|_node_ |*theme* |`ExtResource("1_hp5xr")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*position* |`Vector2(150.5, 133.5)`
|_node_ |*scale* |`Vector2(1.38281, 1.38281)`
|_node_ |*texture* |`ExtResource("5_gfqg8")`
|_node_ |*position* |`Vector2(303, 92.5)`
|_node_ |*scale* |`Vector2(0.269531, 0.269531)`
|_node_ |*texture* |`ExtResource("5_trs7h")`
|_node_ |*position* |`Vector2(353, 94.5)`
|_node_ |*scale* |`Vector2(0.145145, 0.145145)`
|_node_ |*texture* |`ExtResource("5_tb0qi")`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_left* |`0.637`
|_node_ |*anchor_top* |`0.322`
|_node_ |*anchor_right* |`0.637`
|_node_ |*anchor_bottom* |`0.322`
|_node_ |*offset_left* |`-10.036`
|_node_ |*offset_top* |`-28.94`
|_node_ |*offset_right* |`126.964`
|_node_ |*offset_bottom* |`38.06`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*text* |`0`
|_node_ |*layout_mode* |`2`
|_node_ |*text* |`/`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*text* |`20`
|_node_ |*position* |`Vector2(327, 187.5)`
|_node_ |*scale* |`Vector2(0.392578, 0.392578)`
|_node_ |*texture* |`ExtResource("6_6dned")`
|_node_ |*position* |`Vector2(383, 188.5)`
|_node_ |*scale* |`Vector2(0.145, 0.145)`
|_node_ |*texture* |`ExtResource("5_tb0qi")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`0`
|_node_ |*offset_left* |`413.0`
|_node_ |*offset_top* |`151.5`
|_node_ |*offset_right* |`541.0`
|_node_ |*offset_bottom* |`218.5`
|_node_ |*text* |`0`
|_node_ |*z_index* |`2`
|_node_ |*layout_mode* |`3`
|_node_ |*anchor_left* |`1.0`
|_node_ |*anchor_top* |`0.713`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.713`
|_node_ |*offset_left* |`1199.0`
|_node_ |*offset_top* |`517.0`
|_node_ |*offset_right* |`1920.0`
|_node_ |*offset_bottom* |`753.0`
|_node_ |*grow_horizontal* |`0`
|_node_ |*theme* |`ExtResource("1_hp5xr")`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.913`
|_node_ |*offset_bottom* |`-61.468`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*theme_override_colors/font_color* |`Color(0.508731, 0.408952, 0.432275, 1)`
|_node_ |*theme_override_colors/font_outline_color* |`Color(0, 0, 0, 0)`
|_node_ |*text* |`Climb`
|_node_ |*horizontal_alignment* |`1`
|_node_ |*vertical_alignment* |`1`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*z_index* |`1`
|_node_ |*offset_left* |`1402.0`
|_node_ |*offset_top* |`648.0`
|_node_ |*offset_right* |`1739.0`
|_node_ |*offset_bottom* |`875.0`
|_node_ |*size_flags_horizontal* |`6`
|_node_ |*layout_mode* |`2`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`2`
|_node_ |*scale* |`Vector2(0.8, 0.8)`
|_node_ |*texture* |`ExtResource("5_sr4qr")`
|_node_ |*z_index* |`2`
|_node_ |*layout_mode* |`3`
|_node_ |*anchor_left* |`1.0`
|_node_ |*anchor_top* |`0.713`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.713`
|_node_ |*offset_left* |`1199.0`
|_node_ |*offset_top* |`648.269`
|_node_ |*offset_right* |`1920.0`
|_node_ |*offset_bottom* |`791.269`
|_node_ |*grow_horizontal* |`0`
|_node_ |*theme* |`ExtResource("1_hp5xr")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*anchors_preset* |`14`
|_node_ |*anchor_top* |`0.5`
|_node_ |*anchor_right* |`1.0`
|_node_ |*anchor_bottom* |`0.5`
|_node_ |*offset_top* |`-45.5`
|_node_ |*offset_bottom* |`33.5`
|_node_ |*grow_horizontal* |`2`
|_node_ |*grow_vertical* |`2`
|_node_ |*theme_override_colors/font_color* |`Color(0.508731, 0.408952, 0.432275, 1)`
|_node_ |*theme_override_colors/font_outline_color* |`Color(0, 0, 0, 0)`
|_node_ |*text* |`Get started`
|_node_ |*horizontal_alignment* |`1`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*z_index* |`2`
|_node_ |*position* |`Vector2(1545, 451)`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*z_index* |`1`
|_node_ |*offset_left* |`1293.0`
|_node_ |*offset_top* |`755.0`
|_node_ |*offset_right* |`1843.0`
|_node_ |*offset_bottom* |`951.0`
|_node_ |*size_flags_horizontal* |`4`
|_node_ |*alignment* |`1`
|_node_ |*layout_mode* |`2`
|_node_ |*texture* |`ExtResource("13_jxwkk")`
|_node_ |*scale* |`Vector2(0.7, 0.7)`
|_node_ |*texture* |`ExtResource("13_hfos7")`
|_node_ |*layout_mode* |`2`
|_node_ |*texture* |`ExtResource("15_7vn6q")`
|_node_ |*scale* |`Vector2(0.7, 0.7)`
|_node_ |*texture* |`ExtResource("15_wdor7")`
|_node_ |*layout_mode* |`2`
|_node_ |*texture* |`ExtResource("15_7vn6q")`
|_node_ |*scale* |`Vector2(0.7, 0.7)`
|_node_ |*texture* |`ExtResource("15_wdor7")`
|_node_ |*layout_mode* |`2`
|_node_ |*texture* |`ExtResource("15_7vn6q")`
|_node_ |*scale* |`Vector2(0.7, 0.7)`
|_node_ |*texture* |`ExtResource("15_wdor7")`
|_node_ |*layout_mode* |`2`
|_node_ |*texture* |`ExtResource("15_7vn6q")`
|_node_ |*scale* |`Vector2(0.7, 0.7)`
|_node_ |*texture* |`ExtResource("15_wdor7")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*layout_mode* |`1`
|_node_ |*offset_top* |`-1.0`
|_node_ |*offset_bottom* |`-1.0`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*libraries* |`{
&"": SubResource("AnimationLibrary_ebi0a")
}`
|===


=== link:/scripts/src/beginning/chapters/menu/menu.gd[menu.gd]

```gdscript
extends Control

signal ui_backed
signal get_started(stage_number: int)

@export var grab_focus_first : bool = false : set = set_grab_focus_first
@export var grab_focus_side  : bool = false : set = set_grab_focus_side
@export var grab_focus_stage : bool = false : set = set_grab_focus_stage
@export var shown : bool = false
@export var chapter_resource : ChapterResource : set = load_chapter
enum State { UNSELECTED, SELECTED }
var state : State = State.UNSELECTED
var chapter_number : int
var stage_resources : Array[StageResource]


func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('show')
	FocusHelper.set_neighbors_h(%SideButtonContainer.get_children())
	FocusHelper.set_neighbors_h(%StageButtonContainer.get_children())


func load_chapter(resource: ChapterResource) -> void:
	if not is_node_ready(): await ready
	chapter_number      = resource.number
	%ChapterNumber.text = 'Chapter %s' % resource.number
	%ChapterName.text   = resource.name
	%Banner.modulate    = resource.color
	%BlueHeartIcon.visible = false
	%MaxStrawberryCount.text = str(resource.strawberry_count())
	load_chapter_stages(resource)
	if Current.account: setup_from_account_resource()


func load_chapter_stages(resource: ChapterResource) -> void:
	clear_photos()
	clear_stage_buttons()
	stage_resources = []
	for i in resource.stages.size():
		var stage = resource.stages[i]
		add_photo(stage, i)
		add_stage_button(stage, i)
		stage_resources.push_back(stage)


func setup_from_account_resource() -> void:
	var chapter = Current.account.get_chapter(chapter_number)
	var stage_count = %StageButtonContainer.get_child_count() - 1
	var hidden_numbers = ArrayHelper.build(stage_count, false)
	if chapter:
		%CassetteBookmark.visible = chapter.obtained_cassette
		%BlueHeartIcon.visible    = chapter.obtained_blue_heart
		%ObtainedStrawberryCount.text = str(chapter.obtained_strawberry_count())
		%FailureCount.text = str(chapter.total_failure_count())
		for i in stage_count:
			hidden_numbers[i] = not chapter.has_stage(i+1)
	else:
		%CassetteBookmark.visible = false
	for i in stage_count:
		if hidden_numbers[i]:
			hide_stage_button_and_photo(i + 1)


func set_grab_focus_first(val) -> void:
	if val: %AnimationPlayer.play("show")


func set_grab_focus_side(val) -> void:
	FocusHelper.grab_first(%SideButtonContainer, val)


func set_grab_focus_stage(val) -> void:
	FocusHelper.grab_first(%StageButtonContainer, val)


func clear_photos() -> void:
	%Photos.get_node('Template').hide()
	for photo in %PhotoInstances.get_children():
		photo.queue_free()


func add_photo(resource: StageResource, idx: int) -> void:
	var photo = %Photos.get_node('Template/Photo').duplicate()
	photo.rotation = abs(photo.rotation) * (idx%2 * 2 - 1)
	photo.position += Vector2(8, -8) * idx
	photo.image = resource.photo
	photo.set_meta('number', idx + 1)
	%PhotoInstances.add_child(photo)
	%PhotoInstances.move_child(photo, 0)


func clear_stage_buttons() -> void:
	for button in %StageButtonContainer.get_children():
		button.hide()


func add_stage_button(resource: StageResource, idx: int) -> void:
	var stage = get_stage_button(idx)
	stage.set_meta('name', resource.name)
	stage.show()


func get_stage_button(idx: int) -> Node:
	return %StageButtonContainer.get_child(idx)


func hide_stage_button_and_photo(number: int) -> void:
	var button = %StageButtonContainer.get_child(number)
	if button: button.hide()
	for photo in %PhotoInstances.get_children():
		if photo.get_meta('number') == number:
			photo.hide()


func stages_count() -> int:
	return %StageButtonContainer.get_children().filter(func(c):
		return c.visible).size()


func _input(event: InputEvent) -> void:
	if not shown: return
	if event.is_action_pressed("ui_back"):
		match state:
			State.UNSELECTED: ui_backed.emit()
			State.SELECTED:
				state = State.UNSELECTED
				%AnimationPlayer.play("climb_unselected")


func _on_climb_button_pressed() -> void:
	if stages_count() > 1:
		state = State.SELECTED
		%AnimationPlayer.play("climb_selected")
	else:
		get_started.emit(1)


func _on_stage_button_focus_entered(number: int) -> void:
	var photos = %PhotoInstances.get_children()
	var button = get_stage_button(number - 1)
	%StageLabel.text = str(button.get_meta('name'))
	for i in photos.size():
		var photo = photos.pop_back()
		if i+1 < number: photo.flick()
		else: photo.pull()


func _on_stage_button_pressed(stage_number: int) -> void:
	get_started.emit(stage_number)


func _on_ui_backed() -> void:
	if shown: %AnimationPlayer.play("hide")


func _on_get_started(stage_number: int) -> void:
	var stage = stage_resources.filter(func(r):
		return r.number == stage_number)
	if not (stage && stage[0].scene): return
	%ClosingCurtain.play(stage[0].scene)

```


