---
title: src/beginning/chapters/menu/menu.tscn
---
:toc:

== src / beginning / chapters / menu / menu.tscn

=== Diagram
[plantuml]
....
class R as "Menu" <<(C,lightgreen) Control>> {
  ~ ui_backed
  ~ get_started
---
  * grab_focus_first
  * grab_focus_side
  * grab_focus_stage
  * shown
  * chapter_resource
  * state
  * chapter_number
  * stage_resources
---
  + _ready()
  + load_chapter()
  + load_chapter_stages()
  + setup_from_account_resource()
  + set_grab_focus_first()
  + set_grab_focus_side()
  + set_grab_focus_stage()
  + clear_photos()
  + add_photo()
  + clear_stage_buttons()
  + add_stage_button()
  + get_stage_button()
  + hide_stage_button_and_photo()
  + stages_count()
  + _input()
  + _on_climb_button_pressed()
  + _on_stage_button_focus_entered()
  + _on_stage_button_pressed()
  + _on_ui_backed()
  + _on_get_started()
}
class N1 as "BannerBox" <<(C,lightgreen) Control>> {
}
class N2 as "ChapterNumber" <<(L,lightgreen) Label>> {
}
class N3 as "ChapterName" <<(L,lightgreen) Label>> {
}
class N4 as "Box" <<(N,lightgreen) NinePatchRect>> {
}
class N5 as "Banner" <<(S,lightskyblue) Sprite2D>> {
}
class N6 as "SideSelection" <<(N,lightskyblue) Node2D>> {
}
class N7 as "CenterBox" <<(C,lightgreen) Control>> {
}
class N8 as "BlueHeartIcon" <<(S,lightskyblue) Sprite2D>> {
}
class N9 as "StrawberryIcon" <<(S,lightskyblue) Sprite2D>> {
}
class N10 as "MultiplicationStrawberry" <<(S,lightskyblue) Sprite2D>> {
}
class N11 as "StrawberryCountContainer" <<(H,lightgreen) HBoxContainer>> {
}
class N12 as "ObtainedStrawberryCount" <<(L,lightgreen) Label>> {
}
class N13 as "Slash" <<(L,lightgreen) Label>> {
}
class N14 as "MaxStrawberryCount" <<(L,lightgreen) Label>> {
}
class N15 as "FailureIcon" <<(S,lightskyblue) Sprite2D>> {
}
class N16 as "MultiplicationStrawberry2" <<(S,lightskyblue) Sprite2D>> {
}
class N17 as "FailureCount" <<(L,lightgreen) Label>> {
}
class N18 as "BottomBox" <<(C,lightgreen) Control>> {
}
class N19 as "Label" <<(L,lightgreen) Label>> {
}
class N20 as "SideButtonContainer" <<(B,lightgreen) BoxContainer>> {
}
class N21 as "ClimbBookmark" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N22 as "CassetteBookmark" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N23 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N24 as "StageSelection" <<(N,lightskyblue) Node2D>> {
}
class N25 as "BottomBox" <<(C,lightgreen) Control>> {
}
class N26 as "StageLabel" <<(L,lightgreen) Label>> {
}
class N27 as "Photos" <<(N,lightskyblue) Node2D>> {
}
class N28 as "Template" <<(N,lightskyblue) Node2D>> {
}
class N29 as "Photo" <<(S,lightskyblue) Sprite2D>> {
  * flicked
  * image
---
  + set_image()
  + flick()
  + pull()
}
class N30 as "PhotoInstances" <<(N,lightskyblue) Node2D>> {
}
class N31 as "StageButtonContainer" <<(H,lightgreen) HBoxContainer>> {
}
class N32 as "Stage1Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N33 as "Bookmark" <<(N,darkgray) Node>> {
}
class N34 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N35 as "Stage2Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N36 as "Bookmark" <<(N,darkgray) Node>> {
}
class N37 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N38 as "Stage3Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N39 as "Bookmark" <<(N,darkgray) Node>> {
}
class N40 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N41 as "Stage4Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N42 as "Bookmark" <<(N,darkgray) Node>> {
}
class N43 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N44 as "Stage5Button" <<(M,lightgreen) MarginContainer>> {
  ~ pressed
---
  * focused
---
  + _input()
  + set_focus()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N45 as "Bookmark" <<(N,darkgray) Node>> {
}
class N46 as "Sprite2D" <<(N,darkgray) Node>> {
}
class N47 as "ClosingCurtain" <<(C,lightgreen) Control>> {
  * pattern
  * next_scene
---
  + play()
  + _on_animation_player_animation_finished()
}
class N48 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
R --o N4
R --o N5
R --o N6
R --o N24
R --o N47
R --o N48
N1 --o N2
N1 --o N3
N6 --o N7
N6 --o N18
N6 --o N20
N7 --o N8
N7 --o N9
N7 --o N10
N7 --o N11
N7 --o N15
N7 --o N16
N7 --o N17
N11 --o N12
N11 --o N13
N11 --o N14
N18 --o N19
N20 --o N21
N20 --o N22
N24 --o N25
N24 --o N27
N24 --o N31
N25 --o N26
N27 --o N28
N27 --o N30
N28 --o N29
N31 --o N32
N31 --o N35
N31 --o N38
N31 --o N41
N31 --o N44
N32 --o N33
N33 --o N34
N35 --o N36
N36 --o N37
N38 --o N39
N39 --o N40
N41 --o N42
N42 --o N43
N44 --o N45
N45 --o N46
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_get_started, R::get_started)
_(R::_on_ui_backed, R::ui_backed)
_(R::_on_climb_button_pressed, N21::pressed)
_(R::_on_stage_button_focus_entered, N32::focus_entered)
_(R::_on_stage_button_pressed, N32::pressed)
_(R::_on_stage_button_focus_entered, N35::focus_entered)
_(R::_on_stage_button_pressed, N35::pressed)
_(R::_on_stage_button_focus_entered, N38::focus_entered)
_(R::_on_stage_button_pressed, N38::pressed)
_(R::_on_stage_button_focus_entered, N41::focus_entered)
_(R::_on_stage_button_pressed, N41::pressed)
_(R::_on_stage_button_focus_entered, N44::focus_entered)
_(R::_on_stage_button_pressed, N44::pressed)
....


=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('show')
	FocusHelper.set_neighbors_h(%SideButtonContainer.get_children())
	FocusHelper.set_neighbors_h(%StageButtonContainer.get_children())
```
==== _input
```gdscript
func _input(event: InputEvent) -> void:
	if not shown: return
	if event.is_action_pressed("ui_back"):
		match state:
			State.UNSELECTED: ui_backed.emit()
			State.SELECTED:
				state = State.UNSELECTED
				%AnimationPlayer.play("climb_unselected")
```
.$SideSelection/SideButtonContainer/ClimbBookmark, $SideSelection/SideButtonContainer/CassetteBookmark, $StageSelection/StageButtonContainer/Stage1Button, $StageSelection/StageButtonContainer/Stage2Button, $StageSelection/StageButtonContainer/Stage3Button, $StageSelection/StageButtonContainer/Stage4Button, $StageSelection/StageButtonContainer/Stage5Button
```gdscript
func _input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_accept") && focused:
		pressed.emit()
```



=== Instantiators
* link:/scenes/src/beginning/chapters/chapters.tscn[res://src/beginning/chapters/chapters.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Menu# [.node-type.type-control]#Control#
** [.node-name.type-control]#BannerBox# [.node-type.type-control]#Control#
*** [.node-name.type-control]#ChapterNumber# [.node-type.type-control]#Label#
*** [.node-name.type-control]#ChapterName# [.node-type.type-control]#Label#
** [.node-name.type-control]#Box# [.node-type.type-control]#NinePatchRect#
** [.node-name.type-2d]#Banner# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#SideSelection# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#CenterBox# [.node-type.type-control]#Control#
**** [.node-name.type-2d]#BlueHeartIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#StrawberryIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#MultiplicationStrawberry# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-control]#StrawberryCountContainer# [.node-type.type-control]#HBoxContainer#
***** [.node-name.type-control]#ObtainedStrawberryCount# [.node-type.type-control]#Label#
***** [.node-name.type-control]#Slash# [.node-type.type-control]#Label#
***** [.node-name.type-control]#MaxStrawberryCount# [.node-type.type-control]#Label#
**** [.node-name.type-2d]#FailureIcon# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-2d]#MultiplicationStrawberry2# [.node-type.type-2d]#Sprite2D#
**** [.node-name.type-control]#FailureCount# [.node-type.type-control]#Label#
*** [.node-name.type-control]#BottomBox# [.node-type.type-control]#Control#
**** [.node-name.type-control]#Label# [.node-type.type-control]#Label#
*** [.node-name.type-control]#SideButtonContainer# [.node-type.type-control]#BoxContainer#
**** [.node-name.type-control]#ClimbBookmark# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
**** [.node-name.type-control]#CassetteBookmark# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
** [.node-name.type-2d]#StageSelection# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#BottomBox# [.node-type.type-control]#Control#
**** [.node-name.type-control]#StageLabel# [.node-type.type-control]#Label#
*** [.node-name.type-2d]#Photos# [.node-type.type-2d]#Node2D#
**** [.node-name.type-2d]#Template# [.node-type.type-2d]#Node2D#
***** [.node-name.type-2d]#Photo# [.node-type.type-2d]#link:/scenes/src/beginning/chapters/menu/photo/photo.tscn[res://src/beginning/chapters/menu/photo/photo.tscn]#
**** [.node-name.type-2d]#PhotoInstances# [.node-type.type-2d]#Node2D#
*** [.node-name.type-control]#StageButtonContainer# [.node-type.type-control]#HBoxContainer#
**** [.node-name.type-control]#Stage1Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage2Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage3Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage4Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
**** [.node-name.type-control]#Stage5Button# [.node-type.type-control]#link:/scenes/src/beginning/chapters/menu/bookmark/bookmark.tscn[res://src/beginning/chapters/menu/bookmark/bookmark.tscn]#
***** [.node-name.type-other]#Bookmark# [.node-type.type-other]#Node#
****** [.node-name.type-other]#Sprite2D# [.node-type.type-other]#Node#
** [.node-name.type-control]#ClosingCurtain# [.node-type.type-control]#link:/scenes/src/curtain/closing/closing.tscn[res://src/curtain/closing/closing.tscn]#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$.:[#_get_started_#]=>$.
```gdscript
func _on_get_started(stage_number: int) -> void:
	var stage = stage_resources.filter(func(r):
		return r.number == stage_number)
	if not (stage && stage[0].scene): return
	%ClosingCurtain.play(stage[0].scene)
```
[.signal-connection]
.$.:[#_ui_backed_#]=>$.
```gdscript
func _on_ui_backed() -> void:
	if shown: %AnimationPlayer.play("hide")
```
[.signal-connection]
.$SideSelection/SideButtonContainer/ClimbBookmark:[#_pressed_#]=>$.
```gdscript
func _on_climb_button_pressed() -> void:
	if stages_count() > 1:
		state = State.SELECTED
		%AnimationPlayer.play("climb_selected")
	else:
		get_started.emit(1)
```
[.signal-connection]
.$StageSelection/StageButtonContainer/Stage1Button:[#_focus_entered_#]=>$., $StageSelection/StageButtonContainer/Stage2Button:[#_focus_entered_#]=>$., $StageSelection/StageButtonContainer/Stage3Button:[#_focus_entered_#]=>$., $StageSelection/StageButtonContainer/Stage4Button:[#_focus_entered_#]=>$., $StageSelection/StageButtonContainer/Stage5Button:[#_focus_entered_#]=>$.
```gdscript
func _on_stage_button_focus_entered(number: int) -> void:
	var photos = %PhotoInstances.get_children()
	var button = get_stage_button(number - 1)
	%StageLabel.text = str(button.get_meta('name'))
	for i in photos.size():
		var photo = photos.pop_back()
		if i+1 < number: photo.flick()
		else: photo.pull()
```
[.signal-connection]
.$StageSelection/StageButtonContainer/Stage1Button:[#_pressed_#]=>$., $StageSelection/StageButtonContainer/Stage2Button:[#_pressed_#]=>$., $StageSelection/StageButtonContainer/Stage3Button:[#_pressed_#]=>$., $StageSelection/StageButtonContainer/Stage4Button:[#_pressed_#]=>$., $StageSelection/StageButtonContainer/Stage5Button:[#_pressed_#]=>$.
```gdscript
func _on_stage_button_pressed(stage_number: int) -> void:
	get_started.emit(stage_number)
```


=== Animations
==== Animation_m3sah

[plantuml]
....
control "Root" as R
participant "$SideSelection\n/CenterBox\n/StrawberryIcon" as T1
participant "$SideSelection\n/CenterBox\n/FailureIcon" as T2
participant "$SideSelection" as T3
participant "$StageSelection" as T4
participant "$Box" as T5
participant "$SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T6
participant "$SideSelection\n/CenterBox\n/BlueHeartIcon" as T10



== Time: 0.0 ==
R  ->  R : position\n = Vector2(960, 0)
R  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
R  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
R  ->  T3 : position\n = Vector2(0, 0)
R  ->  T4 : position\n = Vector2(0, 0)
R  ->  T5 : size\n = Vector2(725, 678)
R  ->o  T6 : focused\n = false
R  ->o  R : grab_focus_side\n = false
R  ->o  R : grab_focus_stage\n = false
R  ->o  R : shown\n = false
R  ->  T10 : rotation\n = 0.0
R  ->  T10 : scale\n = Vector2(1.38281, 1.38281)


....
---

==== climb_selected

[plantuml]
....
control "Root" as R
participant "$SideSelection" as T0
participant "$StageSelection" as T1
participant "$Box" as T3



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(1000, 0)
R  ->  R : position\n = Vector2(0, 0)
R  ->  T3 : size\n = Vector2(725, 678)
R  ->o  R : grab_focus_stage\n = true
R  ->o  R : grab_focus_side\n = false
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(1000, 0)
R  ->  T3 : size\n = Vector2(725, 760)
== Time: 0.7 ==
R  ->  T1 : position\n = Vector2(0, 0)


....
---

==== climb_unselected

[plantuml]
....
control "Root" as R
participant "$SideSelection" as T0
participant "$StageSelection" as T1
participant "$Box" as T3



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(1000, 0)
R  ->  T1 : position\n = Vector2(0, 0)
R  ->  R : position\n = Vector2(0, 0)
R  ->  T3 : size\n = Vector2(725, 760)
R  ->o  R : grab_focus_stage\n = false
== Time: 0.1 ==
R  ->o  R : grab_focus_side\n = true
== Time: 0.5 ==
R  ->  T0 : position\n = Vector2(0, 0)
== Time: 0.7 ==
R  ->  T1 : position\n = Vector2(1000, 0)
R  ->  T3 : size\n = Vector2(725, 678)


....
---

==== hide

[plantuml]
....
control "Root" as R
participant "$Box" as T1
participant "$SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T2
participant "$SideSelection" as T4
participant "$StageSelection" as T5



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)
R  ->  T1 : size\n = Vector2(725, 678)
R  ->  T4 : position\n = Vector2(0, 0)
R  ->  T5 : position\n = Vector2(1000, 0)
R  ->o  R : shown\n = false
== Time: 0.1 ==
R  ->o  T2 : focused\n = false
== Time: 0.2 ==
R  ->o  R : grab_focus_side\n = false
== Time: 0.5 ==
R  ->  R : position\n = Vector2(960, 0)


....
---

==== show

[plantuml]
....
control "Root" as R
participant "$SideSelection\n/CenterBox\n/StrawberryIcon" as T1
participant "$SideSelection\n/CenterBox\n/FailureIcon" as T2
participant "$Box" as T3
participant "$SideSelection\n/SideButtonContainer\n/ClimbBookmark" as T4
participant "$SideSelection" as T6
participant "$StageSelection" as T7
participant "$SideSelection\n/CenterBox\n/BlueHeartIcon" as T9



== Time: 0.0 ==
R  ->  R : position\n = Vector2(960, 0)
R  ->  T3 : size\n = Vector2(725, 678)
R  ->o  T4 : focused\n = true
R  ->  T6 : position\n = Vector2(0, 0)
R  ->  T7 : position\n = Vector2(1000, 0)
R  ->o  R : shown\n = true
== Time: 0.12 ==
R  ->o  R : grab_focus_side\n = true
== Time: 0.23 ==
R  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
R  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
R  ->  T9 : rotation\n = 0.0
== Time: 0.230703 ==
R  ->  T9 : scale\n = Vector2(1.38281, 1.38281)
== Time: 0.38 ==
R  ->  T1 : scale\n = Vector2(0.32, 0.32)
R  ->  T2 : scale\n = Vector2(0.443, 0.443)
R  ->  T9 : rotation\n = 0.0890118
R  ->  T9 : scale\n = Vector2(1.583, 1.583)
== Time: 0.5 ==
R  ->  R : position\n = Vector2(0, 0)
R  ->  T1 : scale\n = Vector2(0.269531, 0.269531)
R  ->  T2 : scale\n = Vector2(0.392578, 0.392578)
R  ->  T9 : rotation\n = 0.0
R  ->  T9 : scale\n = Vector2(1.38281, 1.38281)


....
---



=== Properties
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`3`
|*anchors_preset* |`15`
|*anchor_right* |`1.0`
|*anchor_bottom* |`1.0`
|*offset_left* |`960.0`
|*offset_right* |`960.0`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme* |`ExtResource("1_hp5xr")`
|*script* |`ExtResource("2_prk84")`
|*chapter_resource* |`ExtResource("3_54dmq")`
|===
.#$BannerBox# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* |`4`
|*layout_mode* |`1`
|*anchor_left* |`1.0`
|*anchor_top* |`0.162`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.162`
|*offset_left* |`-721.0`
|*offset_top* |`-70.96`
|*offset_right* |`4.0`
|*offset_bottom* |`72.04`
|*grow_horizontal* |`0`
|===
.#$BannerBox/ChapterNumber# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*anchors_preset* |`-1`
|*anchor_left* |`0.709`
|*anchor_top* |`0.276`
|*anchor_right* |`0.709`
|*anchor_bottom* |`0.276`
|*offset_left* |`-590.189`
|*offset_top* |`-27.468`
|*offset_right* |`-0.189026`
|*offset_bottom* |`27.532`
|*theme_override_colors/font_color* |`Color(0.242966, 0.242966, 0.242966, 1)`
|*theme_override_colors/font_outline_color* |`Color(0.239, 0.239, 0.239, 0)`
|*theme_override_font_sizes/font_size* |`36`
|*text* |`Chapter 1`
|*horizontal_alignment* |`2`
|===
.#$BannerBox/ChapterName# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*anchors_preset* |`-1`
|*anchor_left* |`0.709`
|*anchor_top* |`0.64`
|*anchor_right* |`0.709`
|*anchor_bottom* |`0.64`
|*offset_left* |`-590.189`
|*offset_top* |`-33.52`
|*offset_right* |`-0.189026`
|*offset_bottom* |`33.48`
|*text* |`Ghost town`
|*horizontal_alignment* |`2`
|===
.#$Box# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* |`2`
|*layout_mode* |`1`
|*anchors_preset* |`-1`
|*anchor_left* |`1.0`
|*anchor_top* |`0.069`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.069`
|*offset_left* |`-721.0`
|*offset_top* |`0.479996`
|*offset_right* |`4.0`
|*offset_bottom* |`678.48`
|*texture* |`ExtResource("1_avfsq")`
|*region_rect* |`Rect2(235, 116, 725, 760)`
|*patch_margin_bottom* |`300`
|===
.#$Banner# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*z_index* |`3`
|*texture_filter* |`2`
|*position* |`Vector2(1639, 175)`
|*texture* |`ExtResource("4_30gw0")`
|===
.#$SideSelection# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture_filter* |`2`
|===
.#$SideSelection/CenterBox# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* |`2`
|*layout_mode* |`3`
|*anchors_preset* |`0`
|*offset_left* |`1256.0`
|*offset_top* |`247.0`
|*offset_right* |`1884.0`
|*offset_bottom* |`517.0`
|*theme* |`ExtResource("1_hp5xr")`
|===
.#$SideSelection/CenterBox/BlueHeartIcon# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*position* |`Vector2(150.5, 133.5)`
|*scale* |`Vector2(1.38281, 1.38281)`
|*texture* |`ExtResource("5_gfqg8")`
|===
.#$SideSelection/CenterBox/StrawberryIcon# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(303, 92.5)`
|*scale* |`Vector2(0.269531, 0.269531)`
|*texture* |`ExtResource("5_trs7h")`
|===
.#$SideSelection/CenterBox/MultiplicationStrawberry# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(353, 94.5)`
|*scale* |`Vector2(0.145145, 0.145145)`
|*texture* |`ExtResource("5_tb0qi")`
|===
.#$SideSelection/CenterBox/StrawberryCountContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`1`
|*anchors_preset* |`-1`
|*anchor_left* |`0.637`
|*anchor_top* |`0.322`
|*anchor_right* |`0.637`
|*anchor_bottom* |`0.322`
|*offset_left* |`-10.036`
|*offset_top* |`-28.94`
|*offset_right* |`126.964`
|*offset_bottom* |`38.06`
|===
.#$SideSelection/CenterBox/StrawberryCountContainer/ObtainedStrawberryCount# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*text* |`0`
|===
.#$SideSelection/CenterBox/StrawberryCountContainer/Slash# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|*text* |`/`
|===
.#$SideSelection/CenterBox/StrawberryCountContainer/MaxStrawberryCount# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|*text* |`20`
|===
.#$SideSelection/CenterBox/FailureIcon# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(327, 187.5)`
|*scale* |`Vector2(0.392578, 0.392578)`
|*texture* |`ExtResource("6_6dned")`
|===
.#$SideSelection/CenterBox/MultiplicationStrawberry2# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* |`Vector2(383, 188.5)`
|*scale* |`Vector2(0.145, 0.145)`
|*texture* |`ExtResource("5_tb0qi")`
|===
.#$SideSelection/CenterBox/FailureCount# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`0`
|*offset_left* |`413.0`
|*offset_top* |`151.5`
|*offset_right* |`541.0`
|*offset_bottom* |`218.5`
|*text* |`0`
|===
.#$SideSelection/BottomBox# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* |`2`
|*layout_mode* |`3`
|*anchor_left* |`1.0`
|*anchor_top* |`0.713`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.713`
|*offset_left* |`1199.0`
|*offset_top* |`517.0`
|*offset_right* |`1920.0`
|*offset_bottom* |`753.0`
|*grow_horizontal* |`0`
|*theme* |`ExtResource("1_hp5xr")`
|===
.#$SideSelection/BottomBox/Label# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`1`
|*anchors_preset* |`-1`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.913`
|*offset_bottom* |`-61.468`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme_override_colors/font_color* |`Color(0.508731, 0.408952, 0.432275, 1)`
|*theme_override_colors/font_outline_color* |`Color(0, 0, 0, 0)`
|*text* |`Climb`
|*horizontal_alignment* |`1`
|*vertical_alignment* |`1`
|===
.#$SideSelection/SideButtonContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*z_index* |`1`
|*offset_left* |`1402.0`
|*offset_top* |`648.0`
|*offset_right* |`1739.0`
|*offset_bottom* |`875.0`
|*size_flags_horizontal* |`6`
|===
.#$SideSelection/SideButtonContainer/ClimbBookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$SideSelection/SideButtonContainer/CassetteBookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`2`
|===
.#$SideSelection/SideButtonContainer/CassetteBookmark/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.8, 0.8)`
|*texture* |`ExtResource("5_sr4qr")`
|===
.#$StageSelection/BottomBox# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* |`2`
|*layout_mode* |`3`
|*anchor_left* |`1.0`
|*anchor_top* |`0.713`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.713`
|*offset_left* |`1199.0`
|*offset_top* |`648.269`
|*offset_right* |`1920.0`
|*offset_bottom* |`791.269`
|*grow_horizontal* |`0`
|*theme* |`ExtResource("1_hp5xr")`
|===
.#$StageSelection/BottomBox/StageLabel# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*anchors_preset* |`14`
|*anchor_top* |`0.5`
|*anchor_right* |`1.0`
|*anchor_bottom* |`0.5`
|*offset_top* |`-45.5`
|*offset_bottom* |`33.5`
|*grow_horizontal* |`2`
|*grow_vertical* |`2`
|*theme_override_colors/font_color* |`Color(0.508731, 0.408952, 0.432275, 1)`
|*theme_override_colors/font_outline_color* |`Color(0, 0, 0, 0)`
|*text* |`Get started`
|*horizontal_alignment* |`1`
|===
.#$StageSelection/Photos# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*z_index* |`2`
|*position* |`Vector2(1545, 451)`
|===
.#$StageSelection/Photos/PhotoInstances# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|===
.#$StageSelection/StageButtonContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*z_index* |`1`
|*offset_left* |`1293.0`
|*offset_top* |`755.0`
|*offset_right* |`1843.0`
|*offset_bottom* |`951.0`
|*size_flags_horizontal* |`4`
|*alignment* |`1`
|===
.#$StageSelection/StageButtonContainer/Stage1Button# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$StageSelection/StageButtonContainer/Stage1Button/Bookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* |`ExtResource("13_jxwkk")`
|===
.#$StageSelection/StageButtonContainer/Stage1Button/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.7, 0.7)`
|*texture* |`ExtResource("13_hfos7")`
|===
.#$StageSelection/StageButtonContainer/Stage2Button# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$StageSelection/StageButtonContainer/Stage2Button/Bookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* |`ExtResource("15_7vn6q")`
|===
.#$StageSelection/StageButtonContainer/Stage2Button/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.7, 0.7)`
|*texture* |`ExtResource("15_wdor7")`
|===
.#$StageSelection/StageButtonContainer/Stage3Button# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$StageSelection/StageButtonContainer/Stage3Button/Bookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* |`ExtResource("15_7vn6q")`
|===
.#$StageSelection/StageButtonContainer/Stage3Button/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.7, 0.7)`
|*texture* |`ExtResource("15_wdor7")`
|===
.#$StageSelection/StageButtonContainer/Stage4Button# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$StageSelection/StageButtonContainer/Stage4Button/Bookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* |`ExtResource("15_7vn6q")`
|===
.#$StageSelection/StageButtonContainer/Stage4Button/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.7, 0.7)`
|*texture* |`ExtResource("15_wdor7")`
|===
.#$StageSelection/StageButtonContainer/Stage5Button# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|===
.#$StageSelection/StageButtonContainer/Stage5Button/Bookmark# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* |`ExtResource("15_7vn6q")`
|===
.#$StageSelection/StageButtonContainer/Stage5Button/Bookmark/Sprite2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.7, 0.7)`
|*texture* |`ExtResource("15_wdor7")`
|===
.#$ClosingCurtain# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*layout_mode* |`1`
|*offset_top* |`-1.0`
|*offset_bottom* |`-1.0`
|===
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*libraries* |`{
&"": SubResource("AnimationLibrary_ebi0a")
}`
|===


=== link:/scripts/src/beginning/chapters/menu/menu.gd[menu.gd]

```gdscript
extends Control

signal ui_backed
signal get_started(stage_number: int)

@export var grab_focus_first : bool = false : set = set_grab_focus_first
@export var grab_focus_side  : bool = false : set = set_grab_focus_side
@export var grab_focus_stage : bool = false : set = set_grab_focus_stage
@export var shown : bool = false
@export var chapter_resource : ChapterResource : set = load_chapter
enum State { UNSELECTED, SELECTED }
var state : State = State.UNSELECTED
var chapter_number : int
var stage_resources : Array[StageResource]


func _ready() -> void:
	if get_parent() == get_tree().root:
		%AnimationPlayer.play('show')
	FocusHelper.set_neighbors_h(%SideButtonContainer.get_children())
	FocusHelper.set_neighbors_h(%StageButtonContainer.get_children())


func load_chapter(resource: ChapterResource) -> void:
	if not is_node_ready(): await ready
	chapter_number      = resource.number
	%ChapterNumber.text = 'Chapter %s' % resource.number
	%ChapterName.text   = resource.name
	%Banner.modulate    = resource.color
	%BlueHeartIcon.visible = false
	%MaxStrawberryCount.text = str(resource.strawberry_count())
	load_chapter_stages(resource)
	if Current.account: setup_from_account_resource()


func load_chapter_stages(resource: ChapterResource) -> void:
	clear_photos()
	clear_stage_buttons()
	stage_resources = []
	for i in resource.stages.size():
		var stage = resource.stages[i]
		add_photo(stage, i)
		add_stage_button(stage, i)
		stage_resources.push_back(stage)


func setup_from_account_resource() -> void:
	var chapter = Current.account.get_chapter(chapter_number)
	var stage_count = %StageButtonContainer.get_child_count() - 1
	var hidden_numbers = ArrayHelper.build(stage_count, false)
	if chapter:
		%CassetteBookmark.visible = chapter.obtained_cassette
		%BlueHeartIcon.visible    = chapter.obtained_blue_heart
		%ObtainedStrawberryCount.text = str(chapter.obtained_strawberry_count())
		%FailureCount.text = str(chapter.total_failure_count())
		for i in stage_count:
			hidden_numbers[i] = not chapter.has_stage(i+1)
	else:
		%CassetteBookmark.visible = false
	for i in stage_count:
		if hidden_numbers[i]:
			hide_stage_button_and_photo(i + 1)


func set_grab_focus_first(val) -> void:
	if val: %AnimationPlayer.play("show")


func set_grab_focus_side(val) -> void:
	FocusHelper.grab_first(%SideButtonContainer, val)


func set_grab_focus_stage(val) -> void:
	FocusHelper.grab_first(%StageButtonContainer, val)


func clear_photos() -> void:
	%Photos.get_node('Template').hide()
	for photo in %PhotoInstances.get_children():
		photo.queue_free()


func add_photo(resource: StageResource, idx: int) -> void:
	var photo = %Photos.get_node('Template/Photo').duplicate()
	photo.rotation = abs(photo.rotation) * (idx%2 * 2 - 1)
	photo.position += Vector2(8, -8) * idx
	photo.image = resource.photo
	photo.set_meta('number', idx + 1)
	%PhotoInstances.add_child(photo)
	%PhotoInstances.move_child(photo, 0)


func clear_stage_buttons() -> void:
	for button in %StageButtonContainer.get_children():
		button.hide()


func add_stage_button(resource: StageResource, idx: int) -> void:
	var stage = get_stage_button(idx)
	stage.set_meta('name', resource.name)
	stage.show()


func get_stage_button(idx: int) -> Node:
	return %StageButtonContainer.get_child(idx)


func hide_stage_button_and_photo(number: int) -> void:
	var button = %StageButtonContainer.get_child(number)
	if button: button.hide()
	for photo in %PhotoInstances.get_children():
		if photo.get_meta('number') == number:
			photo.hide()


func stages_count() -> int:
	return %StageButtonContainer.get_children().filter(func(c):
		return c.visible).size()


func _input(event: InputEvent) -> void:
	if not shown: return
	if event.is_action_pressed("ui_back"):
		match state:
			State.UNSELECTED: ui_backed.emit()
			State.SELECTED:
				state = State.UNSELECTED
				%AnimationPlayer.play("climb_unselected")


func _on_climb_button_pressed() -> void:
	if stages_count() > 1:
		state = State.SELECTED
		%AnimationPlayer.play("climb_selected")
	else:
		get_started.emit(1)


func _on_stage_button_focus_entered(number: int) -> void:
	var photos = %PhotoInstances.get_children()
	var button = get_stage_button(number - 1)
	%StageLabel.text = str(button.get_meta('name'))
	for i in photos.size():
		var photo = photos.pop_back()
		if i+1 < number: photo.flick()
		else: photo.pull()


func _on_stage_button_pressed(stage_number: int) -> void:
	get_started.emit(stage_number)


func _on_ui_backed() -> void:
	if shown: %AnimationPlayer.play("hide")


func _on_get_started(stage_number: int) -> void:
	var stage = stage_resources.filter(func(r):
		return r.number == stage_number)
	if not (stage && stage[0].scene): return
	%ClosingCurtain.play(stage[0].scene)

```


