---
title: src/curtain/closing/closing.tscn
---
:toc:

== src / curtain / closing / closing.tscn

=== Diagram
[plantuml]
....
class R as "ClosingCurtain" <<(C,lightgreen) Control>> {
  * pattern
  * next_scene
---
  + play()
  + _on_animation_player_animation_finished()
}
class N1 as "Pattern1" <<(N,lightskyblue) Node2D>> {
}
class N2 as "LeftCurtain" <<(P,lightskyblue) Polygon2D>> {
}
class N3 as "RightCurtain" <<(P,lightskyblue) Polygon2D>> {
}
class N4 as "Pattern2" <<(C,lightgreen) ColorRect>> {
}
class N5 as "Pattern3" <<(C,lightgreen) ColorRect>> {
}
class N6 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
R --o N4
R --o N5
R --o N6
N1 --o N2
N1 --o N3
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_animation_player_animation_finished, N6::animation_finished)
....






=== Instantiators
* link:/scenes/src/beginning/chapters/menu/menu.tscn[res://src/beginning/chapters/menu/menu.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#ClosingCurtain# [.node-type.type-control]#Control#
** [.node-name.type-2d]#Pattern1# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#LeftCurtain# [.node-type.type-2d]#Polygon2D#
*** [.node-name.type-2d]#RightCurtain# [.node-type.type-2d]#Polygon2D#
** [.node-name.type-control]#Pattern2# [.node-type.type-control]#ColorRect#
** [.node-name.type-control]#Pattern3# [.node-type.type-control]#ColorRect#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$AnimationPlayer:[#_animation_finished_#]=>$.
```gdscript
func _on_animation_player_animation_finished(_anim_name: StringName) -> void:
	if next_scene: SceneHelper.transit(self, next_scene)
```


=== Animations
==== Animation_bwqwf

[plantuml]
....
control "Root" as R
participant "$Pattern1\n/RightCurtain" as T0 #87CEFA
participant "$Pattern1\n/LeftCurtain" as T1 #87CEFA
participant "$Pattern1" as T2 #87CEFA
participant "$Pattern2" as T3 #90EE90
participant "$Pattern3" as T5 #90EE90



== Time: 0.0 ==
R  ->  T0 : polygon\n = PackedVector2Array(1920, 1080, 1920, 0, 960, 0, 1920, 540, 960, 1074)
R  ->  T1 : polygon\n = PackedVector2Array(0, 0, 0, 1080, 960, 1080, 9, 548, 960, 0)
R  ->  T2 : visible\n = false
R  ->o  T3 : visible\n = false
R  ->  T3 : material\n = 0.0
R  ->o  T5 : visible\n = false
R  ->  T5 : material\n = 0.5


....
---

==== pattern1

[plantuml]
....
control "Root" as R
participant "$Pattern1\n/RightCurtain" as T0 #87CEFA
participant "$Pattern1\n/LeftCurtain" as T1 #87CEFA
participant "$Pattern1" as T2 #87CEFA
participant "$Pattern2" as T3 #90EE90
participant "$Pattern3" as T4 #90EE90



== Time: 0.0 ==
R  ->  T0 : polygon\n = PackedVector2Array(1920, 1080, 1920, 0, 1920, 0, 1920, 540, 1920, 1080)
R  ->  T1 : polygon\n = PackedVector2Array(0, 0, 0, 1080, 0, 1080, 0, 548, 0, 0)
R  ->  T2 : visible\n = true
R  ->o  T3 : visible\n = false
R  ->o  T4 : visible\n = false
== Time: 0.5 ==
R  ->  T0 : polygon\n = PackedVector2Array(1920, 1080, 1920, 0, 960, 0, 1920, 540, 960, 1080)
R  ->  T1 : polygon\n = PackedVector2Array(0, 0, 0, 1080, 960, 1080, 0, 548, 960, 0)
== Time: 1.0 ==
R  ->  T0 : polygon\n = PackedVector2Array(1920, 1080, 1920, 0, 960, 0, 960, 540, 960, 1080)
R  ->  T1 : polygon\n = PackedVector2Array(0, 0, 0, 1080, 960, 1080, 960, 548, 960, 0)


....
---

==== pattern2

[plantuml]
....
control "Root" as R
participant "$Pattern2" as T0 #90EE90
participant "$Pattern1" as T1 #87CEFA
participant "$Pattern3" as T3 #90EE90



== Time: 0.0 ==
R  ->o  T0 : visible\n = true
R  ->  T1 : visible\n = false
R  ->  T0 : material\n = 1.0
R  ->o  T3 : visible\n = false
== Time: 0.5 ==
R  ->  T0 : material\n = 0.2
== Time: 1.0 ==
R  ->  T0 : material\n = -0.1


....
---

==== pattern3

[plantuml]
....
control "Root" as R
participant "$Pattern1" as T0 #87CEFA
participant "$Pattern2" as T1 #90EE90
participant "$Pattern3" as T2 #90EE90



== Time: 0.0 ==
R  ->  T0 : visible\n = false
R  ->o  T1 : visible\n = false
R  ->o  T2 : visible\n = true
R  ->  T2 : material\n = 0.0
== Time: 1.0 ==
R  ->  T2 : material\n = 1.0


....
---



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*z_index* a|`5`
|*z_as_relative* a|`false`
|*layout_mode* a|`3`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|*script* a|link:/scripts/src/curtain/closing/closing.gd[res://src/curtain/closing/closing.gd]
|===
[.node-property.node-2d]
.#$Pattern1# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* a|`false`
|===
[.node-property.node-2d]
.#$Pattern1/LeftCurtain# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*color* a|`Color(0, 0, 0, 1)`
|*polygon* a|`PackedVector2Array(0, 0, 0, 1080, 960, 1080, 9, 548, 960, 0)`
|*uv* a|`PackedVector2Array(572.5, -87.75, 575.5, -85.75)`
|===
[.node-property.node-2d]
.#$Pattern1/RightCurtain# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*color* a|`Color(0, 0, 0, 1)`
|*polygon* a|`PackedVector2Array(1920, 1080, 1920, 0, 960, 0, 1920, 540, 960, 1074)`
|*uv* a|`PackedVector2Array(1920, 1080, 1920, 0, 960, 0, 960, 540, 960, 1080, 492, 40.75)`
|===
[.node-property.node-control]
.#$Pattern2# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* a|`false`
|*material* a|`SubResource("ShaderMaterial_kivlp")`
|*layout_mode* a|`1`
|*anchors_preset* a|`-1`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*offset_top* a|`-450.0`
|*offset_bottom* a|`390.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$Pattern3# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* a|`false`
|*material* a|`SubResource("ShaderMaterial_663td")`
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*libraries* a|`{
&"": SubResource("AnimationLibrary_kivlp")
}`
|===


=== link:/scripts/src/curtain/closing/closing.gd[closing.gd]

```gdscript
extends Control

enum Pattern { PATTERN_1, PATTERN_2, PATTERN_3 }
@export var pattern : Pattern
@export_file('*.tscn') var next_scene : String


func play(_next_scene: String) -> void:
	next_scene = _next_scene
	var number = Pattern.keys()[pattern].split('_')[1]
	%AnimationPlayer.play("pattern%s" % number)


func _on_animation_player_animation_finished(_anim_name: StringName) -> void:
	if next_scene: SceneHelper.transit(self, next_scene)

```


