---
title: src/chapters/1/chapter1.tscn
---
:toc:

== src / chapters / 1 / chapter1.tscn

=== Diagram
[plantuml]
....
class R as "Chapter1" <<(C,lightgreen) Control>> {
}
class N1 as "Frames" <<(N,lightskyblue) Node2D>> {
}
class N2 as "CameraFrame" <<(A,lightskyblue) Area2D>> {
  - HALF_SIZE
---
  + corner_of()
  + corner()
}
class N3 as "Player" <<(C,lightskyblue) CharacterBody2D>> {
  ~ dashed
  ~ jumped
  ~ landed
  ~ failed
---
  - SPEED
  - DASH_SPEED
  - CLIMBING_SPEED
  - JUMP_VELOCITY
  - GRAVITY
  - ALLOWED_TIME_TO_JUMP
  - DASH_TIME
  - DASH_ATTENUATION
  - MAX_DASH_COUNT
  - MAX_CLIMBING_TIME
  - DEFAULT_SCALE
  * GhostEffect
  * LandedEffect
  * fatigue_curve
  * state
  * falling_time
  * dash_rest_time
  * dash_rest_count
  * climb_rest_time
  * sprite_tween
  * playable
---
  + _ready()
  + _physics_process()
  + compute_state()
  + is_just_input_action()
  + is_input_action()
  + animate()
  + animate_with()
  + compute_dashed()
  + idle()
  + walk_right()
  + walk_left()
  + turn_right()
  + turn_left()
  + dash()
  + lock()
  + unlock()
  + vibrate()
  + get_state_by()
  + tween_sprite()
  + update_sprite_states_shader_parameters()
  + spawn_ghost_effect()
  + current_sprite_state()
  + is_dashed()
  + _on_dashed()
  + _on_jumped()
  + _on_landed()
  + _on_failed()
  + _on_frame_subject_area_entered()
  + _on_frame_subject_area_exited()
  + _on_failure_collision_area_entered()
}
class N4 as "StageGround0" <<(T,yellow) TileMapLayer>> {
}
R --o N1
R --o N3
R --o N4
N1 --o N2
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _ready
.$Player
```gdscript
func _ready() -> void:
	playable = true
```
==== _physics_process
.$Player
```gdscript
func _physics_process(delta: float) -> void:
	var dx := Input.get_axis(&'move_left', &'move_right')
	var dy := Input.get_axis(&'move_up', &'move_down')
	var direction := Vector2(dx, dy)
	var last_state := state
	state = compute_state(delta, direction)
	match state:
		State.CLIMBING:
			dx = 0
			velocity.y = dy * CLIMBING_SPEED
		State.DASHED:
			velocity = direction.normalized() * DASH_SPEED
		State.DASHING:
			velocity *= DASH_ATTENUATION * delta
		State.EXHAUSTED:
			dx = 0
		State.FAILED:
			velocity.x = lerp(velocity.x, 0.0, 0.2)
			velocity.y = lerp(velocity.y, 0.0, 0.2)
		State.FALLING:
			if last_state == State.CLIMBING \
			and dy < 0:
				velocity.y = JUMP_VELOCITY * 0.8
			else:
				if velocity.y < JUMP_VELOCITY * 0.85:
					velocity.y += GRAVITY * 1.15 * delta
				else:
					velocity.y += GRAVITY * delta
		State.JUMPED:
			velocity.y = JUMP_VELOCITY
		State.LOCKED:
			dx = 0
			velocity = Vector2(0, 0)
		_: pass
	
	if not playable: dx = 0
	if not (state == State.DASHED or state == State.DASHING):
		if dx: velocity.x = dx * SPEED
		else: velocity.x = move_toward(velocity.x, 0, SPEED)

	animate(playable)
	move_and_slide()
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Chapter1# [.node-type.type-control]#Control#
** [.node-name.type-2d]#Frames# [.node-type.type-2d]#Node2D#
*** [.node-name.type-2d]#CameraFrame# [.node-type.type-2d]#link:/scenes/src/stages/frame/camera_frame.tscn[res://src/stages/frame/camera_frame.tscn]#
** [.node-name.type-2d]#Player# [.node-type.type-2d]#link:/scenes/src/player/player.tscn[res://src/player/player.tscn]#
** [.node-name.type-other]#StageGround0# [.node-type.type-other]#link:/scenes/src/stages/0/staege_ground_0.tscn[res://src/stages/0/staege_ground_0.tscn]#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`3`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-2d]
.#$Frames/CameraFrame# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(964, 538)`
|===
[.node-property.node-2d]
.#$Player# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(294, 346)`
|===




