---
title: src/beginning/screen/screen.tscn
---
:toc:

== src / beginning / screen / screen.tscn

=== Diagram
[plantuml]
....
class R as "Screen" <<(C,lightgreen) Control>> {
  * MenuScenePath
  * current_animation
---
  + _ready()
  + _input()
  + transit()
  + _on_animation_tree_animation_started()
  + _on_animation_tree_animation_finished()
}
class N1 as "Background" <<(C,lightgreen) ColorRect>> {
}
class N2 as "Author" <<(C,lightgreen) Control>> {
}
class N3 as "Container" <<(V,lightgreen) VBoxContainer>> {
}
class N4 as "NameContainer" <<(M,lightgreen) MarginContainer>> {
}
class N5 as "Name" <<(L,lightgreen) Label>> {
}
class N6 as "Presents" <<(L,lightgreen) Label>> {
}
class N7 as "Title" <<(C,lightgreen) Control>> {
}
class N8 as "TitleContainer" <<(C,lightgreen) CenterContainer>> {
}
class N9 as "TitleLogo" <<(S,lightskyblue) Sprite2D>> {
}
class N10 as "ButtonContainer" <<(M,lightgreen) MarginContainer>> {
}
class N11 as "JoyAButton" <<(S,lightskyblue) Sprite2D>> {
}
class N12 as "SubViewportContainer" <<(S,lightgreen) SubViewportContainer>> {
}
class N13 as "SubViewport" <<(S,yellow) SubViewport>> {
}
class N14 as "Show" <<(N,hotpink) Node3D>> {
}
class N15 as "Blinder" <<(C,lightgreen) ColorRect>> {
}
class N16 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
class N17 as "AnimationTree" <<(A,yellow) AnimationTree>> {
}
R --o N1
R --o N2
R --o N7
R --o N12
R --o N15
R --o N16
R --o N17
N2 --o N3
N3 --o N4
N3 --o N6
N4 --o N5
N7 --o N8
N7 --o N10
N8 --o N9
N10 --o N11
N12 --o N13
N13 --o N14
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_animation_tree_animation_finished, N17::animation_finished)
_(R::_on_animation_tree_animation_started, N17::animation_started)
....


[.scene-assets]
=== Assets
[.asset-image]
[link=/assets/assets/images/ui/Joy_A_button.svg]
image::/assets/raw/assets/images/ui/Joy_A_button.svg[200, 100] 



=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	SceneHelper.preload_scene(MenuScenePath)
```
==== _input
```gdscript
func _input(_event: InputEvent) -> void:
	if Input.is_action_just_pressed("ui_accept"):
		match current_animation:
			'show_title': transit('hide_title')
			'hide_title': pass
			_: 		      transit('show_title')
```


=== Instantiators
CAUTION: No other scene instantiate this scene.

=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Screen# [.node-type.type-control]#Control#
** [.node-name.type-control]#Background# [.node-type.type-control]#ColorRect#
** [.node-name.type-control]#Author# [.node-type.type-control]#Control#
*** [.node-name.type-control]#Container# [.node-type.type-control]#VBoxContainer#
**** [.node-name.type-control]#NameContainer# [.node-type.type-control]#MarginContainer#
***** [.node-name.type-control]#Name# [.node-type.type-control]#Label#
**** [.node-name.type-control]#Presents# [.node-type.type-control]#Label#
** [.node-name.type-control]#Title# [.node-type.type-control]#Control#
*** [.node-name.type-control]#TitleContainer# [.node-type.type-control]#CenterContainer#
**** [.node-name.type-2d]#TitleLogo# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-control]#ButtonContainer# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#JoyAButton# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-control]#SubViewportContainer# [.node-type.type-control]#SubViewportContainer#
*** [.node-name.type-other]#SubViewport# [.node-type.type-other]#SubViewport#
**** [.node-name.type-3d]#Show# [.node-type.type-3d]#link:/scenes/src/beginning/screen/snow/snow.tscn[res://src/beginning/screen/snow/snow.tscn]#
** [.node-name.type-control]#Blinder# [.node-type.type-control]#ColorRect#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#
** [.node-name.type-other]#AnimationTree# [.node-type.type-other]#AnimationTree#


=== Signal Connections
[.signal-connection]
.$AnimationTree:[#_animation_finished_#]=>$.
```gdscript
func _on_animation_tree_animation_finished(anim_name: StringName) -> void:
	if anim_name == 'hide_title':
		SceneHelper.transit(self, MenuScenePath)
```
[.signal-connection]
.$AnimationTree:[#_animation_started_#]=>$.
```gdscript
func _on_animation_tree_animation_started(anim_name: StringName) -> void:
	current_animation = anim_name
```


=== Animations
==== Animation_g86x5

[plantuml]
....
control "Root" as R
participant "$Author" as T0 #90EE90
participant "$Title" as T1 #90EE90
participant "$Title\n/TitleContainer\n/TitleLogo" as T4 #87CEFA
participant "$Blinder" as T6 #90EE90
participant "$Title\n/ButtonContainer" as T7 #90EE90



== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->  T0 : modulate\n = Color(1, 1, 1, 0)
R  ->  T1 : modulate\n = Color(1, 1, 1, 1)
R  ->  T4 : scale\n = Vector2(1, 1)
R  ->  T4 : modulate\n = Color(1, 1, 1, 1)
R  ->  T6 : color\n = Color(0, 0, 0, 0)
R  ->  T7 : position\n = Vector2(1820, 980)


....
---

==== hide_title

[plantuml]
....
control "Root" as R
participant "$Author" as T0 #90EE90
participant "$Title" as T1 #90EE90
participant "$Title\n/TitleContainer\n/TitleLogo" as T2 #87CEFA
participant "$Blinder" as T4 #90EE90
participant "$Title\n/ButtonContainer" as T5 #90EE90



== Time: 0.0 ==
R  ->o  T0 : visible\n = false
R  ->o  T1 : visible\n = true
R  ->  T2 : scale\n = Vector2(1, 1)
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)
R  ->  T4 : color\n = Color(0, 0, 0, 0)
R  ->  T5 : position\n = Vector2(1820, 980)
== Time: 0.1 ==
R  ->  T5 : position\n = Vector2(1820, 990)
== Time: 0.3 ==
R  ->  T5 : position\n = Vector2(1820, 1100)
== Time: 1.0 ==
R  ->  T2 : scale\n = Vector2(0.5, 0.5)
R  ->  T2 : modulate\n = Color(0, 0, 0, 0)
R  ->  T4 : color\n = Color(0.141176, 0.129412, 0.223529, 1)
R  ->  T5 : position\n = Vector2(1820, 1500)


....
---

==== opening (autoplay)

[plantuml]
....
control "Root" as R
participant "$Author" as T0 #90EE90
participant "$Title" as T1 #90EE90
participant "$Blinder" as T3 #90EE90



== Time: 0.0 ==
R  ->  T0 : visible\n = true
R  ->o  T1 : visible\n = false
R  ->  T0 : modulate\n = Color(1, 1, 1, 0)
R  ->  T3 : color\n = Color(0, 0, 0, 0)
== Time: 1.0 ==
R  ->  T0 : modulate\n = Color(1, 1, 1, 1)


....
---

==== show_title

[plantuml]
....
control "Root" as R
participant "$Author" as T0 #90EE90
participant "$Title" as T1 #90EE90
participant "$Title\n/TitleContainer\n/TitleLogo" as T4 #87CEFA
participant "$Blinder" as T5 #90EE90



== Time: 0.0 ==
R  ->o  T0 : visible\n = true
R  ->o  T1 : visible\n = true
R  ->  T0 : modulate\n = Color(1, 1, 1, 1)
R  ->  T4 : modulate\n = Color(1, 1, 1, 1)
R  ->  T5 : color\n = Color(0, 0, 0, 0)
== Time: 1.0 ==
R  ->o  T0 : visible\n = false
R  ->  T1 : modulate\n = Color(1, 1, 1, 0)
R  ->  T0 : modulate\n = Color(1, 1, 1, 0)
== Time: 2.0 ==
R  ->  T1 : modulate\n = Color(1, 1, 1, 1)


....
---



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`3`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|*script* a|link:/scripts/src/beginning/screen/screen.gd[res://src/beginning/screen/screen.gd]
|*MenuScenePath* a|link:/scenes/src/beginning/menu/menu.tscn[res://src/beginning/menu/menu.tscn]
|===
[.node-property.node-control]
.#$Background# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|*color* a|`Color(0.186624, 0.185867, 0.286366, 1)`
|===
[.node-property.node-control]
.#$Author# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*visible* a|`false`
|*modulate* a|`Color(1, 1, 1, 0)`
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$Author/Container# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`8`
|*anchor_left* a|`0.5`
|*anchor_top* a|`0.5`
|*anchor_right* a|`0.5`
|*anchor_bottom* a|`0.5`
|*offset_left* a|`-267.0`
|*offset_top* a|`-215.5`
|*offset_right* a|`267.0`
|*offset_bottom* a|`215.5`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$Author/Container/NameContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`2`
|*theme_override_constants/margin_bottom* a|`80`
|===
[.node-property.node-control]
.#$Author/Container/NameContainer/Name# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`2`
|*theme_override_fonts/font* a|`res://assets/fonts/Brownhill-Script/Brownhill Script.ttf`
|*theme_override_font_sizes/font_size* a|`250`
|*text* a|`tkmfujise`
|*horizontal_alignment* a|`1`
|===
[.node-property.node-control]
.#$Author/Container/Presents# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`2`
|*theme_override_colors/font_color* a|`Color(1, 1, 1, 0.196078)`
|*theme_override_font_sizes/font_size* a|`70`
|*text* a|`presents`
|*horizontal_alignment* a|`1`
|===
[.node-property.node-control]
.#$Title# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-control]
.#$Title/TitleContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-2d]
.#$Title/TitleContainer/TitleLogo# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(950, 522)`
|*texture* a|`res://assets/images/beginning/Title.svg`
|===
[.node-property.node-control]
.#$Title/ButtonContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`3`
|*anchor_left* a|`1.0`
|*anchor_top* a|`1.0`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*offset_left* a|`-100.0`
|*offset_top* a|`-100.0`
|*grow_horizontal* a|`0`
|*grow_vertical* a|`0`
|*theme_override_constants/margin_right* a|`100`
|*theme_override_constants/margin_bottom* a|`100`
|===
[.node-property.node-2d]
.#$Title/ButtonContainer/JoyAButton# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture* a|[link=/assets/assets/images/ui/Joy_A_button.svg]
[.asset-image]
.res://assets/images/ui/Joy_A_button.svg
image::/assets/raw/assets/images/ui/Joy_A_button.svg[]

|===
[.node-property.node-control]
.#$SubViewportContainer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|===
[.node-property.node-other]
.#$SubViewportContainer/SubViewport# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*transparent_bg* a|`true`
|*handle_input_locally* a|`false`
|*size* a|`Vector2i(1920, 1080)`
|*render_target_update_mode* a|`4`
|===
[.node-property.node-control]
.#$Blinder# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* a|`1`
|*anchors_preset* a|`15`
|*anchor_right* a|`1.0`
|*anchor_bottom* a|`1.0`
|*grow_horizontal* a|`2`
|*grow_vertical* a|`2`
|*color* a|`Color(0, 0, 0, 0)`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*libraries* a|`{
&"": SubResource("AnimationLibrary_5ydpp")
}`
|*autoplay* a|`opening`
|===
[.node-property.node-other]
.#$AnimationTree# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*root_node* a|`NodePath("%AnimationTree/..")`
|*tree_root* a|`SubResource("AnimationNodeStateMachine_f1cge")`
|*anim_player* a|`NodePath("../AnimationPlayer")`
|===


=== link:/scripts/src/beginning/screen/screen.gd[screen.gd]

```gdscript
extends Control

@export_file("*.tscn") var MenuScenePath : String
var current_animation : StringName


func _ready() -> void:
	SceneHelper.preload_scene(MenuScenePath)


func _input(_event: InputEvent) -> void:
	if Input.is_action_just_pressed("ui_accept"):
		match current_animation:
			'show_title': transit('hide_title')
			'hide_title': pass
			_: 		      transit('show_title')


func transit(animation: String):
	%AnimationTree.get('parameters/playback').start(animation)


func _on_animation_tree_animation_started(anim_name: StringName) -> void:
	current_animation = anim_name


func _on_animation_tree_animation_finished(anim_name: StringName) -> void:
	if anim_name == 'hide_title':
		SceneHelper.transit(self, MenuScenePath)

```


