---
title: src/stages/gimmicks/crumbling_platform/crumbling_platform.tscn
---
:toc:

== src / stages / gimmicks / crumbling_platform / crumbling_platform.tscn

=== Diagram
[plantuml]
....
class R as "CrumblingPlatform" <<(A,lightskyblue) Area2D>> {
  * falling
---
  + fall()
  + play()
  + _on_area_entered()
}
class N1 as "Piece1" <<(S,lightskyblue) Sprite2D>> {
}
class N2 as "Piece2" <<(S,lightskyblue) Sprite2D>> {
}
class N3 as "Piece3" <<(S,lightskyblue) Sprite2D>> {
}
class N4 as "StaticBody2D" <<(S,lightskyblue) StaticBody2D>> {
}
class N5 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N6 as "CollisionShape2D" <<(C,lightskyblue) CollisionShape2D>> {
}
class N7 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
R --o N2
R --o N3
R --o N4
R --o N6
R --o N7
N4 --o N5
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_area_entered, R::area_entered)
....






=== Instantiators
* link:/scenes/src/chapters/1/chapter1.tscn[res://src/chapters/1/chapter1.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#CrumblingPlatform# [.node-type.type-2d]#Area2D#
** [.node-name.type-2d]#Piece1# [.node-type.type-2d]#link:/scenes/src/stages/gimmicks/crumbling_platform/piece/piece.tscn[res://src/stages/gimmicks/crumbling_platform/piece/piece.tscn]#
** [.node-name.type-2d]#Piece2# [.node-type.type-2d]#link:/scenes/src/stages/gimmicks/crumbling_platform/piece/piece.tscn[res://src/stages/gimmicks/crumbling_platform/piece/piece.tscn]#
** [.node-name.type-2d]#Piece3# [.node-type.type-2d]#link:/scenes/src/stages/gimmicks/crumbling_platform/piece/piece.tscn[res://src/stages/gimmicks/crumbling_platform/piece/piece.tscn]#
** [.node-name.type-2d]#StaticBody2D# [.node-type.type-2d]#StaticBody2D#
*** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-2d]#CollisionShape2D# [.node-type.type-2d]#CollisionShape2D#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$.:[#_area_entered_#]=>$.
```gdscript
func _on_area_entered(area: Area2D) -> void:
	if not falling: fall()
```


=== Animations
==== fall

[plantuml]
....
control "Root" as R
participant "$Piece1" as T0 #87CEFA
participant "$Piece2" as T1 #87CEFA
participant "$Piece3" as T2 #87CEFA
participant "$StaticBody2D\n/CollisionShape2D" as T13 #87CEFA



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(48, 0)
R  ->  T2 : position\n = Vector2(96.00001, 0)
R  ->o  T0 : frame\n = 0
R  ->  T0 : modulate\n = Color(1, 1, 1, 1)
R  ->  T1 : modulate\n = Color(1, 1, 1, 1)
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)
R  ->  T0 : scale\n = Vector2(6, 6)
R  ->  T1 : scale\n = Vector2(6, 6)
R  ->  T2 : scale\n = Vector2(6, 6)
R  ->o  R : falling\n = true
R  ->o  T13 : disabled\n = false
== Time: 0.033333335 ==
R  ->o  T1 : frame\n = 1
== Time: 0.06666667 ==
R  ->o  T2 : frame\n = 2
== Time: 0.2 ==
R  ->  T0 : position\n = Vector2(3, 4)
R  ->  T1 : position\n = Vector2(50, 4)
R  ->  T2 : position\n = Vector2(99, 2)
== Time: 0.4 ==
R  ->  T0 : position\n = Vector2(2.27, 1.47)
R  ->  T1 : position\n = Vector2(49.52, 2.1)
R  ->  T2 : position\n = Vector2(98.49, 3.1)
== Time: 0.6 ==
R  ->  T0 : position\n = Vector2(1.07, -5.29)
R  ->  T1 : position\n = Vector2(40, 2.99)
R  ->  T2 : position\n = Vector2(97.18, 4.77)
R  ->o  T13 : disabled\n = true
== Time: 0.8 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(48, 0)
R  ->  T2 : position\n = Vector2(96.00001, 0)
R  ->o  T0 : frame\n = 3
R  ->o  T1 : frame\n = 4
R  ->o  T2 : frame\n = 5
R  ->  T0 : modulate\n = Color(1, 1, 1, 0)
R  ->  T1 : modulate\n = Color(1, 1, 1, 0)
R  ->  T2 : modulate\n = Color(1, 1, 1, 0)
== Time: 1.0 ==
R  ->  T0 : modulate\n = Color(1, 1, 1, 1)
R  ->  T1 : modulate\n = Color(1, 1, 1, 1)
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)
== Time: 1.7 ==
R  ->  T0 : scale\n = Vector2(6, 6)
R  ->  T1 : scale\n = Vector2(6, 6)
R  ->  T2 : scale\n = Vector2(6, 6)
== Time: 1.8 ==
R  ->o  T0 : frame\n = 2
R  ->  T0 : scale\n = Vector2(7, 7)
== Time: 1.9 ==
R  ->o  T1 : frame\n = 1
R  ->  T1 : scale\n = Vector2(7, 7)
== Time: 1.9333333 ==
R  ->  T2 : scale\n = Vector2(7, 7)
== Time: 2.0 ==
R  ->o  T2 : frame\n = 2
R  ->  T0 : scale\n = Vector2(6, 6)
R  ->  T1 : scale\n = Vector2(6, 6)
R  ->  T2 : scale\n = Vector2(6, 6)
R  ->o  R : falling\n = false
R  ->o  T13 : disabled\n = false


....
---

==== Animation_4jygs

[plantuml]
....
control "Root" as R
participant "$Piece1" as T0 #87CEFA
participant "$Piece2" as T1 #87CEFA
participant "$Piece3" as T2 #87CEFA
participant "$StaticBody2D\n/CollisionShape2D" as T13 #87CEFA



== Time: 0.0 ==
R  ->  T0 : position\n = Vector2(0, 0)
R  ->  T1 : position\n = Vector2(48, 0)
R  ->  T2 : position\n = Vector2(96.00001, 0)
R  ->o  T0 : frame\n = 0
R  ->o  T1 : frame\n = 1
R  ->o  T2 : frame\n = 2
R  ->  T0 : modulate\n = Color(1, 1, 1, 1)
R  ->  T1 : modulate\n = Color(1, 1, 1, 1)
R  ->  T2 : modulate\n = Color(1, 1, 1, 1)
R  ->  T0 : scale\n = Vector2(6, 6)
R  ->  T1 : scale\n = Vector2(6, 6)
R  ->  T2 : scale\n = Vector2(6, 6)
R  ->o  R : falling\n = false
R  ->o  T13 : disabled\n = false


....
---



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*collision_layer* a|`0`
|*collision_mask* a|`2`
|*script* a|link:/scripts/src/stages/gimmicks/crumbling_platform/crumbling_platform.gd[res://src/stages/gimmicks/crumbling_platform/crumbling_platform.gd]
|===
[.node-property.node-2d]
.#$Piece2# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(48, 0)`
|*frame* a|`1`
|===
[.node-property.node-2d]
.#$Piece3# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(96.00001, 0)`
|*frame* a|`2`
|===
[.node-property.node-2d]
.#$StaticBody2D/CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(48, 0)`
|*shape* a|`SubResource("RectangleShape2D_g8o2p")`
|===
[.node-property.node-2d]
.#$CollisionShape2D# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*position* a|`Vector2(48, -26.5)`
|*shape* a|`SubResource("RectangleShape2D_5yfgi")`
|*debug_color* a|`Color(0.7650758, 0.40966964, 0.49610847, 0.41960785)`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*libraries* a|`{
&"": SubResource("AnimationLibrary_uleia")
}`
|===


=== link:/scripts/src/stages/gimmicks/crumbling_platform/crumbling_platform.gd[crumbling_platform.gd]

```gdscript
extends Area2D

@export var falling : bool = false


func fall() -> void:
	play.call_deferred(&'fall')


func play(key: StringName) -> void:
	%AnimationPlayer.play(key)


func _on_area_entered(area: Area2D) -> void:
	if not falling: fall()

```


