---
title: src/beginning/chapters/menu/photo/photo.tscn
---
:toc:

== src / beginning / chapters / menu / photo / photo.tscn

=== Diagram
[plantuml]
....
class ROOT as "Photo" <<(S,lightskyblue) Sprite2D>> {
  * flicked
  * image
---
  + set_image()
  + flick()
  + pull()
}
class Frame as "Frame" <<(P,lightskyblue) Polygon2D>> {
}
class Frame_Image as "Image" <<(S,lightskyblue) Sprite2D>> {
}
class Strawberries as "Strawberries" <<(H,lightgreen) HBoxContainer>> {
}
class Strawberries_Strawberry1 as "Strawberry1" <<(M,lightgreen) MarginContainer>> {
}
class Strawberries_Strawberry1_Strawberry as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class Strawberries_Strawberry2 as "Strawberry2" <<(M,lightgreen) MarginContainer>> {
}
class Strawberries_Strawberry2_Strawberry as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class Strawberries_Strawberry3 as "Strawberry3" <<(M,lightgreen) MarginContainer>> {
}
class Strawberries_Strawberry3_Strawberry as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class AnimationPlayer as "AnimationPlayer" <<(A,darkgray) AnimationPlayer>> {
}
ROOT --o Frame
ROOT --o Strawberries
ROOT --o AnimationPlayer
Frame --o Frame_Image
Strawberries --o Strawberries_Strawberry1
Strawberries --o Strawberries_Strawberry2
Strawberries --o Strawberries_Strawberry3
Strawberries_Strawberry1 --o Strawberries_Strawberry1_Strawberry
Strawberries_Strawberry2 --o Strawberries_Strawberry2_Strawberry
Strawberries_Strawberry3 --o Strawberries_Strawberry3_Strawberry
left to right direction

....





=== Instantiators
* link:/scenes/src/beginning/chapters/menu/menu.tscn[res://src/beginning/chapters/menu/menu.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Photo# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#Frame# [.node-type.type-2d]#Polygon2D#
*** [.node-name.type-2d]#Image# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-control]#Strawberries# [.node-type.type-control]#HBoxContainer#
*** [.node-name.type-control]#Strawberry1# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-control]#Strawberry2# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-control]#Strawberry3# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Animations
==== Animation_tk6ev

[plantuml]
....
control "Root" as Root



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(0, 0)
Root  ->o  Root : flicked\n = false


....
---

==== flick

[plantuml]
....
control "Root" as Root



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(0, 0)
== Time: 0.0333333 ==
Root  ->o  Root : flicked\n = true
== Time: 0.5 ==
Root  ->  Root : position\n = Vector2(1920, 0)


....
---

==== pull

[plantuml]
....
control "Root" as Root



== Time: 0.0 ==
Root  ->  Root : position\n = Vector2(1920, 0)
== Time: 0.0333333 ==
Root  ->o  Root : flicked\n = false
== Time: 0.5 ==
Root  ->  Root : position\n = Vector2(0, 0)


....
---



=== Signal Connections
NOTE: No signal connections.

=== Properties
[cols="1,1,3" options="header"]
|===
|Section |Name |Value
|_sub_resource_ |*length* |`0.001`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 0,
"values": [Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath(".:flicked")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*resource_name* |`flick`
|_sub_resource_ |*length* |`0.5`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.5, 1),
"update": 0,
"values": [Vector2(0, 0), Vector2(1920, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath(".:flicked")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0.0333333),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [true]
}`
|_sub_resource_ |*resource_name* |`pull`
|_sub_resource_ |*length* |`0.5`
|_sub_resource_ |*tracks/0/type* |`value`
|_sub_resource_ |*tracks/0/imported* |`false`
|_sub_resource_ |*tracks/0/enabled* |`true`
|_sub_resource_ |*tracks/0/path* |`NodePath(".:position")`
|_sub_resource_ |*tracks/0/interp* |`1`
|_sub_resource_ |*tracks/0/loop_wrap* |`true`
|_sub_resource_ |*tracks/0/keys* |`{
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(0.25, 1),
"update": 0,
"values": [Vector2(1920, 0), Vector2(0, 0)]
}`
|_sub_resource_ |*tracks/1/type* |`value`
|_sub_resource_ |*tracks/1/imported* |`false`
|_sub_resource_ |*tracks/1/enabled* |`true`
|_sub_resource_ |*tracks/1/path* |`NodePath(".:flicked")`
|_sub_resource_ |*tracks/1/interp* |`1`
|_sub_resource_ |*tracks/1/loop_wrap* |`true`
|_sub_resource_ |*tracks/1/keys* |`{
"times": PackedFloat32Array(0.0333333),
"transitions": PackedFloat32Array(1),
"update": 1,
"values": [false]
}`
|_sub_resource_ |*_data* |`{
&"RESET": SubResource("Animation_tk6ev"),
&"flick": SubResource("Animation_m1pfy"),
&"pull": SubResource("Animation_8t8dd")
}`
|_node_ |*texture_filter* |`2`
|_node_ |*rotation* |`-0.132838`
|_node_ |*texture* |`ExtResource("1_cvkuv")`
|_node_ |*script* |`ExtResource("2_khtv3")`
|_node_ |*clip_children* |`1`
|_node_ |*position* |`Vector2(0.132448, -0.99119)`
|_node_ |*polygon* |`PackedVector2Array(-231.306, -164.081, 230.871, -164.874, 231.259, 96.4797, -231.777, 96.1488)`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*position* |`Vector2(-0.102002, -34.1747)`
|_node_ |*scale* |`Vector2(0.772257, 0.767854)`
|_node_ |*texture* |`ExtResource("3_y3tgv")`
|_node_ |*anchors_preset* |`-1`
|_node_ |*anchor_left* |`0.307`
|_node_ |*anchor_top* |`0.843`
|_node_ |*anchor_right* |`0.307`
|_node_ |*anchor_bottom* |`0.843`
|_node_ |*offset_left* |`-234.403`
|_node_ |*offset_top* |`-200.2`
|_node_ |*offset_right* |`67.597`
|_node_ |*offset_bottom* |`-200.2`
|_node_ |*rotation* |`-0.00349066`
|_node_ |*alignment* |`2`
|_node_ |*visible* |`false`
|_node_ |*layout_mode* |`2`
|_node_ |*theme_override_constants/margin_right* |`30`
|_node_ |*scale* |`Vector2(0.15, 0.15)`
|_node_ |*texture* |`ExtResource("2_7p363")`
|_node_ |*layout_mode* |`2`
|_node_ |*theme_override_constants/margin_right* |`30`
|_node_ |*scale* |`Vector2(0.15, 0.15)`
|_node_ |*texture* |`ExtResource("3_7dyr3")`
|_node_ |*layout_mode* |`2`
|_node_ |*theme_override_constants/margin_right* |`30`
|_node_ |*scale* |`Vector2(0.15, 0.15)`
|_node_ |*texture* |`ExtResource("2_7p363")`
|_node_ |*unique_name_in_owner* |`true`
|_node_ |*libraries* |`{
"": SubResource("AnimationLibrary_ih3et")
}`
|===


=== link:/scripts/src/beginning/chapters/menu/photo/photo.gd[photo.gd]

```gdscript
extends Sprite2D

@export var flicked: bool = false
@export var image : Texture2D : set = set_image


func set_image(image: Texture2D) -> void:
	%Image.texture = image


func flick() -> void:
	if not flicked: %AnimationPlayer.play("flick")


func pull() -> void:
	if flicked: %AnimationPlayer.play("pull")

```


