---
title: src/beginning/chapters/menu/photo/photo.tscn
---
:toc:

== src / beginning / chapters / menu / photo / photo.tscn

=== Diagram
[plantuml]
....
class R as "Photo" <<(S,lightskyblue) Sprite2D>> {
  * flicked
  * image
---
  + set_image()
  + flick()
  + pull()
}
class N1 as "Frame" <<(P,lightskyblue) Polygon2D>> {
}
class N2 as "Image" <<(S,lightskyblue) Sprite2D>> {
}
class N3 as "Strawberries" <<(H,lightgreen) HBoxContainer>> {
}
class N4 as "Strawberry1" <<(M,lightgreen) MarginContainer>> {
}
class N5 as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class N6 as "Strawberry2" <<(M,lightgreen) MarginContainer>> {
}
class N7 as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class N8 as "Strawberry3" <<(M,lightgreen) MarginContainer>> {
}
class N9 as "Strawberry" <<(S,lightskyblue) Sprite2D>> {
}
class N10 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
R --o N3
R --o N10
N1 --o N2
N3 --o N4
N3 --o N6
N3 --o N8
N4 --o N5
N6 --o N7
N8 --o N9
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....





=== Instantiators
* link:/scenes/src/beginning/chapters/menu/menu.tscn[res://src/beginning/chapters/menu/menu.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Photo# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-2d]#Frame# [.node-type.type-2d]#Polygon2D#
*** [.node-name.type-2d]#Image# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-control]#Strawberries# [.node-type.type-control]#HBoxContainer#
*** [.node-name.type-control]#Strawberry1# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-control]#Strawberry2# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
*** [.node-name.type-control]#Strawberry3# [.node-type.type-control]#MarginContainer#
**** [.node-name.type-2d]#Strawberry# [.node-type.type-2d]#Sprite2D#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
NOTE: No signal connections.

=== Animations
==== Animation_tk6ev

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)
R  ->o  R : flicked\n = false


....
---

==== flick

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)
== Time: 0.0333333 ==
R  ->o  R : flicked\n = true
== Time: 0.5 ==
R  ->  R : position\n = Vector2(1920, 0)


....
---

==== pull

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(1920, 0)
== Time: 0.0333333 ==
R  ->o  R : flicked\n = false
== Time: 0.5 ==
R  ->  R : position\n = Vector2(0, 0)


....
---



=== Properties
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture_filter* |`2`
|*rotation* |`-0.132838`
|*texture* |`ExtResource("1_cvkuv")`
|*script* |`ExtResource("2_khtv3")`
|===
.#$Frame# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*clip_children* |`1`
|*position* |`Vector2(0.132448, -0.99119)`
|*polygon* |`PackedVector2Array(-231.306, -164.081, 230.871, -164.874, 231.259, 96.4797, -231.777, 96.1488)`
|===
.#$Frame/Image# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*position* |`Vector2(-0.102002, -34.1747)`
|*scale* |`Vector2(0.772257, 0.767854)`
|*texture* |`ExtResource("3_y3tgv")`
|===
.#$Strawberries# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*anchors_preset* |`-1`
|*anchor_left* |`0.307`
|*anchor_top* |`0.843`
|*anchor_right* |`0.307`
|*anchor_bottom* |`0.843`
|*offset_left* |`-234.403`
|*offset_top* |`-200.2`
|*offset_right* |`67.597`
|*offset_bottom* |`-200.2`
|*rotation* |`-0.00349066`
|*alignment* |`2`
|===
.#$Strawberries/Strawberry1# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*visible* |`false`
|*layout_mode* |`2`
|*theme_override_constants/margin_right* |`30`
|===
.#$Strawberries/Strawberry1/Strawberry# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.15, 0.15)`
|*texture* |`ExtResource("2_7p363")`
|===
.#$Strawberries/Strawberry2# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|*theme_override_constants/margin_right* |`30`
|===
.#$Strawberries/Strawberry2/Strawberry# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.15, 0.15)`
|*texture* |`ExtResource("3_7dyr3")`
|===
.#$Strawberries/Strawberry3# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*layout_mode* |`2`
|*theme_override_constants/margin_right* |`30`
|===
.#$Strawberries/Strawberry3/Strawberry# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*scale* |`Vector2(0.15, 0.15)`
|*texture* |`ExtResource("2_7p363")`
|===
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* |`true`
|*libraries* |`{
"": SubResource("AnimationLibrary_ih3et")
}`
|===


=== link:/scripts/src/beginning/chapters/menu/photo/photo.gd[photo.gd]

```gdscript
extends Sprite2D

@export var flicked: bool = false
@export var image : Texture2D : set = set_image


func set_image(image: Texture2D) -> void:
	%Image.texture = image


func flick() -> void:
	if not flicked: %AnimationPlayer.play("flick")


func pull() -> void:
	if flicked: %AnimationPlayer.play("pull")

```


