---
title: src/player/camera/camera.tscn
---
:toc:

== src / player / camera / camera.tscn

=== Diagram
[plantuml]
....
class R as "Camera" <<(C,#87CEFA) Camera2D>> {
  - DASH_SHAKING_TIME
  * shaking_time
  * fixed_position
  * current_frames
---
  + _process()
  + add_frame()
  + remove_frame()
  + apply_limitation()
  + shake()
  + shaking()
}
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _process
```gdscript
func _process(delta: float) -> void:
	if shaking_time:
		shaking_time = maxf(0.0, shaking_time - delta)
		shaking()
```


=== Instantiators
* link:/scenes/src/player/player.tscn[res://src/player/player.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Camera# [.node-type.type-2d]#Camera2D#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*limit_left* |`0`
|*limit_bottom* |`1080`
|*limit_smoothed* |`true`
|*position_smoothing_enabled* |`true`
|*script* |`ExtResource("1_ak8su")`
|===


=== link:/scripts/src/player/camera/camera.gd[camera.gd]

```gdscript
extends Camera2D

const DASH_SHAKING_TIME = 0.5
var shaking_time := 0.0
var fixed_position := Vector2(0, 0)
var current_frames : Array


func _process(delta: float) -> void:
	if shaking_time:
		shaking_time = maxf(0.0, shaking_time - delta)
		shaking()


func add_frame(frame: Area2D) -> void:
	current_frames.push_back(frame)
	apply_limitation()


func remove_frame(frame: Area2D) -> void:
	var idx = current_frames.find(frame)
	current_frames.remove_at(idx)
	apply_limitation()


func apply_limitation() -> void:
	if current_frames:
		var corners  = current_frames.map(func(f): return f.corner())
		limit_left   = corners.map(func(c): return c["left"]).min()
		limit_right  = corners.map(func(c): return c["right"]).max()
		limit_bottom = corners.map(func(c): return c["top"]).min()
		limit_top    = corners.map(func(c): return c["bottom"]).max()
	else:
		limit_left   = 0
		limit_right  = 10000
		limit_bottom = -10000
		limit_top    = 10000


func shake(type: StringName) -> void:
	match type:
		&'dash':
			shaking_time = DASH_SHAKING_TIME


func shaking() -> void:
	offset.x = 10 * randf_range(-1, 1) * shaking_time
	offset.y = 8 * randf_range(-1, 1) * shaking_time

```


