---
title: src/player/hair/hair.tscn
---
:toc:

== src / player / hair / hair.tscn

=== Diagram
[plantuml]
....
class R as "Hair" <<(N,lightskyblue) Node2D>> {
  - SEGMENT_COUNT
  - MAX_DISTANCE
  - LERP_SPEED
  - BASE_RADIUS
  - OUTLINE_WIDTH
  - DECREASE_RATE
  * base_color
  * dash_color
  * color
  * positions
---
  + _ready()
  + _process()
  + _draw()
  + set_dashed()
}
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction

....




=== Overridden virtual functions
==== _ready
```gdscript
func _ready() -> void:
	positions.clear()
	for i in range(SEGMENT_COUNT):
		positions.append(global_position)
```
==== _process
```gdscript
func _process(delta: float) -> void:
	if positions.is_empty(): return
	positions[0] = global_position
	
	for i in range(1, SEGMENT_COUNT):
		var target = positions[i-1]
		var diff = positions[i] - target
		if diff.length() > MAX_DISTANCE:
			positions[i] = target + diff.normalized() * MAX_DISTANCE
		positions[i] = positions[i].lerp(target, LERP_SPEED * delta)
	
	queue_redraw()
```
==== _draw
```gdscript
func _draw() -> void:
	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r + OUTLINE_WIDTH, Color.BLACK)

	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r, color)
```


=== Instantiators
* link:/scenes/debug/hair/node_2d.tscn[res://debug/hair/node_2d.tscn]
* link:/scenes/src/player/player.tscn[res://src/player/player.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-2d]#Hair# [.node-type.type-2d]#Node2D#


=== Signal Connections
NOTE: No signal connections.



=== Properties
[.node-property.node-2d]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*script* a|link:/scripts/src/player/hair/hair.gd[res://src/player/hair/hair.gd]
|===


=== link:/scripts/src/player/hair/hair.gd[hair.gd]

```gdscript
@tool
extends Node2D

var base_color : Color = Color('e0872f')
var dash_color : Color = Color(0.1, 0.8, 1.0)
@onready var color : Color = base_color
const SEGMENT_COUNT := 5
const MAX_DISTANCE := 15.0
const LERP_SPEED := 20.0
const BASE_RADIUS := 3.8
const OUTLINE_WIDTH := 1.0
const DECREASE_RATE := 0.75

var positions: Array[Vector2] = []


func _ready() -> void:
	positions.clear()
	for i in range(SEGMENT_COUNT):
		positions.append(global_position)


func _process(delta: float) -> void:
	if positions.is_empty(): return
	positions[0] = global_position
	
	for i in range(1, SEGMENT_COUNT):
		var target = positions[i-1]
		var diff = positions[i] - target
		if diff.length() > MAX_DISTANCE:
			positions[i] = target + diff.normalized() * MAX_DISTANCE
		positions[i] = positions[i].lerp(target, LERP_SPEED * delta)
	
	queue_redraw()


func _draw() -> void:
	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r + OUTLINE_WIDTH, Color.BLACK)

	for i in range(SEGMENT_COUNT - 1, -1, -1):
		var r = BASE_RADIUS * (1.0 - float(i) / SEGMENT_COUNT * DECREASE_RATE)
		draw_circle(to_local(positions[i]), r, color)


func set_dashed(val: bool) -> void:
	color = dash_color if val else base_color

```


