---
title: src/ui/button/button.tscn
---
:toc:

== src / ui / button / button.tscn

=== Diagram
[plantuml]
....
class R as "Button" <<(B,lightgreen) Button>> {
  - BLINK_INTERVAL
  * focus_move_direction
  * focus_color_1
  * focus_color_2
  * blink_time
  * focused
---
  + _process()
  + get_focus_color()
  + focus_move_direction_key()
  + _on_focus_entered()
  + _on_focus_exited()
}
class N1 as "AnimationPlayer" <<(A,yellow) AnimationPlayer>> {
}
R --o N1
!define _(a,b) a <-[#blue,thickness=2]- b
left to right direction
_(R::_on_focus_entered, R::focus_entered)
_(R::_on_focus_exited, R::focus_exited)
....


[.scene-assets]
=== Assets
[.asset-image]
[link=/assets/assets/images/ui/Options.svg]
image::/assets/raw/assets/images/ui/Options.svg[200, 100] 



=== Overridden virtual functions
==== _process
```gdscript
func _process(delta: float) -> void:
	if not focused: return
	blink_time += delta
	add_theme_color_override("font_focus_color", get_focus_color())
	if blink_time > BLINK_INTERVAL: blink_time = 0
```


=== Instantiators
* link:/scenes/src/account/account.tscn[res://src/account/account.tscn]
* link:/scenes/src/beginning/menu/menu.tscn[res://src/beginning/menu/menu.tscn]


=== Scene Tree
[.scene-tree]
* [.node-name.type-control]#Button# [.node-type.type-control]#Button#
** [.node-name.type-other]#AnimationPlayer# [.node-type.type-other]#AnimationPlayer#


=== Signal Connections
[.signal-connection]
.$.:[#_focus_entered_#]=>$.
```gdscript
func _on_focus_entered() -> void:
	focused = true
	%AnimationPlayer.play("focused_%s" % [focus_move_direction_key()])
```
[.signal-connection]
.$.:[#_focus_exited_#]=>$.
```gdscript
func _on_focus_exited() -> void:
	focused = false
	%AnimationPlayer.play("unfocused_%s" % [focus_move_direction_key()])
```


=== Animations
==== Animation_evwsm

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)


....
---

==== focused_none

[plantuml]
....
control "Root" as R





....
---

==== focused_right

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)
== Time: 0.1 ==
R  ->  R : position\n = Vector2(10, 2)
== Time: 0.233333 ==
R  ->  R : position\n = Vector2(25, -5)
== Time: 1.0 ==
R  ->  R : position\n = Vector2(50, -5)


....
---

==== focused_up

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, 0)
== Time: 0.1 ==
R  ->  R : position\n = Vector2(0, 5)
== Time: 0.2 ==
R  ->  R : position\n = Vector2(0, -10)
== Time: 1.0 ==
R  ->  R : position\n = Vector2(0, -5)


....
---

==== unfocused_none

[plantuml]
....
control "Root" as R





....
---

==== unfocused_right

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(50, -5)
== Time: 0.5 ==
R  ->  R : position\n = Vector2(0, 0)


....
---

==== unfocused_up

[plantuml]
....
control "Root" as R



== Time: 0.0 ==
R  ->  R : position\n = Vector2(0, -5)
== Time: 0.5 ==
R  ->  R : position\n = Vector2(0, 0)


....
---



=== Properties
[.node-property.node-control]
.#Root# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*texture_filter* a|`2`
|*offset_right* a|`287.0`
|*offset_bottom* a|`91.0`
|*theme* a|`ExtResource("1_r8ale")`
|*text* a|` Button`
|*icon* a|[link=/assets/assets/images/ui/Options.svg]
[.asset-image]
.res://assets/images/ui/Options.svg
image::/assets/raw/assets/images/ui/Options.svg[]

|*flat* a|`true`
|*alignment* a|`0`
|*script* a|link:/scripts/src/ui/button/button.gd[res://src/ui/button/button.gd]
|*focus_color_1* a|`Color(0.5, 1, 0.5, 1)`
|*focus_color_2* a|`Color(1, 1, 0.5, 1)`
|===
[.node-property.node-other]
.#$AnimationPlayer# properties
[cols="1,3" options="header"]
|===
|Name |Value
|*unique_name_in_owner* a|`true`
|*libraries* a|`{
"": SubResource("AnimationLibrary_c4kiu")
}`
|===


=== link:/scripts/src/ui/button/button.gd[button.gd]

```gdscript
extends Button

@export var focus_move_direction : FocusMoveDirection
@export_color_no_alpha var focus_color_1 : Color
@export_color_no_alpha var focus_color_2 : Color
enum FocusMoveDirection { RIGHT, UP, NONE }

const BLINK_INTERVAL := 0.2
var blink_time := 0.0
var focused := false


func _process(delta: float) -> void:
	if not focused: return
	blink_time += delta
	add_theme_color_override("font_focus_color", get_focus_color())
	if blink_time > BLINK_INTERVAL: blink_time = 0


func get_focus_color() -> Color:
	if blink_time > BLINK_INTERVAL / 2:
		return focus_color_1
	else:
		return focus_color_2


func focus_move_direction_key() -> String:
	return FocusMoveDirection.find_key(focus_move_direction).to_lower()


func _on_focus_entered() -> void:
	focused = true
	%AnimationPlayer.play("focused_%s" % [focus_move_direction_key()])


func _on_focus_exited() -> void:
	focused = false
	%AnimationPlayer.play("unfocused_%s" % [focus_move_direction_key()])

```


